var CompConfigMap={
	    'Ext.form.field.Text':{
									fieldLabel:'新建',
									columnWidth:0.3
								},
	    'Ext.form.field.TextArea':{
									fieldLabel:'新建',
									columnWidth:0.3
								},
	    'Ext.form.field.Radio':{
									fieldLabel:'新建',
									columnWidth:0.3
								},
	    'Ext.form.field.Checkbox':{
									fieldLabel:'新建',
									columnWidth:0.3
								},
	    'Ext.form.field.Date':{
									fieldLabel:'新建',
									columnWidth:0.3
								},
	    'Ext.form.field.ComboBox':{
									fieldLabel:'新建',
									columnWidth:0.3
								},
	    'Ext.button.Button':{
									fieldLabel:'新建',
									columnWidth:0.3
								},
	    
	    
	    'Ext.form.Panel':{
							width:300,
							resizable:true,
							height:300
						},
	    'Ext.Panel'		:{
							width:300,
							resizable:true,
							height:300
						},
	    'Ext.grid.Panel':{
							width:300,
							resizable:true,
							height:300
						},
	    'Ext.tree.Panel':{
							width:300,
							resizable:true,
							height:300
						}
};