Ext
		.define(
				'Pallas.portal.waapp.lib.Cache',
				{
					requires:["Pallas.web.waapp.lib.cache.bpm.Modules",
					          "Pallas.web.waapp.lib.cache.bpm.Menus",
					          "Pallas.web.waapp.lib.cache.bpm.Views",
					          "Pallas.web.waapp.lib.cache.bpm.Documents",
					          "Pallas.web.waapp.lib.cache.bpm.DocumentTypes",
					          "Pallas.web.waapp.lib.cache.bpm.Dictionarys"],
					statics : {
						// private 根据ID获得菜单
						getMenuById : function(id) {
							for (n in Pallas.portal.waapp.lib.Cache.Menus) {
								if (Pallas.portal.waapp.lib.Cache.Menus[n].id == id) {
									return Pallas.portal.waapp.lib.Cache.Menus[n];
								}
							}
						},

						getAppModule : function(appkey, modulekey) {
							var modules = eval('Pallas.web.waapp.lib.cache.' + appkey
									+ '.Modules');
							return modules[modulekey];
						},
						getAppModuleMenus : function(appkey) {
							return eval('Pallas.web.waapp.lib.cache.' + appkey
									+ '.Menus');
						},
						getAppModuleMenu : function(appkey, menukey) {
							var menus = eval('Pallas.web.waapp.lib.cache.' + appkey
									+ '.Menus');
							return menus[menukey];
						},
						getAppModuleView : function(appkey, viewkey) {
							var views = eval('Pallas.web.waapp.lib.cache.' + appkey
									+ '.Views');
							return views[viewkey];
						},
						getAppDocument : function(appkey, documentkey) {
							var documents = eval('Pallas.web.waapp.lib.cache.' + appkey
									+ '.Documents');
							return documents[documentkey];
						},
						getAppDocumentType : function(appkey, documenttypekey) {
							var documenttypes = eval('Pallas.web.waapp.lib.cache.'
									+ appkey + '.DocumentTypes');
							return documenttypes[documenttypekey];
						},
						getDictionary : function(appkey, dictionarykey) {
							var dictionarys;
							if (Ext.isDefined(appkey) && appkey != '') {
								dictionarys = eval('Pallas.web.waapp.lib.cache.'
										+ appkey + '.Dictionarys');
							} else {
								dictionarys = Pallas.portal.waapp.lib.Cache.Dictionarys;
							}
							return dictionarys[dictionarykey];
						},
						Dictionarys : {

						},
						Applications : {
							'guiji' : {
								key : 'guiji',
								keyPrefix : 'Guiji',
								text : 'guiji',
								url : '/guiji',
								name : 'guiji'
							},
							'crm' : {
								key : 'crm',
								keyPrefix : 'Crm',
								text : 'crm',
								url : '/crm',
								name : 'crm'
							},
							'OA' : {
								key : 'OA',
								keyPrefix : 'Oa',
								text : 'OA',
								url : '/OA',
								name : 'OA'
							},
							'bpm' : {
								key : 'bpm',
								keyPrefix : 'Bpm',
								text : 'bpm',
								url : '/bpm',
								name : 'bpm'
							}
						},
						Menus : {
							'DSK' : {
								id : 100,
								parentId : 0,
								level : 1,
								applicationkey : 'OA',
								type : 'sysmodulemenu',
								modulekey : 'waWorkBench',
								text : '工作桌面',
								iconCls : 'icon-portal-menu-workdesk',
								qtip : '',
								name : 'DSK'
							},
							'SYS' : {
								id : 32,
								parentId : 0,
								level : 1,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '系统配置',
								iconCls : 'icon-portal-menu-sysconf',
								qtip : '',
								name : 'SYS'
							},
							'SYS1' : {
								id : 33,
								parentId : 32,
								level : 2,
								applicationkey : 'bpm',
								type : 'sysmodulemenu',
								modulekey : 'waBpmZx',
								text : '流程中心',
								iconCls : 'icon-portal-menu-sysconf-process',
								qtip : '',
								name : 'SYS1'
							},
							'SYS2' : {
								id : 34,
								parentId : 32,
								level : 2,
								applicationkey : 'OA',
								type : 'sysmodulemenu',
								modulekey : 'waTybmgl',
								text : '编码中心',
								iconCls : 'icon-portal-menu-sysconf-code',
								qtip : '',
								name : 'SYS2'
							},
							'SYS4' : {
								id : 36,
								parentId : 32,
								level : 2,
								applicationkey : 'OA',
								type : 'sysmodulemenu',
								modulekey : 'waSysYwcs',
								text : '参数配置',
								iconCls : 'icon-portal-menu-sysconf-config',
								qtip : '',
								name : 'SYS4'
							},
							'SYS6' : {
								id : 38,
								parentId : 32,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '运维管控',
								iconCls : 'icon-portal-menu-sysconf-monitor',
								qtip : '',
								name : 'SYS6'
							},
							'SYS7' : {
								id : 39,
								parentId : 32,
								level : 2,
								applicationkey : 'OA',
								type : 'sysmodulemenu',
								modulekey : 'waDatatypesgl',
								text : '数据字典',
								iconCls : 'icon-portal-menu-sysconf-datadic',
								qtip : '',
								name : 'SYS7'
							},
							'SYS8' : {
								id : 40,
								parentId : 32,
								level : 2,
								applicationkey : 'OA',
								type : 'sysmodulemenu',
								modulekey : 'waCzygl',
								text : '用户管理',
								iconCls : 'icon-portal-menu-sysconf-usermanager',
								qtip : '',
								name : 'SYS8'
							},
							'SYS9' : {
								id : 41,
								parentId : 32,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '报表管理',
								iconCls : 'icon-portal-menu-sysconf-report',
								qtip : '',
								name : 'SYS9'
							},
							'SYS11' : {
								id : 299,
								parentId : 32,
								level : 2,
								applicationkey : 'daikuan',
								type : 'sysmodulemenu',
								modulekey : 'wadksz',
								text : '贷款设置',
								iconCls : 'icon-portal-menu-sysconf-config',
								qtip : '',
								name : 'SYS11'
							},
							'SYS12' : {
								id : 315,
								parentId : 32,
								level : 2,
								applicationkey : 'txdk',
								type : 'sysmodulemenu',
								modulekey : 'waTxsz',
								text : '贴息设置',
								iconCls : 'icon-portal-menu-sysconf-config',
								qtip : '',
								name : 'SYS12'
							},
							'report_zjxt' : {
								id : 159,
								parentId : 41,
								level : 3,
								applicationkey : 'report',
								type : 'sysmodulemenu',
								modulekey : 'report_zjxt',
								text : '资金管理',
								iconCls : '',
								qtip : '',
								name : 'report_zjxt'
							},
							'report_guiji' : {
								id : 160,
								parentId : 41,
								level : 3,
								applicationkey : 'report',
								type : 'sysmodulemenu',
								modulekey : 'report_guiji',
								text : '归集支付',
								iconCls : '',
								qtip : '',
								name : 'report_guiji'
							},
							'report_dkdb' : {
								id : 161,
								parentId : 41,
								level : 3,
								applicationkey : 'report',
								type : 'sysmodulemenu',
								modulekey : 'report_dkdb',
								text : '贷款担保',
								iconCls : '',
								qtip : '',
								name : 'report_dkdb'
							},
							'report_wazj' : {
								id : 162,
								parentId : 41,
								level : 3,
								applicationkey : 'report',
								type : 'sysmodulemenu',
								modulekey : 'report_wazj',
								text : '资金管理',
								iconCls : '',
								qtip : '',
								name : 'report_wazj'
							},
							'report_console' : {
								id : 163,
								parentId : 41,
								level : 3,
								applicationkey : 'report',
								type : 'sysmodulemenu',
								modulekey : 'report_console',
								text : '控制台',
								iconCls : '',
								qtip : '',
								name : 'report_console'
							},
							'report_bzj ' : {
								id : 164,
								parentId : 41,
								level : 3,
								applicationkey : 'report',
								type : 'sysmodulemenu',
								modulekey : 'report_bzj ',
								text : '保证金',
								iconCls : '',
								qtip : '',
								name : 'report_bzj '
							},
							'report_unitapp' : {
								id : 165,
								parentId : 41,
								level : 3,
								applicationkey : 'report',
								type : 'sysmodulemenu',
								modulekey : 'report_unitapp',
								text : '网上大厅',
								iconCls : '',
								qtip : '',
								name : 'report_unitapp'
							},
							'report_test ' : {
								id : 166,
								parentId : 41,
								level : 3,
								applicationkey : 'report',
								type : 'sysmodulemenu',
								modulekey : 'report_test ',
								text : '测试报表',
								iconCls : '',
								qtip : '',
								name : 'report_test '
							},
							'report_wacw' : {
								id : 167,
								parentId : 41,
								level : 3,
								applicationkey : 'report',
								type : 'sysmodulemenu',
								modulekey : 'report_wacw',
								text : '会计核算',
								iconCls : '',
								qtip : '',
								name : 'report_wacw'
							},
							'report_wxzj' : {
								id : 168,
								parentId : 41,
								level : 3,
								applicationkey : 'report',
								type : 'sysmodulemenu',
								modulekey : 'report_wxzj',
								text : '公共维修资金',
								iconCls : '',
								qtip : '',
								name : 'report_wxzj'
							},
							'report_daikuan' : {
								id : 169,
								parentId : 41,
								level : 3,
								applicationkey : 'report',
								type : 'sysmodulemenu',
								modulekey : 'report_daikuan',
								text : '个人贷款',
								iconCls : '',
								qtip : '',
								name : 'report_daikuan'
							},
							'report_wada' : {
								id : 170,
								parentId : 41,
								level : 3,
								applicationkey : 'report',
								type : 'sysmodulemenu',
								modulekey : 'report_wada',
								text : '档案管理',
								iconCls : '',
								qtip : '',
								name : 'report_wada'
							},
							'report_sfk' : {
								id : 171,
								parentId : 41,
								level : 3,
								applicationkey : 'report',
								type : 'sysmodulemenu',
								modulekey : 'report_sfk',
								text : '售房款',
								iconCls : '',
								qtip : '',
								name : 'report_sfk'
							},
							'SYS10' : {
								id : 107,
								parentId : 32,
								level : 2,
								applicationkey : 'OA',
								type : 'sysmodulemenu',
								modulekey : 'waArchiveconf',
								text : '档案管理',
								iconCls : 'icon-portal-menu-sysconf-file',
								qtip : '',
								name : 'SYS10'
							},
							'MAN' : {
								id : 43,
								parentId : 0,
								level : 1,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '行政管理',
								iconCls : 'icon-portal-menu-orgman',
								qtip : '',
								name : 'MAN'
							},
							'MAN1' : {
								id : 48,
								parentId : 43,
								level : 2,
								applicationkey : 'OA',
								type : 'sysmodulemenu',
								modulekey : 'waZzjg',
								text : '组织机构',
								iconCls : 'icon-portal-menu-orgman-org',
								qtip : '',
								name : 'MAN1'
							},
							'MAN2' : {
								id : 225,
								parentId : 43,
								level : 2,
								applicationkey : 'OA',
								type : 'sysmodulemenu',
								modulekey : 'waHrgl',
								text : '人力资源管理',
								iconCls : 'icon-portal-menu-orgman-person',
								qtip : '',
								name : 'MAN2'
							},
							'MAN3' : {
								id : 226,
								parentId : 43,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '电子政务',
								iconCls : 'icon-portal-menu-orgman-oa',
								qtip : '',
								name : 'MAN3'
							},
							'mkCalendar' : {
								id : 275,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkCalendar',
								text : '日历日程',
								iconCls : '',
								qtip : '',
								name : 'mkCalendar'
							},
							'mkTodo' : {
								id : 276,
								parentId : 226,
								level : 3,
								applicationkey : 'OA',
								type : 'sysmodulemenu',
								modulekey : 'mkTodo',
								text : '待办事宜',
								iconCls : '',
								qtip : '',
								name : 'mkTodo'
							},
							'mkNotify' : {
								id : 277,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkNotify',
								text : '通知公告',
								iconCls : '',
								qtip : '',
								name : 'mkNotify'
							},
							'mkWorkReport' : {
								id : 278,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkWorkReport',
								text : '工作简报',
								iconCls : '',
								qtip : '',
								name : 'mkWorkReport'
							},
							'mkKnowledge' : {
								id : 279,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkKnowledge',
								text : '知识管理',
								iconCls : '',
								qtip : '',
								name : 'mkKnowledge'
							},
							'mkMail' : {
								id : 280,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkMail',
								text : '电子邮件',
								iconCls : '',
								qtip : '',
								name : 'mkMail'
							},
							'mkFavorite' : {
								id : 281,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkFavorite',
								text : '收藏夹',
								iconCls : '',
								qtip : '',
								name : 'mkFavorite'
							},
							'mkRegulations' : {
								id : 282,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkRegulations',
								text : '规章制度',
								iconCls : '',
								qtip : '',
								name : 'mkRegulations'
							},
							'mkNetFolder' : {
								id : 283,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkNetFolder',
								text : '网络文件柜',
								iconCls : '',
								qtip : '',
								name : 'mkNetFolder'
							},
							'mkVote' : {
								id : 284,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkVote',
								text : '投票管理',
								iconCls : '',
								qtip : '',
								name : 'mkVote'
							},
							'mkWorkRequest' : {
								id : 285,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkWorkRequest',
								text : '请示报告',
								iconCls : '',
								qtip : '',
								name : 'mkWorkRequest'
							},
							'mkMeetingManage' : {
								id : 286,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkMeetingManage',
								text : '会议管理',
								iconCls : '',
								qtip : '',
								name : 'mkMeetingManage'
							},
							'mkAddressBook' : {
								id : 287,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkAddressBook',
								text : '通讯录',
								iconCls : '',
								qtip : '',
								name : 'mkAddressBook'
							},
							'mktrain' : {
								id : 288,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mktrain',
								text : '员工培训',
								iconCls : '',
								qtip : '',
								name : 'mktrain'
							},
							'mkSendDocument' : {
								id : 289,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkSendDocument',
								text : '发文管理',
								iconCls : '',
								qtip : '',
								name : 'mkSendDocument'
							},
							'mkAttendance' : {
								id : 291,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkAttendance',
								text : '考勤管理',
								iconCls : '',
								qtip : '',
								name : 'mkAttendance'
							},
							'mkgdzc' : {
								id : 464,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkgdzc',
								text : '固定资产',
								iconCls : '',
								qtip : '',
								name : 'mkgdzc'
							},
							'mkPersonnelManage' : {
								id : 465,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkPersonnelManage',
								text : '人事档案',
								iconCls : '',
								qtip : '',
								name : 'mkPersonnelManage'
							},
							'mkVehicle' : {
								id : 484,
								parentId : 226,
								level : 3,
								applicationkey : 'mkoa',
								type : 'sysmodulemenu',
								modulekey : 'mkVehicle',
								text : '车辆管理',
								iconCls : 'icon-app-mkoa-car',
								qtip : '',
								name : 'mkVehicle'
							},
							'MAN4' : {
								id : 51,
								parentId : 43,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '绩效管理',
								iconCls : 'icon-portal-menu-orgman-perf',
								qtip : '',
								name : 'MAN4'
							},
							'waXmgl' : {
								id : 245,
								parentId : 51,
								level : 3,
								applicationkey : 'OA',
								type : 'sysmodulemenu',
								modulekey : 'waXmgl',
								text : '项目管理',
								iconCls : 'icon-portal-menu-orgman-proj',
								qtip : '',
								name : 'waXmgl'
							},
							'waTasks' : {
								id : 246,
								parentId : 51,
								level : 3,
								applicationkey : 'OA',
								type : 'sysmodulemenu',
								modulekey : 'waTasks',
								text : '任务管理',
								iconCls : 'icon-portal-menu-orgman-task',
								qtip : '',
								name : 'waTasks'
							},
							'Log' : {
								id : 247,
								parentId : 51,
								level : 3,
								applicationkey : 'OA',
								type : 'sysmodulegroup',
								text : '日志管理',
								iconCls : 'icon-portal-menu-orgman-log',
								qtip : '',
								name : 'Log'
							},
							'waKqgl' : {
								id : 248,
								parentId : 247,
								level : 4,
								applicationkey : 'OA',
								type : 'sysmodulemenu',
								modulekey : 'waKqgl',
								text : '考勤管理',
								iconCls : '',
								qtip : '',
								name : 'waKqgl'
							},
							'waLogxx' : {
								id : 249,
								parentId : 247,
								level : 4,
								applicationkey : 'OA',
								type : 'sysmodulemenu',
								modulekey : 'waLogxx',
								text : '工作日志',
								iconCls : '',
								qtip : '',
								name : 'waLogxx'
							},
							'MAN5' : {
								id : 52,
								parentId : 43,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '统计分析',
								iconCls : 'icon-portal-menu-orgman-analyse',
								qtip : '',
								name : 'MAN5'
							},
							'BUS' : {
								id : 350,
								parentId : 0,
								level : 1,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '业务应用',
								iconCls : 'icon-portal-menu-busapp',
								qtip : '',
								name : 'BUS'
							},
							'BUS1' : {
								id : 355,
								parentId : 350,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '归集提取',
								iconCls : 'icon-portal-menu-busapp-gj',
								qtip : '',
								name : 'BUS1'
							},
							'Crm1' : {
								id : 77,
								parentId : 68,
								level : 3,
								applicationkey : 'crm',
								type : 'sysmodulemenu',
								modulekey : 'waCrmKhgl',
								text : '客户管理',
								iconCls : '',
								qtip : '',
								name : 'Crm1'
							},
							'gz_dwzhgl' : {
								id : 366,
								parentId : 355,
								level : 3,
								applicationkey : 'guiji',
								type : 'sysmodulemenu',
								modulekey : 'gz_dwzhgl',
								text : '单位账户管理',
								iconCls : '',
								qtip : '',
								name : 'gz_dwzhgl'
							},
							'gz_grzhgl' : {
								id : 367,
								parentId : 355,
								level : 3,
								applicationkey : 'guiji',
								type : 'sysmodulemenu',
								modulekey : 'gz_grzhgl',
								text : '个人账户管理',
								iconCls : '',
								qtip : '',
								name : 'gz_grzhgl'
							},
							'gz_grzhzy' : {
								id : 368,
								parentId : 355,
								level : 3,
								applicationkey : 'guiji',
								type : 'sysmodulemenu',
								modulekey : 'gz_grzhzy',
								text : '账户转移',
								iconCls : '',
								qtip : '',
								name : 'gz_grzhzy'
							},
							'gz_hbjyw' : {
								id : 369,
								parentId : 355,
								level : 3,
								applicationkey : 'guiji',
								type : 'sysmodulemenu',
								modulekey : 'gz_hbjyw',
								text : '汇补缴业务',
								iconCls : '',
								qtip : '',
								name : 'gz_hbjyw'
							},
							'gz_tqyw' : {
								id : 370,
								parentId : 355,
								level : 3,
								applicationkey : 'guiji',
								type : 'sysmodulemenu',
								modulekey : 'gz_tqyw',
								text : '提取业务',
								iconCls : '',
								qtip : '',
								name : 'gz_tqyw'
							},
							'gz_jcbg' : {
								id : 371,
								parentId : 355,
								level : 3,
								applicationkey : 'guiji',
								type : 'sysmodulemenu',
								modulekey : 'gz_jcbg',
								text : '缴存变更',
								iconCls : '',
								qtip : '',
								name : 'gz_jcbg'
							},
							'gz_jz' : {
								id : 372,
								parentId : 355,
								level : 3,
								applicationkey : 'guiji',
								type : 'sysmodulemenu',
								modulekey : 'gz_jz',
								text : '结账',
								iconCls : '',
								qtip : '',
								name : 'gz_jz'
							},
							'gz_lxjs' : {
								id : 373,
								parentId : 355,
								level : 3,
								applicationkey : 'guiji',
								type : 'sysmodulemenu',
								modulekey : 'gz_lxjs',
								text : '利息结算',
								iconCls : '',
								qtip : '',
								name : 'gz_lxjs'
							},
							'gz_tjcx' : {
								id : 374,
								parentId : 355,
								level : 3,
								applicationkey : 'guiji',
								type : 'sysmodulemenu',
								modulekey : 'gz_tjcx',
								text : '统计查询',
								iconCls : '',
								qtip : '',
								name : 'gz_tjcx'
							},
							'gz_gjzfsz' : {
								id : 375,
								parentId : 355,
								level : 3,
								applicationkey : 'guiji',
								type : 'sysmodulemenu',
								modulekey : 'gz_gjzfsz',
								text : '支付设置',
								iconCls : '',
								qtip : '',
								name : 'gz_gjzfsz'
							},
							'BUS2' : {
								id : 356,
								parentId : 350,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '个人贷款',
								iconCls : 'icon-portal-menu-busapp-gd',
								qtip : '',
								name : 'BUS2'
							},
							'waGdzx' : {
								id : 376,
								parentId : 356,
								level : 3,
								applicationkey : 'daikuan',
								type : 'sysmodulemenu',
								modulekey : 'waGdzx',
								text : '贷款咨询',
								iconCls : '',
								qtip : '',
								name : 'waGdzx'
							},
							'waGdsl' : {
								id : 377,
								parentId : 356,
								level : 3,
								applicationkey : 'daikuan',
								type : 'sysmodulemenu',
								modulekey : 'waGdsl',
								text : '贷款受理',
								iconCls : '',
								qtip : '',
								name : 'waGdsl'
							},
							'waGdsp' : {
								id : 378,
								parentId : 356,
								level : 3,
								applicationkey : 'daikuan',
								type : 'sysmodulemenu',
								modulekey : 'waGdsp',
								text : '贷款审批',
								iconCls : '',
								qtip : '',
								name : 'waGdsp'
							},
							'waGdphyw' : {
								id : 379,
								parentId : 356,
								level : 3,
								applicationkey : 'daikuan',
								type : 'sysmodulemenu',
								modulekey : 'waGdphyw',
								text : '批后管理',
								iconCls : '',
								qtip : '',
								name : 'waGdphyw'
							},
							'waGdwzxdj' : {
								id : 380,
								parentId : 356,
								level : 3,
								applicationkey : 'daikuan',
								type : 'sysmodulemenu',
								modulekey : 'waGdwzxdj',
								text : '外中心贷款申请',
								iconCls : '',
								qtip : '',
								name : 'waGdwzxdj'
							},
							'waDkhs' : {
								id : 381,
								parentId : 356,
								level : 3,
								applicationkey : 'daikuan',
								type : 'sysmodulemenu',
								modulekey : 'waDkhs',
								text : '贷款回收',
								iconCls : '',
								qtip : '',
								name : 'waDkhs'
							},
							'wadhgl' : {
								id : 382,
								parentId : 356,
								level : 3,
								applicationkey : 'daikuan',
								type : 'sysmodulemenu',
								modulekey : 'wadhgl',
								text : '贷后管理',
								iconCls : '',
								qtip : '',
								name : 'wadhgl'
							},
							'waGdyqgl' : {
								id : 383,
								parentId : 356,
								level : 3,
								applicationkey : 'daikuan',
								type : 'sysmodulemenu',
								modulekey : 'waGdyqgl',
								text : '逾期管理',
								iconCls : '',
								qtip : '',
								name : 'waGdyqgl'
							},
							'waGdllgl' : {
								id : 384,
								parentId : 356,
								level : 3,
								applicationkey : 'daikuan',
								type : 'sysmodulemenu',
								modulekey : 'waGdllgl',
								text : '利率管理',
								iconCls : '',
								qtip : '',
								name : 'waGdllgl'
							},
							'waGdhzgl' : {
								id : 385,
								parentId : 356,
								level : 3,
								applicationkey : 'daikuan',
								type : 'sysmodulemenu',
								modulekey : 'waGdhzgl',
								text : '合作单位管理',
								iconCls : '',
								qtip : '',
								name : 'waGdhzgl'
							},
							'waGdjz ' : {
								id : 386,
								parentId : 356,
								level : 3,
								applicationkey : 'daikuan',
								type : 'sysmodulemenu',
								modulekey : 'waGdjz',
								text : '结账',
								iconCls : '',
								qtip : '',
								name : 'waGdjz '
							},
							'waGdlstj' : {
								id : 387,
								parentId : 356,
								level : 3,
								applicationkey : 'daikuan',
								type : 'sysmodulemenu',
								modulekey : 'waGdlstj',
								text : '统计查询',
								iconCls : '',
								qtip : '',
								name : 'waGdlstj'
							},
							'BUS3' : {
								id : 357,
								parentId : 350,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '项目贷款',
								iconCls : 'icon-portal-menu-busapp-xmdk',
								qtip : '',
								name : 'BUS3'
							},
							'waXdkfsgl' : {
								id : 455,
								parentId : 357,
								level : 3,
								applicationkey : 'xmdk',
								type : 'sysmodulemenu',
								modulekey : 'waXdkfsgl',
								text : '开发商管理',
								iconCls : '',
								qtip : '',
								name : 'waXdkfsgl'
							},
							'waXdxmgl' : {
								id : 453,
								parentId : 357,
								level : 3,
								applicationkey : 'xmdk',
								type : 'sysmodulemenu',
								modulekey : 'waXdxmgl',
								text : '项目信息管理',
								iconCls : '',
								qtip : '',
								name : 'waXdxmgl'
							},
							'waXmzqmx' : {
								id : 454,
								parentId : 357,
								level : 3,
								applicationkey : 'xmdk',
								type : 'sysmodulemenu',
								modulekey : 'waXmzqmx',
								text : '项目支付明细登记',
								iconCls : '',
								qtip : '',
								name : 'waXmzqmx'
							},
							'BUS4' : {
								id : 358,
								parentId : 350,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '担保业务',
								iconCls : 'icon-portal-menu-busapp-dbyw',
								qtip : '',
								name : 'BUS4'
							},
							'BUS5' : {
								id : 359,
								parentId : 350,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '房改资金',
								iconCls : 'icon-portal-menu-busapp-fgzj',
								qtip : '',
								name : 'BUS5'
							},
							'waDwzhgl' : {
								id : 388,
								parentId : 359,
								level : 3,
								applicationkey : 'sfk',
								type : 'sysmodulemenu',
								modulekey : 'waDwzhgl',
								text : '单位账户管理',
								iconCls : '',
								qtip : '',
								name : 'waDwzhgl'
							},
							'waSfkjcgl' : {
								id : 389,
								parentId : 359,
								level : 3,
								applicationkey : 'sfk',
								type : 'sysmodulemenu',
								modulekey : 'waSfkjcgl',
								text : '售房款缴存',
								iconCls : '',
								qtip : '',
								name : 'waSfkjcgl'
							},
							'waSfkzfgl' : {
								id : 390,
								parentId : 359,
								level : 3,
								applicationkey : 'sfk',
								type : 'sysmodulemenu',
								modulekey : 'waSfkzfgl',
								text : '售房款支付',
								iconCls : '',
								qtip : '',
								name : 'waSfkzfgl'
							},
							'waSfktzgl' : {
								id : 391,
								parentId : 359,
								level : 3,
								applicationkey : 'sfk',
								type : 'sysmodulemenu',
								modulekey : 'waSfktzgl',
								text : '售房款调账',
								iconCls : '',
								qtip : '',
								name : 'waSfktzgl'
							},
							'sfkJzgl' : {
								id : 392,
								parentId : 359,
								level : 3,
								applicationkey : 'sfk',
								type : 'sysmodulemenu',
								modulekey : 'sfkJzgl',
								text : '结账管理',
								iconCls : '',
								qtip : '',
								name : 'sfkJzgl'
							},
							'waSfkjdjx' : {
								id : 393,
								parentId : 359,
								level : 3,
								applicationkey : 'sfk',
								type : 'sysmodulemenu',
								modulekey : 'waSfkjdjx',
								text : '季度结息',
								iconCls : '',
								qtip : '',
								name : 'waSfkjdjx'
							},
							'waSfktjcx' : {
								id : 394,
								parentId : 359,
								level : 3,
								applicationkey : 'sfk',
								type : 'sysmodulemenu',
								modulekey : 'waSfktjcx',
								text : '统计查询',
								iconCls : '',
								qtip : '',
								name : 'waSfktjcx'
							},
							'sfkKzzxsz' : {
								id : 395,
								parentId : 359,
								level : 3,
								applicationkey : 'sfk',
								type : 'sysmodulemenu',
								modulekey : 'sfkKzzxsz',
								text : '售房款控制中心',
								iconCls : '',
								qtip : '',
								name : 'sfkKzzxsz'
							},
							'BUS6' : {
								id : 360,
								parentId : 350,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '公共维修资金',
								iconCls : 'icon-portal-menu-busapp-wxzj',
								qtip : '',
								name : 'BUS6'
							},
							'BUS7' : {
								id : 361,
								parentId : 350,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '住房补贴',
								iconCls : 'icon-portal-menu-busapp-zfbt',
								qtip : '',
								name : 'BUS7'
							},
							'bt_dwzhgl' : {
								id : 396,
								parentId : 361,
								level : 3,
								applicationkey : 'zfbt',
								type : 'sysmodulemenu',
								modulekey : 'bt_dwzhgl',
								text : '补贴单位账户管理',
								iconCls : '',
								qtip : '',
								name : 'bt_dwzhgl'
							},
							'bt_grzhgl' : {
								id : 397,
								parentId : 361,
								level : 3,
								applicationkey : 'zfbt',
								type : 'sysmodulemenu',
								modulekey : 'bt_grzhgl',
								text : '补贴个人账户管理',
								iconCls : '',
								qtip : '',
								name : 'bt_grzhgl'
							},
							'bt_grzhzy' : {
								id : 399,
								parentId : 361,
								level : 3,
								applicationkey : 'zfbt',
								type : 'sysmodulemenu',
								modulekey : 'bt_grzhzy',
								text : '补贴个人账户转移',
								iconCls : '',
								qtip : '',
								name : 'bt_grzhzy'
							},
							'bt_hbjyw' : {
								id : 398,
								parentId : 361,
								level : 3,
								applicationkey : 'zfbt',
								type : 'sysmodulemenu',
								modulekey : 'bt_hbjyw',
								text : '补贴汇补缴业务',
								iconCls : '',
								qtip : '',
								name : 'bt_hbjyw'
							},
							'bt_jcbg' : {
								id : 400,
								parentId : 361,
								level : 3,
								applicationkey : 'zfbt',
								type : 'sysmodulemenu',
								modulekey : 'bt_jcbg',
								text : '补贴缴存变更',
								iconCls : '',
								qtip : '',
								name : 'bt_jcbg'
							},
							'bt_lxjs' : {
								id : 401,
								parentId : 361,
								level : 3,
								applicationkey : 'zfbt',
								type : 'sysmodulemenu',
								modulekey : 'bt_lxjs',
								text : '补贴利息结算',
								iconCls : '',
								qtip : '',
								name : 'bt_lxjs'
							},
							'bt_tqyw' : {
								id : 402,
								parentId : 361,
								level : 3,
								applicationkey : 'zfbt',
								type : 'sysmodulemenu',
								modulekey : 'bt_tqyw',
								text : '补贴提取业务',
								iconCls : '',
								qtip : '',
								name : 'bt_tqyw'
							},
							'bt_jz' : {
								id : 403,
								parentId : 361,
								level : 3,
								applicationkey : 'zfbt',
								type : 'sysmodulemenu',
								modulekey : 'bt_jz',
								text : '补贴业务结账管理',
								iconCls : '',
								qtip : '',
								name : 'bt_jz'
							},
							'BUS8' : {
								id : 362,
								parentId : 350,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '保障房',
								iconCls : 'icon-portal-menu-busapp-bzf',
								qtip : '',
								name : 'BUS8'
							},
							'BUS9' : {
								id : 363,
								parentId : 350,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '行政执法',
								iconCls : 'icon-portal-menu-busapp-xzzf',
								qtip : '',
								name : 'BUS9'
							},
							'BUS10' : {
								id : 364,
								parentId : 350,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '电子档案',
								iconCls : 'icon-portal-menu-busapp-dzda',
								qtip : '',
								name : 'BUS10'
							},
							'waArchiveEnregister' : {
								id : 405,
								parentId : 364,
								level : 3,
								applicationkey : 'archive',
								type : 'sysmodulemenu',
								modulekey : 'waArchiveEnregister',
								text : '材料扫描录入',
								iconCls : '',
								qtip : '',
								name : 'waArchiveEnregister'
							},
							'waArchive' : {
								id : 406,
								parentId : 364,
								level : 3,
								applicationkey : 'archive',
								type : 'sysmodulemenu',
								modulekey : 'waArchive',
								text : '档案审核归档',
								iconCls : '',
								qtip : '',
								name : 'waArchive'
							},
							'waArchiveSele' : {
								id : 407,
								parentId : 364,
								level : 3,
								applicationkey : 'archive',
								type : 'sysmodulemenu',
								modulekey : 'waArchiveSele',
								text : '档案查询',
								iconCls : '',
								qtip : '',
								name : 'waArchiveSele'
							},
							'waArchiveChange' : {
								id : 408,
								parentId : 364,
								level : 3,
								applicationkey : 'archive',
								type : 'sysmodulemenu',
								modulekey : 'waArchiveChange',
								text : '信息变更管理',
								iconCls : '',
								qtip : '',
								name : 'waArchiveChange'
							},
							'waArchiveLogout' : {
								id : 409,
								parentId : 364,
								level : 3,
								applicationkey : 'archive',
								type : 'sysmodulemenu',
								modulekey : 'waArchiveLogout',
								text : '鉴定管理',
								iconCls : '',
								qtip : '',
								name : 'waArchiveLogout'
							},
							'waArchiveDestroy' : {
								id : 410,
								parentId : 364,
								level : 3,
								applicationkey : 'archive',
								type : 'sysmodulemenu',
								modulekey : 'waArchiveDestroy',
								text : '销毁管理',
								iconCls : '',
								qtip : '',
								name : 'waArchiveDestroy'
							},
							'waBorrow' : {
								id : 411,
								parentId : 364,
								level : 3,
								applicationkey : 'archive',
								type : 'sysmodulemenu',
								modulekey : 'waBorrow',
								text : '档案借阅',
								iconCls : '',
								qtip : '',
								name : 'waBorrow'
							},
							'waStatistics' : {
								id : 412,
								parentId : 364,
								level : 3,
								applicationkey : 'archive',
								type : 'sysmodulemenu',
								modulekey : 'waStatistics',
								text : '档案统计',
								iconCls : '',
								qtip : '',
								name : 'waStatistics'
							},
							'waVirtualHouse' : {
								id : 413,
								parentId : 364,
								level : 3,
								applicationkey : 'archive',
								type : 'sysmodulemenu',
								modulekey : 'waVirtualHouse',
								text : '虚拟档案馆',
								iconCls : '',
								handler : function() {
									var module = MixkyApp.desktop.openModule(
											'archive', 'waVirtualHouse');
									if (module && module.openView) {
										module
												.openView('waVirtualHouse.qModule.vModule');
									}
								},
								qtip : '',
								name : 'waVirtualHouse'
							},
							'waConfigure' : {
								id : 414,
								parentId : 364,
								level : 3,
								applicationkey : 'archive',
								type : 'sysmodulemenu',
								modulekey : 'waConfigure',
								text : '系统配置',
								iconCls : '',
								qtip : '',
								name : 'waConfigure'
							},
							'BUS11' : {
								id : 365,
								parentId : 350,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '贴息贷款',
								iconCls : 'icon-portal-menu-busapp-gd',
								qtip : '',
								name : 'BUS11'
							},
							'waTdxxlr' : {
								id : 415,
								parentId : 365,
								level : 3,
								applicationkey : 'txdk',
								type : 'sysmodulemenu',
								modulekey : 'waTdxxlr',
								text : '贷款信息录入',
								iconCls : '',
								qtip : '',
								name : 'waTdxxlr'
							},
							'waTdtxjs' : {
								id : 416,
								parentId : 365,
								level : 3,
								applicationkey : 'txdk',
								type : 'sysmodulemenu',
								modulekey : 'waTdtxjs',
								text : '贷款贴息计算',
								iconCls : '',
								qtip : '',
								name : 'waTdtxjs'
							},
							'waTdflcx' : {
								id : 417,
								parentId : 365,
								level : 3,
								applicationkey : 'txdk',
								type : 'sysmodulemenu',
								modulekey : 'waTdflcx',
								text : '业务分类查询',
								iconCls : '',
								qtip : '',
								name : 'waTdflcx'
							},
							'SER' : {
								id : 46,
								parentId : 0,
								level : 1,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '客户服务',
								iconCls : 'icon-portal-menu-service',
								qtip : '',
								name : 'SER'
							},
							'FIN' : {
								id : 351,
								parentId : 0,
								level : 1,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '财务管理',
								iconCls : 'icon-portal-menu-fin',
								qtip : '',
								name : 'FIN'
							},
							'SER1' : {
								id : 68,
								parentId : 46,
								level : 2,
								applicationkey : 'crm',
								type : 'sysmodulegroup',
								text : '客户资源管理',
								iconCls : 'icon-portal-menu-service-crm',
								qtip : '',
								name : 'SER1'
							},
							'FIN1' : {
								id : 421,
								parentId : 351,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '会计核算',
								iconCls : 'icon-portal-menu-fin-cw',
								qtip : '',
								name : 'FIN1'
							},
							'wacwztbg' : {
								id : 436,
								parentId : 421,
								level : 3,
								applicationkey : 'wacw',
								type : 'sysmodulegroup',
								text : '切换账套',
								iconCls : '',
								handler : function() {
									atwasoft.common.lib.getZtdialog('wacw',
											false);
								},
								qtip : '',
								name : 'wacwztbg'
							},
							'wacwpzgl' : {
								id : 437,
								parentId : 421,
								level : 3,
								applicationkey : 'wacw',
								type : 'sysmodulemenu',
								modulekey : 'wacwpzgl',
								text : '凭证管理',
								iconCls : '',
								qtip : '',
								name : 'wacwpzgl'
							},
							'wacwzbgl' : {
								id : 438,
								parentId : 421,
								level : 3,
								applicationkey : 'wacw',
								type : 'sysmodulemenu',
								modulekey : 'wacwzbgl',
								text : '账薄管理',
								iconCls : '',
								qtip : '',
								name : 'wacwzbgl'
							},
							'Crm2' : {
								id : 213,
								parentId : 68,
								level : 3,
								applicationkey : 'crm',
								type : 'sysmodulemenu',
								modulekey : 'waCrmKhbfgz',
								text : '客户拜访跟踪',
								iconCls : '',
								qtip : '',
								name : 'Crm2'
							},
							'wacwpzcx' : {
								id : 439,
								parentId : 421,
								level : 3,
								applicationkey : 'wacw',
								type : 'sysmodulemenu',
								modulekey : 'wacwpzcx',
								text : '凭证查询',
								iconCls : '',
								qtip : '',
								name : 'wacwpzcx'
							},
							'wacwreport' : {
								id : 443,
								parentId : 421,
								level : 3,
								applicationkey : 'wacw',
								type : 'sysmodulemenu',
								modulekey : 'wacwreport',
								text : '报表管理',
								iconCls : '',
								qtip : '',
								name : 'wacwreport'
							},
							'wacwqmcl' : {
								id : 440,
								parentId : 421,
								level : 3,
								applicationkey : 'wacw',
								type : 'sysmodulemenu',
								modulekey : 'wacwqmcl',
								text : '期末处理',
								iconCls : '',
								qtip : '',
								name : 'wacwqmcl'
							},
							'wacwhssz' : {
								id : 441,
								parentId : 421,
								level : 3,
								applicationkey : 'wacw',
								type : 'sysmodulemenu',
								modulekey : 'wacwhssz',
								text : '财务核算设置',
								iconCls : '',
								qtip : '',
								name : 'wacwhssz'
							},
							'SER2' : {
								id : 72,
								parentId : 46,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '网上服务',
								iconCls : 'icon-portal-menu-service-net',
								qtip : '',
								name : 'SER2'
							},
							'FIN2' : {
								id : 422,
								parentId : 351,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '资金管理',
								iconCls : 'icon-portal-menu-fin-zj',
								handler : function() {
									atwasoft.common.lib.getZjztdialog('wazj',
											true, this);
								},
								qtip : '',
								name : 'FIN2'
							},
							'NET1' : {
								id : 253,
								parentId : 72,
								level : 3,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '门户网站',
								iconCls : '',
								qtip : '',
								name : 'NET1'
							},
							'wazjztbg' : {
								id : 445,
								parentId : 422,
								level : 3,
								applicationkey : 'wazj',
								type : 'sysmodulemenu',
								modulekey : 'wazjztbg',
								text : '账套变更',
								iconCls : '',
								handler : function() {
									atwasoft.common.lib.getZjztdialog('wazj',
											true, null);
								},
								qtip : '',
								name : 'wazjztbg'
							},
							'NET2' : {
								id : 254,
								parentId : 72,
								level : 3,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '网上业务大厅',
								iconCls : '',
								qtip : '',
								name : 'NET2'
							},
							'wazjzjdb' : {
								id : 458,
								parentId : 422,
								level : 3,
								applicationkey : 'wazj',
								type : 'sysmodulemenu',
								modulekey : 'wazjzjdb',
								text : '资金调拨',
								iconCls : '',
								qtip : '',
								name : 'wazjzjdb'
							},
							'unit_hbjyw' : {
								id : 308,
								parentId : 254,
								level : 4,
								applicationkey : 'unitapp',
								type : 'sysmodulemenu',
								modulekey : 'unit_hbjyw',
								text : '汇补缴业务',
								iconCls : '',
								qtip : '',
								name : 'unit_hbjyw'
							},
							'unit_dwzhgl' : {
								id : 309,
								parentId : 254,
								level : 4,
								applicationkey : 'unitapp',
								type : 'sysmodulemenu',
								modulekey : 'unit_dwzhgl',
								text : '单位账户管理',
								iconCls : '',
								qtip : '',
								name : 'unit_dwzhgl'
							},
							'unit_grzhgl' : {
								id : 310,
								parentId : 254,
								level : 4,
								applicationkey : 'unitapp',
								type : 'sysmodulemenu',
								modulekey : 'unit_grzhgl',
								text : '个人账户管理',
								iconCls : '',
								qtip : '',
								name : 'unit_grzhgl'
							},
							'unit_tqyw' : {
								id : 312,
								parentId : 254,
								level : 4,
								applicationkey : 'unitapp',
								type : 'sysmodulemenu',
								modulekey : 'unit_tqyw',
								text : '提取业务',
								iconCls : '',
								qtip : '',
								name : 'unit_tqyw'
							},
							'unit_txl' : {
								id : 344,
								parentId : 254,
								level : 4,
								applicationkey : 'unitapp',
								type : 'sysmodulemenu',
								modulekey : 'unit_txl',
								text : '通讯录',
								iconCls : '',
								qtip : '',
								name : 'unit_txl'
							},
							'unit_wzxd' : {
								id : 345,
								parentId : 254,
								level : 4,
								applicationkey : 'unitapp',
								type : 'sysmodulemenu',
								modulekey : 'unit_wzxdj',
								text : '外中心贷款申请',
								iconCls : '',
								qtip : '',
								name : 'unit_wzxd'
							},
							'bmtjcx' : {
								id : 346,
								parentId : 254,
								level : 4,
								applicationkey : 'unitapp',
								type : 'sysmodulemenu',
								modulekey : 'bmtjcx',
								text : '部门统计查询',
								iconCls : '',
								qtip : '',
								name : 'bmtjcx'
							},
							'unit_bbtj' : {
								id : 347,
								parentId : 254,
								level : 4,
								applicationkey : 'unitapp',
								type : 'sysmodulemenu',
								modulekey : 'unit_bbtj',
								text : '报表统计',
								iconCls : '',
								qtip : '',
								name : 'unit_bbtj'
							},
							'unit_grzhzy' : {
								id : 348,
								parentId : 254,
								level : 4,
								applicationkey : 'unitapp',
								type : 'sysmodulemenu',
								modulekey : 'unit_grzhzy',
								text : '内部转移',
								iconCls : '',
								qtip : '',
								name : 'unit_grzhzy'
							},
							'NET3' : {
								id : 255,
								parentId : 72,
								level : 3,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '网上查询',
								iconCls : '',
								qtip : '',
								name : 'NET3'
							},
							'mkFM_CM_RM' : {
								id : 457,
								parentId : 422,
								level : 3,
								applicationkey : 'wazj',
								type : 'sysmodulemenu',
								modulekey : 'mkFM_CM_RM',
								text : '定期管理',
								iconCls : '',
								qtip : '',
								name : 'mkFM_CM_RM'
							},
							'NET4' : {
								id : 256,
								parentId : 72,
								level : 3,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '触摸屏',
								iconCls : '',
								qtip : '',
								name : 'NET4'
							},
							'mkFM_CM_HCM' : {
								id : 459,
								parentId : 422,
								level : 3,
								applicationkey : 'wazj',
								type : 'sysmodulemenu',
								modulekey : 'mkFM_CM_HCM',
								text : '手续费管理',
								iconCls : '',
								qtip : '',
								name : 'mkFM_CM_HCM'
							},
							'wazjzjc' : {
								id : 460,
								parentId : 422,
								level : 3,
								applicationkey : 'wazj',
								type : 'sysmodulemenu',
								modulekey : 'wazjzjc',
								text : '资金池',
								iconCls : '',
								qtip : '',
								name : 'wazjzjc'
							},
							'FM_CM_CAS' : {
								id : 461,
								parentId : 422,
								level : 3,
								applicationkey : 'wazj',
								type : 'sysmodulemenu',
								modulekey : 'FM_CM_CAS',
								text : '资金账户设置',
								iconCls : '',
								qtip : '',
								name : 'FM_CM_CAS'
							},
							'mkFM_CM_CS' : {
								id : 462,
								parentId : 422,
								level : 3,
								applicationkey : 'wazj',
								type : 'sysmodulemenu',
								modulekey : 'mkFM_CM_CS',
								text : '资金系统设置',
								iconCls : '',
								qtip : '',
								name : 'mkFM_CM_CS'
							},
							'wazjzjjh' : {
								id : 463,
								parentId : 422,
								level : 3,
								applicationkey : 'wazj',
								type : 'sysmodulemenu',
								modulekey : 'wazjzjjh',
								text : '计划管理',
								iconCls : '',
								qtip : '',
								name : 'wazjzjjh'
							},
							'SER3' : {
								id : 73,
								parentId : 46,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '短信平台',
								iconCls : 'icon-portal-menu-service-sms',
								qtip : '',
								name : 'SER3'
							},
							'FIN3' : {
								id : 423,
								parentId : 351,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '银行资金结算',
								iconCls : '',
								qtip : '',
								name : 'FIN3'
							},
							'SER4' : {
								id : 74,
								parentId : 46,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '呼叫中心',
								iconCls : 'icon-portal-menu-service-call',
								qtip : '',
								name : 'SER4'
							},
							'waGdgl' : {
								id : 117,
								parentId : 74,
								level : 3,
								applicationkey : 'CCC',
								type : 'sysmodulemenu',
								modulekey : 'waGdgl',
								text : '工单管理',
								iconCls : '',
								qtip : '',
								name : 'waGdgl'
							},
							'waOM' : {
								id : 118,
								parentId : 74,
								level : 3,
								applicationkey : 'CCC',
								type : 'sysmodulemenu',
								modulekey : 'waOM',
								text : '运营管理',
								iconCls : '',
								qtip : '',
								name : 'waOM'
							},
							'waClient' : {
								id : 119,
								parentId : 74,
								level : 3,
								applicationkey : 'CCC',
								type : 'sysmodulemenu',
								modulekey : 'waClient',
								text : '坐席端',
								iconCls : '',
								qtip : '',
								name : 'waClient'
							},
							'waZsk' : {
								id : 120,
								parentId : 74,
								level : 3,
								applicationkey : 'CCC',
								type : 'sysmodulemenu',
								modulekey : 'waZsk',
								text : '知识库管理',
								iconCls : '',
								qtip : '',
								name : 'waZsk'
							},
							'SER5' : {
								id : 75,
								parentId : 46,
								level : 2,
								applicationkey : 'OA',
								type : 'sysmodulemenu',
								modulekey : 'waSysMan',
								text : '服务管理',
								iconCls : 'icon-portal-menu-service-exp',
								qtip : '',
								name : 'SER5'
							},
							'SER6' : {
								id : 251,
								parentId : 46,
								level : 2,
								applicationkey : '',
								type : 'sysmodulegroup',
								text : '征信管理',
								iconCls : '',
								qtip : '',
								name : 'SER6'
							},
							'JDGL' : {
								id : 352,
								parentId : 0,
								level : 1,
								applicationkey : 'jdgl',
								type : 'sysmodulegroup',
								text : '监督管理',
								iconCls : 'icon-portal-menu-monman',
								qtip : '',
								name : 'JDGL'
							},
							'jdgl1' : {
								id : 468,
								parentId : 352,
								level : 2,
								applicationkey : 'jhjg',
								type : 'sysmodulemenu',
								modulekey : 'jg_jgcl',
								text : '监管策略',
								iconCls : '',
								qtip : '',
								name : 'jdgl1'
							},
							'jdgl2' : {
								id : 469,
								parentId : 352,
								level : 2,
								applicationkey : 'jhjg',
								type : 'sysmodulemenu',
								modulekey : 'waZzjg',
								text : '组织结构',
								iconCls : '',
								qtip : '',
								name : 'jdgl2'
							},
							'jdgl3' : {
								id : 470,
								parentId : 352,
								level : 2,
								applicationkey : 'jhjg',
								type : 'sysmodulemenu',
								modulekey : 'jg_zhba',
								text : '账户备案',
								iconCls : '',
								qtip : '',
								name : 'jdgl3'
							},
							'jdgl4' : {
								id : 471,
								parentId : 352,
								level : 2,
								applicationkey : 'jhjg',
								type : 'sysmodulemenu',
								modulekey : 'jg_zjlxjk',
								text : '资金流向监控与分析',
								iconCls : '',
								qtip : '',
								name : 'jdgl4'
							},
							'jdgl5' : {
								id : 472,
								parentId : 352,
								level : 2,
								applicationkey : 'jhjg',
								type : 'sysmodulemenu',
								modulekey : 'jg_ywtjfx',
								text : '业务统计分析',
								iconCls : '',
								qtip : '',
								name : 'jdgl5'
							},
							'jdgl6' : {
								id : 473,
								parentId : 352,
								level : 2,
								applicationkey : 'jhjg',
								type : 'sysmodulemenu',
								modulekey : 'ai_sj',
								text : '模型监管',
								iconCls : '',
								qtip : '',
								name : 'jdgl6'
							},
							'jdgl7' : {
								id : 474,
								parentId : 352,
								level : 2,
								applicationkey : 'jhjg',
								type : 'sysmodulemenu',
								modulekey : 'jg_sjwtjz',
								text : '审计问题纠正',
								iconCls : '',
								qtip : '',
								name : 'jdgl7'
							},
							'jdgl18' : {
								id : 475,
								parentId : 352,
								level : 2,
								applicationkey : 'jhjg',
								type : 'sysmodulemenu',
								modulekey : 'jg_jxkhgl',
								text : '绩效考核',
								iconCls : '',
								qtip : '',
								name : 'jdgl18'
							},
							'jdgl9' : {
								id : 476,
								parentId : 352,
								level : 2,
								applicationkey : 'jhjg',
								type : 'sysmodulemenu',
								modulekey : 'ai_bbhz',
								text : '报表汇总',
								iconCls : '',
								qtip : '',
								name : 'jdgl9'
							},
							'jdgl10' : {
								id : 477,
								parentId : 352,
								level : 2,
								applicationkey : 'jhjg',
								type : 'sysmodulemenu',
								modulekey : 'jg_gjjywcx',
								text : '公积金业务查询',
								iconCls : '',
								qtip : '',
								name : 'jdgl10'
							},
							'MAP' : {
								id : 353,
								parentId : 0,
								level : 1,
								applicationkey : 'wazj',
								type : 'sysmodulemenu',
								modulekey : 'wazjztbg',
								text : '北铁地图',
								iconCls : 'icon-portal-menu-fin',
								handler : function() {
									atwasoft.common.lib.getZjMapdialog('wazj',
											1);
								},
								qtip : '',
								name : 'MAP'
							}
						}
					}
				});