Ext.namespace("Mixky.editor");
Mixky.editor.CheckboxGroup=Ext.extend(Ext.form.CheckboxGroup,{applicationkey:void 0,defaultItems:[{boxLabel:"no options",disabled:!0}],url:void 0,store:void 0,initComponent:function(){if(Ext.isDefined(this.url)&&this.url!=""){if(!Ext.isDefined(this.item))this.items=[];items=this.items;Ext.lib.Ajax.request("POST",Mixky.wasoft.cache.Applications[this.applicationkey].url+"/page.do?url="+this.url,{success:function(a){for(var b=Ext.decode(a.responseText),c=0;c<b.length;c++)a=b[c],items.push({boxLabel:a.display,
name:this.name+"_",inputValue:a.value})},scope:this},null,{async:!1})}Mixky.editor.CheckboxGroup.superclass.initComponent.call(this)},onRender:function(a,b){if(!Ext.isDefined(this.items))this.items=[];if(this.items.length==0&&Ext.isDefined(this.store))for(var c=0;c<this.store.getCount();c++){var d=this.store.getAt(c);this.items.push({boxLabel:d.get("display"),name:this.name+"_",inputValue:d.get("value")})}if(this.items.length==0)this.items=this.defaultItems;Mixky.editor.CheckboxGroup.superclass.onRender.call(this,
a,b)},getValue:function(){var a=[];this.eachItem(function(b){b.checked&&a.push(b)});for(var b="",c=0;c<a.length;c++)b=c>0?b+","+a[c].inputValue:a[c].inputValue;return b},setValueForItem:function(a){for(var a=String(a).split(","),b=0;b<a.length;b++)this.eachItem(function(c){if(a[b]==c.inputValue)return c.setValue(!0),!1})},focus:function(){this.getValue()==""?this.items.get(0).focus():this.eachItem(function(a){a.getValue()&&a.focus()})}});Ext.reg("mixkycheckboxgroup",Mixky.editor.CheckboxGroup);Ext.namespace("Mixky.editor");Ext.isDefined=function(a){return typeof a!=="undefined"};
Mixky.editor.PanelTriggerField=Ext.extend(Ext.form.TriggerField,{applicationkey:void 0,defaultAutoCreate:{tag:"input",type:"text",size:"24",autocomplete:"off"},listClass:"",listEmptyText:"",triggerClass:"x-form-arrow-trigger",shadow:"sides",listAlign:"tl-bl?",maxHeight:400,minHeight:120,resizable:!1,handleHeight:8,minListWidth:120,lazyInit:!0,confirm:!0,initComponent:function(){Mixky.editor.PanelTriggerField.superclass.initComponent.call(this);this.addEvents("expand","collapse","beforeselect","select");
if(this.transform){var a=Ext.getDom(this.transform);if(!this.hiddenName)this.hiddenName=a.name;a.name=Ext.id();if(!this.lazyRender)this.target=!0,this.el=Ext.DomHelper.insertBefore(a,this.autoCreate||this.defaultAutoCreate),this.render(this.el.parentNode,a);Ext.removeNode(a)}},onRender:function(a,b){Mixky.editor.PanelTriggerField.superclass.onRender.call(this,a,b);if(this.hiddenName)this.hiddenField=this.el.insertSibling({tag:"input",type:"hidden",name:this.hiddenName,id:this.hiddenId||this.hiddenName},
"before",!0),this.el.dom.removeAttribute("name");Ext.isGecko&&this.el.dom.setAttribute("autocomplete","off");if(this.lazyInit)this.on("focus",this.initList,this,{single:!0});else this.initList()},initList:function(){if(!this.list){this.list=new Ext.Layer({parentEl:this.getListParent(),shadow:this.shadow,cls:["x-panel",this.listClass].join(" "),constrain:!1});var a=this.listWidth||Math.max(this.wrap.getWidth(),this.minListWidth);this.list.setSize(a,0);this.list.swallowEvent("mousewheel");this.assetHeight=
0;this.syncFont!==!1&&this.list.setStyle("font-size",this.el.getStyle("font-size"));if(this.title)this.header=this.list.createChild({cls:"x-panel-hd",html:this.title}),this.assetHeight+=this.header.getHeight();this.innerList=this.list.createChild({cls:"x-panel-inner"});this.innerList.setWidth(a-this.list.getFrameWidth("lr"));this.panel=this.renderPanel(this.innerList);if(this.resizable)this.resizer=new Ext.Resizable(this.list,{pinned:!0,handles:"se"}),this.mon(this.resizer,"resize",function(a,c,d){this.maxHeight=
d-this.handleHeight-this.list.getFrameWidth("tb")-this.assetHeight;this.listWidth=c;this.innerList.setWidth(c-this.list.getFrameWidth("lr"));this.restrictHeight()},this),this.innerList.setStyle("margin-bottom",this.handleHeight+"px")}},getListParent:function(){return document.body},initEvents:function(){Mixky.editor.PanelTriggerField.superclass.initEvents.call(this);this.keyNav=new Ext.KeyNav(this.el,{down:function(){this.onTriggerClick();this.delayedCheck=!0;this.unsetDelayCheck.defer(10,this)},
esc:function(){this.collapse()},scope:this,doRelay:function(a,b,c){return c=="down"||this.scope.isExpanded()?Ext.KeyNav.prototype.doRelay.apply(this,arguments):!0},forceKeyDown:!0})},onDestroy:function(){Ext.destroy(this.resizer,this.panel,this.list);Mixky.editor.PanelTriggerField.superclass.onDestroy.call(this)},unsetDelayCheck:function(){delete this.delayedCheck},fireKey:function(a){var b=function(a){a.isNavKeyPress()&&!this.isExpanded()&&!this.delayedCheck&&this.fireEvent("specialkey",this,a)};
this.inEditor&&Ext.isWebKit&&a.getKey()==a.TAB?b.defer(10,this,[new Ext.EventObjectImpl(a)]):b.call(this,a)},onResize:function(a,b){Mixky.editor.PanelTriggerField.superclass.onResize.apply(this,arguments);if(this.list&&!Ext.isDefined(this.listWidth)){var c=Math.max(a,this.minListWidth);this.list.setWidth(c);this.innerList.setWidth(c-this.list.getFrameWidth("lr"))}},onEnable:function(){Mixky.editor.PanelTriggerField.superclass.onEnable.apply(this,arguments);if(this.hiddenField)this.hiddenField.disabled=
!1},onDisable:function(){Mixky.editor.PanelTriggerField.superclass.onDisable.apply(this,arguments);if(this.hiddenField)this.hiddenField.disabled=!0},getName:function(){var a=this.hiddenField;return a&&a.name?a.name:this.hiddenName||Mixky.editor.PanelTriggerField.superclass.getName.call(this)},initValue:function(){Mixky.editor.PanelTriggerField.superclass.initValue.call(this);if(this.hiddenField)this.hiddenField.value=Ext.isDefined(this.hiddenValue)?this.hiddenValue:Ext.isDefined(this.value)?this.value:
""},getValue:function(){return this.hiddenField?Ext.isDefined(this.value)?this.value:"":Mixky.editor.PanelTriggerField.superclass.getValue.call(this)},setValue:function(a){if(this.hiddenField)this.hiddenField.value=a;return Mixky.editor.PanelTriggerField.superclass.setValue.call(this,a)},restrictHeight:function(){this.innerList.dom.style.height="";var a=this.innerList.dom,b=this.list.getFrameWidth("tb")+(this.resizable?this.handleHeight:0)+this.assetHeight,a=Math.max(a.clientHeight,a.offsetHeight,
a.scrollHeight),c=this.getPosition()[1]-Ext.getBody().getScroll().top,d=Ext.lib.Dom.getViewHeight()-c-this.getSize().height,a=Math.min(a,Math.max(c,d,this.minHeight||0)-this.list.shadowOffset-b-5,this.maxHeight);this.innerList.setHeight(a);this.list.beginUpdate();this.list.setHeight(a+b);this.list.alignTo(this.wrap,this.listAlign);this.list.endUpdate()},onEmptyResults:function(){this.collapse()},isExpanded:function(){return this.list&&this.list.isVisible()},validateBlur:function(){return!this.list||
!this.list.isVisible()},collapse:function(){this.isExpanded()&&(this.list.hide(),Ext.getDoc().un("mousewheel",this.collapseIf,this),Ext.getDoc().un("mousedown",this.collapseIf,this),this.fireEvent("collapse",this))},collapseIf:function(a){!a.within(this.wrap)&&!a.within(this.list)&&this.panelCollapseIf(a)&&this.collapse()},panelCollapseIf:function(a){return this.panel.collapseIf?this.panel.collapseIf(a):!0},expand:function(){!this.isExpanded()&&this.hasFocus&&(this.restrictHeight(),this.list.alignTo(this.wrap,
this.listAlign),Ext.isDefined(this.panel)&&Ext.isDefined(this.panel.beforeexpend)&&this.panel.beforeexpend(this),this.list.show(),Ext.isGecko2&&this.innerList.setOverflow("auto"),Ext.getDoc().on({scope:this,mousewheel:this.collapseIf,mousedown:this.collapseIf}),this.panel.doLayout(),this.fireEvent("expand",this))},onTriggerClick:function(){this.disabled||(this.isExpanded()?this.collapse():(this.onFocus({}),this.expand()),this.el.focus())},onSelect:function(a,b,c){if(this.fireEvent("beforeselect",
this,a,b,c)!==!1){this.setValue(a);this.realValue=b;if(this.hiddenField)this.hiddenField.value=b==void 0?a:b;if(Ext.isDefined(c))this.recordsValue=c;this.collapse();this.fireEvent("select",this,a,b,c)}},renderPanel:function(a){var b=[],c=new Ext.form.ComboBox({name:"testcombo",width:150,triggerAction:"all",mode:"local",editable:!1,store:["test1","test2"]});this.confirm&&(b=["\u6d4b\u8bd5\u9009\u4e2d\u4e8b\u4ef6\uff1a",c,"->",{text:"\u786e\u5b9a",iconCls:"icon-designtool-confirm",handler:function(){this.onSelect("\u9009\u4e2d",
"selected")},scope:this},"-",{text:"\u53d6\u6d88",iconCls:"icon-designtool-cancel",handler:function(){this.collapse()},scope:this}]);return new Ext.Panel({renderTo:a,layout:"fit",items:[new Ext.Panel({autoScroll:!0,bbar:b,html:"Mixky.editor.PanelTriggerField\uff1a\u4e0b\u62c9\u8f93\u5165\u57df<br><br>\u91cd\u8f7drenderPanel(el)\u65b9\u6cd5\u81ea\u5b9a\u4e49\u8f93\u5165\u754c\u9762\u3002<br><br>\u8303\u4f8b\uff1a<br><br>renderPanel : function(el){<br>\u3000\u3000var panel = new Ext.Panel({<br>\u3000\u3000\u3000\u3000applyTo: el,<br>\u3000\u3000\u3000\u3000html:'\u6d4b\u8bd5\u5f55\u5165\u7f16\u8f91\u7a97\u53e3'<br>\u3000\u3000});<br>\u3000\u3000return panel;<br>)"})],
beforeexpend:function(){c.setValue("test2")},collapseIf:function(a){return c.wrap&&a.within(c.wrap)?!1:c.list&&a.within(c.list)?!1:!0}})}});Ext.reg("mixkypaneltriggerfield",Mixky.editor.PanelTriggerField);Ext.namespace("Mixky.editor");
Mixky.editor.ComboViewField=Ext.extend(Mixky.editor.PanelTriggerField,{editable:!1,minListWidth:400,maxHeight:500,minHeight:200,resizable:!1,viewkey:"",groupkey:"",renderPanel:function(a){var b={success:function(a){eval(a.responseText)},scope:this},c=Mixky.wasoft.cache.Applications[this.applicationkey],d=eval(c.keyPrefix+"AppDirect.getModuleOutline");Ext.lib.Ajax.request("POST",c.url+"/jsppage.do?url=engine/views/combo.view&appkey ="+this.applicationkey+"&viewkey="+this.viewkey,b,null,{async:!1});
var e=new Ext.tree.TreePanel({region:"west",width:150,minSize:100,maxSize:300,split:!0,collapsible:!0,collapseMode:"mini",rootVisible:!1,autoScroll:!0,animCollapse:!1,iconCls:"icon-sys-modulemenu",title:"\u68c0\u7d22\u5bfc\u822a",tools:[{id:"refresh",handler:function(){e.refresh()}}],listeners:{afterrender:function(a){a.getRootNode().expand()}},root:{id:"root",text:"root",type:"groupitem",params:{groupkey:this.groupkey}},loader:new Ext.tree.TreeLoader({directFn:d,paramOrder:["params"],baseParams:{params:{}},
listeners:{beforeload:function(a,b){a.baseParams.params=e.getNodeParams(b);a.baseParams.params.type=b.attributes.type}}}),selModel:new Ext.tree.DefaultSelectionModel({listeners:{selectionchange:function(a,b){e.openNode(b)}}}),getNodeParams:function(a){var b={};a.parentNode&&Ext.apply(b,this.getNodeParams(a.parentNode));Ext.apply(b,a.attributes.params);return b},refresh:function(a){a||(a=this.getSelectionModel().getSelectedNode());a&&!a.isLeaf()&&a.reload()},openNode:function(a){a||(a=this.getSelectionModel().getSelectedNode());
a&&(a.attributes.isFunctionMenu||(void 0).refresh(this.getNodeParams(a)))}});this.onSelectRecord=function(){var a=(void 0).getKey(),b=(void 0).getDisplay(),c=(void 0).getRecord();this.onSelect(b,a,c);this.collapse()};return new Ext.Panel({renderTo:a,layout:"border",border:!1,bbar:["->",{text:"\u786e\u5b9a",iconCls:"icon-common-confirm",handler:function(){this.onSelectRecord()},scope:this},"-",{text:"\u53d6\u6d88",iconCls:"icon-common-cancel",handler:function(){this.collapse()},scope:this}],height:300,
items:[e,void 0]})},setValue:function(a,b){Mixky.editor.ComboViewField.superclass.setValue.call(this,a);!Ext.isDefined(this.valueFieldName)&&b!==!0&&Ext.isDefined(a)&&a!=""&&a!=0&&this.renderValue(a);return this},renderValue:function(a){Mixky.wasoft.lib.getDictionaryDourlRender(this.applicationkey,"engine/views/combo.view.renderer",a,this.setRawValue.createDelegate(this),{appkey:this.applicationkey,viewkey:this.viewkey})}});Ext.reg("mixkycomboviewfield",Mixky.editor.ComboViewField);Ext.namespace("Mixky.editor");
Mixky.editor.DeptTreeField=Ext.extend(Mixky.editor.PanelTriggerField,{confirm:!0,minListWidth:300,maxHeight:500,minHeight:200,resizable:!1,editable:!1,selectMulti:!1,selectType:"user",valueField:"key",displayField:"text",valueSeparator:";",valueFieldName:void 0,getRealValue:function(){var a=this.getValue(),b=this.findValueFieldCmp();b&&(a=b.getValue());return a},setRealValue:function(a){this.realValue=a;var b=this.findValueFieldCmp();b&&b.setValue(a);if(this.hiddenField)this.hiddenField.value=a},
findValueFieldCmp:function(){if(Ext.isDefined(this.valueFieldName)){var a=this.findParentByType("form");if(a)return a.getForm().findField(this.valueFieldName)}},onSelect:function(a,b,c){this.fireEvent("beforeselect",this,a,b,c)!==!1&&(this.setValue(a),this.setRealValue(b),this.collapse(),this.fireEvent("select",this,a,b,c))},renderPanel:function(a){function b(a,e){e||(e=d.getRootNode());if(e.attributes[c.valueField]==a&&Ext.isDefined(e.attributes.checked))e.attributes.checked=!0,e.getUI().toggleCheck(!0);
e.eachChild(function(c){b(a,c)})}var c=this,d=new Ext.tree.TreePanel({region:"center",autoScroll:!0,rootVisible:!1,style:"background-color:white",root:{nodeType:"async",text:"\u4eba\u5458\u9009\u62e9"},loader:new Ext.tree.TreeLoader({directFn:OrganizationDirect.getDeptTree,paramOrder:["type"],baseParams:{type:this.selectType},preloadChildren:!0}),tools:[{id:"refresh",handler:function(){d.refresh()}}],refresh:function(){this.getRootNode().reload()}});d.getLoader().on("load",function(a,b){b.expand(!0);
if(Ext.isDefined(c.valueFieldName)){var e=c.findParentByType("form").getForm().findField(c.valueFieldName);Ext.isDefined(e.value)&&d.setValue(e.value)}else Ext.isDefined(c.value)&&d.setValue(c.value)});d.on("checkchange",function(a,b){if(b&&!c.selectMulti)for(var e=d.getChecked("id"),h=0;h<e.length;h++)e[h]!=a.id&&d.getNodeById(e[h]).getUI().toggleCheck(!1)});d.setValue=function(a){if(c.selectMulti)for(var a=a.split(c.valueSeparator),d=0;d<a.length;d++)b(a[d]);else b(a)};var e=[];this.confirm&&(e=
[{text:"\u5237\u65b0",iconCls:"icon-common-refresh",handler:function(){d.refresh()}},"->",{text:"\u786e\u5b9a",iconCls:"icon-common-confirm",handler:function(){var a=d.getChecked(c.valueField),b=d.getChecked(c.displayField),e="",h="";if(Ext.isDefined(a))for(var g=0;g<a.length;g++)g==0?(e=a[g],h=b[g]):(e=e+this.valueSeparator+a[g],h=h+";"+b[g]);this.onSelect(h,e);this.collapse()},scope:this},"-",{text:"\u53d6\u6d88",iconCls:"icon-common-cancel",handler:function(){this.collapse()},scope:this}]);return new Ext.Panel({renderTo:a,
layout:"fit",items:[new Ext.Panel({layout:"fit",height:300,items:[d],bbar:e})],beforeexpend:function(){d.setValue(c.getRealValue())}})}});Ext.reg("mixkydepttreefield",Mixky.editor.DeptTreeField);Ext.namespace("Mixky.editor");
Mixky.editor.DisplayField=Ext.extend(Ext.form.TextField,{applicationkey:void 0,defaultAutoCreate:{tag:"input",type:"hidden",name:this.name},htmlEncode:!1,dictionaryname:void 0,remoterender:void 0,params:void 0,dourl:void 0,url:void 0,hideDisplayBorder:void 0,onRender:function(a,b){Mixky.editor.DisplayField.superclass.onRender.call(this,a,b);this.wrap=this.el.wrap();if(this.hideDisplayBorder){var c=Ext.isDefined(this.style)?"color:gray;padding:3px;"+this.style:"color:gray;padding:3px;";this.displayEl=
this.wrap.createChild({tag:"div",style:c})}else c=Ext.isDefined(this.style)?"color:gray;border:1px solid #C0C0C0;padding:3px;"+this.style:"color:gray;border:1px solid #C0C0C0;padding:3px;",this.displayEl=this.wrap.createChild({tag:"div",style:c,name:this.name});this.displayEl.dom.innerHTML="&nbsp;"},setValue:function(a){Mixky.editor.DisplayField.superclass.setValue.call(this,a);this.remoterender?this.renderValue(a):this.setRawValue(a);return this},setRawValue:function(a){var b=a;this.htmlEncode&&
(b=Ext.util.Format.htmlEncode(a));b&&typeof b=="string"&&(b=b.replaceAll("\n","<BR>").replaceAll("\t","&emsp;").replaceAll(" ","&nbsp;"));this.displayEl.dom.innerHTML=Ext.isEmpty(b)?"&nbsp;":b},renderValue:function(a){var b=a;Ext.isDefined(this.dictionaryname)?b=Mixky.wasoft.lib.dictionaryRenderer(this.applicationkey,a,this.dictionaryname):Ext.isDefined(this.dourl)?Mixky.wasoft.lib.getDictionaryDourlRender(this.applicationkey,this.dourl,a,this.setRawValue.createDelegate(this),this.params):Ext.isDefined(this.url)?
Mixky.wasoft.lib.getDictionaryUrlRender(this.applicationkey,this.url,a,this.setRawValue.createDelegate(this)):Ext.isDefined(this.directFn)&&Mixky.wasoft.lib.getDictionaryDirectRender(this.applicationkey,this.directFn,this.setRawValue.createDelegate(this),this.params,a,this.document);this.setRawValue(b)}});Ext.reg("mixkydisplayfield",Mixky.editor.DisplayField);Ext.namespace("Mixky.editor");
Mixky.editor.OrganizationField=Ext.extend(Mixky.editor.PanelTriggerField,{confirm:!0,editable:!1,minListWidth:450,maxHeight:600,minHeight:400,resizable:!1,selectMulti:!0,selectType:"mix",valueField:"expression",displayField:"f_caption",valueSeparator:"",renderPanel:function(a){var b=this,c=new Ext.tree.TreePanel({region:"center",autoScroll:!0,rootVisible:!1,root:{nodeType:"async",text:"\u4eba\u5458\u9009\u62e9",id:"root-organization"},loader:new Ext.tree.TreeLoader({directFn:OrganizationDirect.getOrganizationTree,paramOrder:["type"],
baseParams:{type:"mix"},preloadChildren:!0}),tools:[{id:"refresh",handler:function(){c.refresh()}}],refresh:function(){this.getRootNode().reload()}}),d=new Ext.grid.GridPanel({region:"east",width:300,minSize:200,maxSize:400,split:!0,autoExpandColumn:"f_note",enableHdMenu:!1,enableColumnMove:!1,store:new Ext.data.DirectStore({directFn:OrganizationDirect.getUserList,paramOrder:["expression"],baseParams:{key:"expression"},root:"results",totalProperty:"totals",idProperty:"id",fields:[{name:"id",mapping:"id"},
{name:"f_name",mapping:"f_name"},{name:"f_caption",mapping:"f_caption"},{name:"f_note",mapping:"f_note"},{name:"expression",mapping:"expression"}]}),columns:[new Ext.grid.RowNumberer,{id:"f_caption",dataIndex:"f_caption",width:80,header:"\u7528\u6237\u540d"},{id:"f_name",dataIndex:"f_name",width:100,header:"\u767b\u5f55\u540d"},{id:"f_note",dataIndex:"f_note",header:"\u5907\u6ce8"}],loadExpression:function(a){this.getStore().baseParams.expression=a;this.getStore().reload()}}),e=new Ext.DataView({region:"south",
autoScroll:!0,split:!0,height:60,minSize:50,maxSize:250,style:"background-color:white",tpl:new Ext.XTemplate('<tpl for=".">','<div class="user-expression-item icon-administrator-{type}" id="{expression}">{f_caption}</div>',"</tpl>",'<div class="x-clear"></div>'),selectedClass:"x-user-expression-view-selected",overClass:"x-user-expression-view-over",itemSelector:"div.user-expression-item",multiSelect:!0,plugins:[new Ext.DataView.DragSelector],store:new Ext.data.JsonStore({idProperty:"expression",fields:["expression",
"type","id","f_name","f_caption","f_note"]}),selectExpression:function(a){(b.selectMulti||!(this.getStore().getCount()>0))&&OrganizationDirect.getExpressionData(a,b.selectType,function(a){for(var b=0;b<a.results.length;b++){var c=a.results[b];e.getStore().getById(c.expression)||e.getStore().loadData([a.results[b]],!0)}})},loadSelectedUsers:function(a){this.clearSelected();if(Ext.isDefined(a)&&a!=""){var c="";typeof a=="string"&&(a=a.split(b.valueSeparator));for(var d=0;d<a.length;d++)d>0&&(c+=";"),
c+=a[d];OrganizationDirect.loadSelectedUsers(b.valueField,c,function(a){e.getStore().loadData(a.results,!0)})}},clearSelected:function(){e.getStore().removeAll()},removeSelected:function(){for(var a=e.getSelectedRecords(),b=0;b<a.length;b++)e.getStore().remove(a[b])}});e.contextMenu=new Ext.menu.Menu({items:[{text:"\u5220\u9664",iconCls:"icon-common-delete",handler:function(){e.removeSelected()}}]});c.getSelectionModel().on("selectionchange",function(a,b){if(b){var c=b.attributes.expression;c&&c!=
""&&d.loadExpression(c)}});c.on("dblclick",function(a){(a=a.attributes.expression)&&a!=""&&(this.selectMulti||this.selectType!="user")&&e.selectExpression(a)});d.on("rowdblclick",function(a){a=a.getSelectionModel().getSelected();e.selectExpression(a.get("expression"))});e.on("dblclick",function(){e.removeSelected()});e.on("contextmenu",function(a,b,c,d){a.contextMenu.showAt(d.getXY())});var i=new Ext.Panel({renderTo:a,layout:"border",border:!1,defaults:{border:!1},items:[c,d,e]}),f=[];this.confirm&&
(f=[{text:"\u5237\u65b0",iconCls:"icon-common-refresh",handler:function(){c.refresh()}},"->",{text:"\u786e\u5b9a",iconCls:"icon-common-confirm",handler:function(){var a=e.getStore().getRange(),b="",c="";this.selectMulti&&this.valueSeparator==""&&(b=[]);for(var c="",d=0;d<a.length;d++)d>0&&(c+=";",this.selectMulti&&this.valueSeparator!=""&&(b+=this.valueSeparator)),c+=a[d].get(this.displayField),this.selectMulti&&this.valueSeparator==""?b.push(a[d].get(this.valueField)):b+=a[d].get(this.valueField);
this.onSelect(c,b,a);this.collapse()},scope:this},"-",{text:"\u53d6\u6d88",iconCls:"icon-common-cancel",handler:function(){this.collapse()},scope:this}]);return new Ext.Panel({renderTo:a,layout:"fit",items:[new Ext.Panel({layout:"fit",height:300,items:[i],bbar:f})],beforeexpend:function(){if(b.selectType!=c.getLoader().baseParams.type)c.getLoader().baseParams.type=b.selectType,c.refresh();switch(b.selectType){case "user":case "mix":d.setVisible(!0);break;case "deptment":case "role":d.setVisible(!1)}e.loadSelectedUsers(b.realValue)}})}});
Ext.reg("mixkyorganizationfield",Mixky.editor.OrganizationField);Ext.namespace("Mixky.editor");
Mixky.editor.TextboxField=Ext.extend(Mixky.editor.PanelTriggerField,{confirm:!0,editable:!0,minListWidth:300,minHeight:200,getValue:function(){var a=this.value;if(a===this.emptyText||a===void 0)a="";return a},renderPanel:function(a){var b=new Ext.form.TextArea({hideLabel:!0,anchor:"100%",height:200}),c=[];this.confirm&&(c=["->",{text:"\u786e\u5b9a",iconCls:"icon-common-confirm",handler:function(){var a=b.getValue();this.onSelect(a,a);this.collapse()},scope:this},"-",{text:"\u53d6\u6d88",iconCls:"icon-common-cancel",
handler:function(){this.collapse()},scope:this}]);return new Ext.Panel({renderTo:a,layout:"fit",beforeexpend:function(a){b.setValue(a.value);b.value=a.value},items:[new Ext.Panel({layout:"fit",height:150,items:[b],bbar:c})]})}});Ext.reg("mixkytextboxfield",Mixky.editor.TextboxField);Ext.namespace("Mixky.editor");
Mixky.editor.EmailAddress=Ext.extend(Ext.form.TextArea,{queryDelay:500,queryParam:"query",minChars:1,minListWidth:200,lazyInit:!0,listClass:"",displayField:"display",selectedClass:"x-combo-selected",shadow:"sides",listAlign:"tl-bl?",maxHeight:300,minHeight:90,itemSeparator:",",url:"emailaddress.jsp",directFn:void 0,initComponent:function(){Mixky.editor.EmailAddress.superclass.initComponent.call(this);this.addEvents("expand","collapse","beforeselect","select","beforequery");var a=new Ext.data.JsonReader({root:"results",
totalProperty:"rows",fields:[this.displayField]});this.store=Ext.isDefined(this.directFn)?new Ext.data.Store({proxy:new Ext.data.DirectProxy({directFn:this.directFn,paramsAsHash:!0,paramOrder:[this.queryParam]}),reader:a}):new Ext.data.Store({proxy:new Ext.data.HttpProxy({url:this.url}),reader:a});if(!Ext.isDefined(this.initialConfig.minChars))this.minChars=0;this.selectedIndex=-1},initEvents:function(){Mixky.editor.EmailAddress.superclass.initEvents.call(this);this.keyNav=new Ext.KeyNav(this.el,
{up:function(){this.inKeyMode=!0;this.selectPrev()},down:function(){this.inKeyMode=!0;this.selectNext()},enter:function(){this.onViewClick();this.delayedCheck=!0;this.unsetDelayCheck.defer(10,this)},esc:function(){this.collapse()},tab:function(){this.onViewClick(!1);return!0},scope:this,doRelay:function(a,b,c){return c=="down"||this.scope.isExpanded()?Ext.KeyNav.prototype.doRelay.apply(this,arguments):!0},forceKeyDown:!0});this.queryDelay=Math.max(this.queryDelay||250);this.dqTask=new Ext.util.DelayedTask(this.initQuery,
this);this.editable!==!1&&!this.enableKeyEvents&&this.mon(this.el,"keyup",this.onKeyUp,this)},onRender:function(a,b){Mixky.editor.EmailAddress.superclass.onRender.call(this,a,b);this.wrap=this.el.wrap({cls:"x-form-field-wrap x-form-field-trigger-wrap"});this.width||this.wrap.setWidth(this.el.getWidth());Ext.isGecko&&this.el.dom.setAttribute("autocomplete","off");if(this.lazyInit)this.on("focus",this.initList,this,{single:!0});else this.initList()},initList:function(){if(!this.list){this.list=new Ext.Layer({parentEl:this.getListParent(),
shadow:this.shadow,cls:["x-combo-list",this.listClass].join(" "),constrain:!1});var a=this.listWidth||Math.max(this.wrap.getWidth(),this.minListWidth);this.list.setSize(a,0);this.list.swallowEvent("mousewheel");this.assetHeight=0;this.syncFont!==!1&&this.list.setStyle("font-size",this.wrap.getStyle("font-size"));if(this.title)this.header=this.list.createChild({cls:"x-combo-list-hd",html:this.title}),this.assetHeight+=this.header.getHeight();this.innerList=this.list.createChild({cls:"x-combo-list-inner"});
this.mon(this.innerList,"mouseover",this.onViewOver,this);this.mon(this.innerList,"mousemove",this.onViewMove,this);this.innerList.setWidth(a-this.list.getFrameWidth("lr"));if(!this.tpl)this.tpl='<tpl for="."><div class="x-combo-list-item">{'+this.displayField+"}</div></tpl>";this.view=new Ext.DataView({applyTo:this.innerList,tpl:this.tpl,singleSelect:!0,selectedClass:this.selectedClass,itemSelector:this.itemSelector||".x-combo-list-item",emptyText:this.listEmptyText});this.mon(this.view,"click",
this.onViewClick,this);this.bindStore(this.store,!0)}},getStore:function(){return this.store},getListParent:function(){return document.body},onKeyUp:function(a){var b=a.getKey();if(this.editable!==!1&&(b==a.BACKSPACE||!a.isSpecialKey()))this.lastKey=b,this.dqTask.delay(this.queryDelay);Mixky.editor.EmailAddress.superclass.onKeyUp.call(this,a)},bindStore:function(a,b){if(this.store&&!b&&(this.store.un("beforeload",this.onBeforeLoad,this),this.store.un("load",this.onLoad,this),this.store.un("exception",
this.collapse,this),this.store!==a&&this.store.autoDestroy&&this.store.destroy(),!a))this.store=null,this.view&&this.view.bindStore(null);if(a)this.store=Ext.StoreMgr.lookup(a),this.store.on({scope:this,beforeload:this.onBeforeLoad,load:this.onLoad,exception:this.collapse}),this.view&&this.view.bindStore(a)},onBeforeLoad:function(){if(this.hasFocus)this.innerList.update(this.loadingText?'<div class="loading-indicator">'+this.loadingText+"</div>":""),this.restrictHeight(),this.selectedIndex=-1},onLoad:function(){if(this.hasFocus)if(this.store.getCount()>
0)this.expand(),this.restrictHeight(),this.select(0,!0);else this.onEmptyResults()},onEmptyResults:function(){this.collapse()},validateBlur:function(){return!this.list||!this.list.isVisible()},initQuery:function(){var a=this.getItemText();a==""||Ext.isEmpty(a)?this.collapse():this.doQuery(this.getItemText())},doQuery:function(a){a=Ext.isEmpty(a)?"":a;a={query:a,field:this,cancel:!1};if(this.fireEvent("beforequery",a)===!1||a.cancel)return!1;a=a.query;this.store.baseParams[this.queryParam]=a;this.store.load();
this.expand()},unsetDelayCheck:function(){delete this.delayedCheck},isExpanded:function(){return this.list&&this.list.isVisible()},select:function(a,b){this.selectedIndex=a;this.view.select(a);if(b!==!1){var c=this.view.getNode(a);c&&this.innerList.scrollChildIntoView(c,!1)}},selectPrev:function(){this.store.getCount()>0&&(this.selectedIndex==-1?this.select(0):this.selectedIndex!==0&&this.select(this.selectedIndex-1))},selectNext:function(){var a=this.store.getCount();a>0&&(this.selectedIndex==-1?
this.select(0):this.selectedIndex<a-1&&this.select(this.selectedIndex+1))},onViewMove:function(){this.inKeyMode=!1},onViewOver:function(a,b){if(!this.inKeyMode){var c=this.view.findItemFromChild(b);c&&this.select(this.view.indexOf(c),!1)}},onViewClick:function(a){var b=this.view.getSelectedIndexes()[0],c=this.store.getAt(b);if(c)this.onSelect(c,b);a!==!1&&this.el.focus()},onSelect:function(a,b){this.fireEvent("beforeselect",this,a,b)!==!1&&(this.replaceItemText(a.data[this.displayField]),this.collapse(),
this.fireEvent("select",this,a,b))},getItemText:function(){var a=this.getRawValue(),b=this.el.dom.selectionStart,c=a.substr(0,b).lastIndexOf(this.itemSeparator)+1,d=a.substr(b).indexOf(this.itemSeparator),d=d<0?a.length:b+d;return a.substr(c,d-c)},replaceItemText:function(a){var b=this.getRawValue(),c=this.el.dom.selectionStart,d=b.substr(0,c).lastIndexOf(this.itemSeparator)+1,e=b.substr(c).indexOf(this.itemSeparator),e=e<0?b.length:e+c+1,b=b.substr(0,d)+a+this.itemSeparator+b.substr(e);this.el.dom.selectionStart=
d+a.length+1;this.setValue(b)},collapse:function(){this.isExpanded()&&(this.list.hide(),Ext.getDoc().un("mousewheel",this.collapseIf,this),Ext.getDoc().un("mousedown",this.collapseIf,this),this.fireEvent("collapse",this))},collapseIf:function(a){a.within(this.list)||this.collapse()},expand:function(){!this.isExpanded()&&this.hasFocus&&(this.list.alignTo(this.wrap,this.listAlign),this.list.show(),Ext.isGecko2&&this.innerList.setOverflow("auto"),Ext.getDoc().on({scope:this,mousewheel:this.collapseIf,
mousedown:this.collapseIf}),this.fireEvent("expand",this))},restrictHeight:function(){this.innerList.dom.style.height="";var a=this.innerList.dom,b=this.list.getFrameWidth("tb")+this.assetHeight,a=Math.max(a.clientHeight,a.offsetHeight,a.scrollHeight),c=this.getPosition()[1]-Ext.getBody().getScroll().top,d=Ext.lib.Dom.getViewHeight()-c-this.getSize().height,a=Math.min(a,Math.max(c,d,this.minHeight||0)-this.list.shadowOffset-b-5,this.maxHeight);this.innerList.setHeight(a);this.list.beginUpdate();this.list.setHeight(a+
b);this.list.alignTo(this.wrap,this.listAlign);this.list.endUpdate()},onResize:function(a,b){Mixky.editor.EmailAddress.superclass.onResize.apply(this,arguments);if(this.list&&!Ext.isDefined(this.listWidth)){var c=Math.max(a,this.minListWidth);this.list.setWidth(c);this.innerList.setWidth(c-this.list.getFrameWidth("lr"))}}});Ext.reg("mixkyemailaddress",Mixky.editor.EmailAddress);Ext.namespace("Mixky.editor");
Mixky.editor.OpinionField=Ext.extend(Ext.form.TextField,{applicationkey:void 0,hideDisplayBorder:void 0,defaultAutoCreate:{tag:"input",type:"hidden",name:this.name},onRender:function(a,b){Mixky.editor.OpinionField.superclass.onRender.call(this,a,b);this.wrap=this.el.wrap();this.opinionEl=this.wrap.createChild({tag:"div"});this.hideDisplayBorder||this.wrap.setStyle("border","1px solid #cccccc");this.opinionEl.setStyle("padding","3px");if(!this.readOnly){var c=this.wrap.createChild({tag:"div",align:"right"}).createChild({tag:"div"});
(new Ext.SplitButton({iconCls:"icon-sys-btnedit",text:"\u586b\u5199\u610f\u89c1",handler:this.openOpinionWindow,menu:new Ext.menu.Menu({items:[{text:"\u540c\u610f",handler:function(){this.setDirectOpinion("\u540c\u610f")},scope:this},{text:"\u5df2\u9605",handler:function(){this.setDirectOpinion("\u5df2\u9605")},scope:this},{text:"\u4e0d\u540c\u610f",handler:function(){this.setDirectOpinion("\u4e0d\u540c\u610f")},scope:this}]}),scope:this})).render(c)}this.loadValue()},loadValue:function(){eval(Mixky.wasoft.cache.Applications[this.applicationkey].keyPrefix+
"AppDirect.getFieldDisplayOpinion")(this.document.document.documentkey,this.document.document.documentid,this.name,function(a,b){a&&a.success?this.setOpinion(a.opinion):MixkyApp.showDirectActionFail("\u83b7\u53d6\u610f\u89c1",a,b)},this)},openOpinionWindow:function(){Mixky.wasoft.workflow.OpinionWindow(this.applicationkey,this.document.document.documentkey,this.document.document.documentid,{objectkey:this.name,objectid:this.id})},setDirectOpinion:function(a){eval(Mixky.wasoft.cache.Applications[this.applicationkey].keyPrefix+
"AppDirect.setFieldOpinion")(this.document.document.documentkey,this.document.document.documentid,a,this.name,function(a){a&&a.success&&this.loadValue()},this)},initValue:function(){this.value!==""?this.setOpinion(this.value):this.setOpinion("&nbsp;")},setOpinion:function(a){if(a!="&nbsp;")this.value=a;if(this.opinionEl)this.opinionEl.dom.innerHTML=a===""||a===null||a===void 0?"&nbsp;":a},getValue:function(){if(!this.rendered)return this.value;var a=this.opinionEl.dom.innerHTML;if(a===this.emptyText||
a===void 0)a="";return a},validate:function(){return!0}});Ext.reg("mixkyopinionfield",Mixky.editor.OpinionField);Ext.namespace("Mixky.editor");
Mixky.editor.OrganizationWindowField=Ext.extend(Ext.form.TriggerField,{applicationkey:void 0,defaultAutoCreate:{tag:"textarea",name:this.name},htmlEncode:!1,editable:!1,selectOnFocus:!1,blankText:"\u5168\u90e8",selectMulti:!0,selectType:"mix",valueField:"expression",displayField:"f_caption",valueSeparator:";",valueFieldName:void 0,onTriggerClick:function(){var a={selectMulti:this.selectMulti,selectType:this.selectType,valueField:this.valueField,displayField:this.displayField,valueSeparator:this.valueSeparator};
value="";var b=this,c=this.findValueFieldCmp();c&&(value=c.getValue());Mixky.wasoft.lib.getOrganizationWindow(a,value,function(a,e){b.setValue(a);c&&c.setValue(e)}).show()},findValueFieldCmp:function(){if(Ext.isDefined(this.valueFieldName)){var a=this.findParentByType("form");if(a)return a.getForm().findField(this.valueFieldName)}}});Ext.reg("mixkyorganizationwindowfield",Mixky.editor.OrganizationWindowField);Ext.namespace("Mixky.editor");
Mixky.editor.RadioGroup=Ext.extend(Ext.form.RadioGroup,{applicationkey:void 0,defaultItems:[{boxLabel:"no options",disabled:!0}],url:void 0,store:void 0,initComponent:function(){if(Ext.isDefined(this.url)&&this.url!=""){if(!Ext.isDefined(this.item))this.items=[];items=this.items;Ext.lib.Ajax.request("POST",Mixky.wasoft.cache.Applications[this.applicationkey].url+"/page.do?url="+this.url,{success:function(a){for(var b=Ext.decode(a.responseText),c=0;c<b.length;c++)a=b[c],items.push({boxLabel:a.display,
name:this.name+"_",inputValue:a.value})},scope:this},null,{async:!1})}Mixky.editor.RadioGroup.superclass.initComponent.call(this)},onRender:function(a,b){if(!Ext.isDefined(this.items))this.items=[];if(this.items.length==0&&Ext.isDefined(this.store))for(var c=0;c<this.store.getCount();c++){var d=this.store.getAt(c);this.items.push({boxLabel:d.get("display"),name:this.name+"_",inputValue:d.get("value")})}if(this.items.length==0)this.items=this.defaultItems;Mixky.editor.RadioGroup.superclass.onRender.call(this,
a,b)},getValue:function(){var a=Mixky.editor.RadioGroup.superclass.getValue.call(this),b="";if(a)b=a.inputValue;return b},setValueForItem:function(a){this.eachItem(function(b){if(a==b.inputValue)return b.setValue(!0),!1})},focus:function(){this.getValue()==""?this.items.get(0).focus():this.eachItem(function(a){a.getValue()&&a.focus()})}});Ext.reg("mixkyradiogroup",Mixky.editor.RadioGroup);Ext.namespace("Mixky.editor");
Mixky.editor.TextboxField=Ext.extend(Mixky.editor.PanelTriggerField,{confirm:!0,editable:!1,minListWidth:300,minHeight:200,getValue:function(){var a=this.value;if(a===this.emptyText||a===void 0)a="";return a},renderPanel:function(a){var b=new Ext.form.TextArea({hideLabel:!0,anchor:"100%",height:200}),c=[];this.confirm&&(c=["->",{text:"\u786e\u5b9a",iconCls:"icon-common-confirm",handler:function(){var a=b.getValue();this.onSelect(a,a);this.collapse()},scope:this},"-",{text:"\u53d6\u6d88",iconCls:"icon-common-cancel",
handler:function(){this.collapse()},scope:this}]);return new Ext.Panel({renderTo:a,layout:"fit",beforeexpend:function(a){b.setValue(a.value);b.value=a.value},items:[new Ext.Panel({layout:"fit",height:150,items:[b],bbar:c})]})}});Ext.reg("mixkytextboxfield",Mixky.editor.TextboxField);Ext.namespace("Mixky.editor");
Mixky.editor.FileField=Ext.extend(Ext.form.DisplayField,{readOnly:!1,isMulti:!1,isImage:!1,imageWidth:70,imageHeight:30,downloadUrl:"#",onRender:function(a,b){Mixky.editor.FileField.superclass.onRender.call(this,a,b);this.fileCount=0;this.fileInputs=[];if(!this.readOnly)this.btnInsertFileWrap=this.el.createChild({tag:"div",style:"position: absolute;"}),this.btnInsertFile=new Ext.Button({renderTo:this.btnInsertFileWrap,text:"\u6dfb \u52a0 \u9644 \u4ef6",iconCls:"icon-sys-attachment"}),this.addFileInput()},
bindFileField:function(a){a.on({scope:this,mouseenter:function(){this.btnInsertFile.addClass(["x-btn-over","x-btn-focus"])},mouseleave:function(){this.btnInsertFile.removeClass(["x-btn-over","x-btn-focus","x-btn-click"])},mousedown:function(){this.btnInsertFile.addClass("x-btn-click")},mouseup:function(){this.btnInsertFile.removeClass(["x-btn-over","x-btn-focus","x-btn-click"])},change:function(){this.addFileDisplay(0,this.curFileInput.dom.value,0,this.curFileInput)}})},getFileRowHeight:function(){return this.isImage?
this.imageHeight+2:22},adjustFileInputTop:function(){var a=this.fileCount*this.getFileRowHeight()+2;if(!this.readOnly&&(this.isMulti||this.fileCount==1)){var b=(this.fileCount-1)*this.getFileRowHeight();this.btnInsertFileWrap.setTop(b);this.curFileInput.setTop(b)}!this.readOnly&&!this.isMulti&&(this.fileCount>1?(this.btnInsertFileWrap.hide(),this.curFileInput.setDisplayed("none"),this.curFileInput.hide(),a=this.getFileRowHeight()+2):(this.btnInsertFileWrap.show(),this.curFileInput.setDisplayed(""),
this.curFileInput.show()));this.readOnly&&(this.curFileInput.setDisplayed("none"),this.curFileInput.hide());this.setHeight(a)},addFileInput:function(){this.curFileInput=this.el.createChild({name:this.name+"-0-"+this.fileCount,style:"position: absolute;-moz-opacity: 0;filter:alpha(opacity: 0);opacity: 0;z-index: 2; height: 22px;",tag:"input",type:"file",size:1});var a=this.findParentByType("form");Ext.isDefined(a)&&a.doLayout();this.bindFileField(this.curFileInput);this.fileCount++;this.adjustFileInputTop();
this.fileInputs.push(this.curFileInput)},addFileDisplay:function(a,b,c,d){var c=b+(c>0?" ("+c+"Bytes)":""),e=this.el.createChild({tag:"div",style:"height: "+this.getFileRowHeight()+"px;"});a>0?(b=this.downloadUrl!="#"?this.downloadUrl+"&id="+a+"&fn="+b:"#",this.isImage&&(c="<img align=middle border=0 height="+this.imageHeight+" width="+this.imageWidth+' src="'+b+"\" title='"+c+"'>"),e.createChild({tag:"a",href:b,html:c}),this.readOnly||(e.insertHtml("beforeEnd","\u3000"),b=e.createChild({tag:"a",
href:"#",html:"\u5220\u9664"}),b.on("click",function(){e.remove();this.fileCount--;this.adjustFileInputTop();this.fileInputs.push(this.el.createChild({name:this.name+"-"+a,style:"display:none",tag:"input",type:"file"}))},this)),this.fileCount++,this.fileInputs.push(e),this.adjustFileInputTop()):(e.createChild({tag:"a",href:"#",html:b}),this.readOnly||(e.insertHtml("beforeEnd","\u3000"),b=e.createChild({tag:"a",href:"#",html:"\u5220\u9664"}),b.on("click",function(){d.remove();e.remove();this.fileCount--;
this.adjustFileInputTop()},this)),this.fileInputs.push(e),d.setDisplayed("none"),this.addFileInput(),this.isMulti||this.curFileInput.setDisplayed("none"))},setValue:function(a){for(var b=0;b<this.fileInputs.length;b++)this.fileInputs[b].remove();this.fileInputs=[];this.fileCount=0;this.addFileInput();if(a instanceof Array)for(b=0;b<a.length;b++)this.addFileDisplay(a[b].id,a[b].filename,a[b].filesize)}});Ext.reg("mixkyfilefield",Mixky.editor.FileField);Ext.namespace("Mixky.editor");
Mixky.editor.ComboTree=Ext.extend(Mixky.editor.PanelTriggerField,{confirm:!0,minListWidth:300,maxHeight:300,minHeight:200,resizable:!1,selectMulti:!0,valueAttribute:"key",displayAttribute:"text",valueSeparator:",",checkWithParent:!0,valueFieldName:void 0,getRealValue:function(){var a=this.getValue(),b=this.findValueFieldCmp();b&&(a=b.getValue());return a},setRealValue:function(a){this.realValue=a;var b=this.findValueFieldCmp();b&&b.setValue(a);if(this.hiddenField)this.hiddenField.value=a},findValueFieldCmp:function(){if(Ext.isDefined(this.valueFieldName)){var a=
this.findParentByType("form");if(a)return a.getForm().findField(this.valueFieldName)}},onSelect:function(a,b,c){this.fireEvent("beforeselect",this,a,b,c)!==!1&&(this.setValue(a),this.setRealValue(b),this.collapse(),this.fireEvent("select",this,a,b,c))},renderPanel:function(a){function b(a,e){e||(e=d.getRootNode());if(e.attributes[c.valueAttribute]==a&&Ext.isDefined(e.attributes.checked))e.attributes.checked=!0,e.getUI().toggleCheck(!0);e.eachChild(function(c){b(a,c)})}var c=this,d=new Ext.tree.TreePanel({region:"center",
autoScroll:!0,rootVisible:!1,style:"background-color:white",root:{nodeType:"async",text:"\u6807\u7b7e\u9009\u62e9"},loader:new Ext.tree.TreeLoader({url:Mixky.wasoft.cache.Applications[this.applicationkey].url+"/"+(this.dataUrl||this.url),preloadChildren:!0}),tools:[{id:"refresh",handler:function(){d.refresh()}}],refresh:function(){this.getRootNode().reload()}});d.getLoader().on("load",function(a,b){b.expand(!0);if(Ext.isDefined(c.valueFieldName)){var e=c.findParentByType("form").getForm().findField(c.valueFieldName);
Ext.isDefined(e.value)&&d.setValue(e.value)}else Ext.isDefined(c.value)&&d.setValue(c.value)});d.on("checkchange",function(a,b){if(b&&!c.selectMulti)for(var e=d.getChecked("id"),h=0;h<e.length;h++)e[h]!=a.id&&d.getNodeById(e[h]).getUI().toggleCheck(!1);c.checkWithParent&&(b?d.checkAllParentNode(a.parentNode):d.unCheckAllChildNode(a))});d.checkAllParentNode=function(a){a&&a!=this.getRootNode()&&a.getUI().toggleCheck(!0)};d.unCheckAllChildNode=function(a){for(var a=a.childNodes,b=0,c=a.length;b<c;b++){if(!a[b]||
a[b]==this.getRootNode())break;a[b].getUI().toggleCheck(!1)}};d.setValue=function(a){if(c.selectMulti)for(var a=a.split(c.valueSeparator),d=0;d<a.length;d++)b(a[d]);else b(a)};var e=[];this.confirm&&(e=[{text:"\u5237\u65b0",iconCls:"icon-sys-refresh",handler:function(){d.refresh()}},"->",{text:"\u786e\u5b9a",iconCls:"icon-sys-confirm",handler:function(){var a=d.getChecked(this.valueAttribute),b=d.getChecked(this.displayAttribute),c="",e="";if(Ext.isDefined(a))for(var g=0;g<a.length;g++)g==0?(c=a[g],
e=b[g]):(c=c+this.valueSeparator+a[g],e=e+";"+b[g]);this.onSelect(e,c);this.collapse()},scope:this},"-",{text:"\u53d6\u6d88",iconCls:"icon-sys-cancel",handler:function(){this.collapse()},scope:this}]);return new Ext.Panel({renderTo:a,layout:"fit",items:[new Ext.Panel({layout:"fit",height:300,items:[d],bbar:e})]})}});Ext.reg("combotree",Mixky.editor.ComboTree);Ext.namespace("Atwa.editor");
Atwa.editor.LenovoText=Ext.extend(Ext.form.TextField,{queryDelay:500,queryParam:"query",minChars:1,minListWidth:200,lazyInit:!0,listClass:"",displayField:"display",selectedClass:"x-combo-selected",shadow:"sides",listAlign:"tl-bl?",maxHeight:200,minHeight:90,listWidth:300,itemSeparator:" ",url:"",directFn:void 0,params:{},initComponent:function(){Atwa.editor.LenovoText.superclass.initComponent.call(this);this.addEvents("expand","collapse","beforeselect","select","beforequery");var a=new Ext.data.JsonReader({root:"results",
totalProperty:"rows",fields:[this.displayField]});this.store=Ext.isDefined(this.directFn)?new Ext.data.Store({proxy:new Ext.data.DirectProxy({directFn:this.directFn,paramsAsHash:!0,paramOrder:["query","params"]}),baseParams:{query:this.queryParam,params:this.params},reader:a}):new Ext.data.Store({proxy:new Ext.data.HttpProxy({url:this.url}),reader:a});if(!Ext.isDefined(this.initialConfig.minChars))this.minChars=0;this.selectedIndex=-1},initEvents:function(){Atwa.editor.LenovoText.superclass.initEvents.call(this);
this.keyNav=new Ext.KeyNav(this.el,{up:function(){this.inKeyMode=!0;this.selectPrev()},down:function(){this.inKeyMode=!0;this.selectNext()},enter:function(){this.onViewClick();this.delayedCheck=!0;this.unsetDelayCheck.defer(10,this)},esc:function(){this.collapse()},tab:function(){this.onViewClick(!1);return!0},scope:this,doRelay:function(a,b,c){return c=="down"||this.scope.isExpanded()?Ext.KeyNav.prototype.doRelay.apply(this,arguments):!0},forceKeyDown:!0});this.queryDelay=Math.max(this.queryDelay||
250);this.dqTask=new Ext.util.DelayedTask(this.initQuery,this);this.editable!==!1&&!this.enableKeyEvents&&this.mon(this.el,"keyup",this.onKeyUp,this)},onRender:function(a,b){Atwa.editor.LenovoText.superclass.onRender.call(this,a,b);this.wrap=this.el.wrap({cls:"x-form-field-wrap x-form-field-trigger-wrap"});this.width||this.wrap.setWidth(this.el.getWidth());Ext.isGecko&&this.el.dom.setAttribute("autocomplete","off");if(this.lazyInit)this.on("focus",this.initList,this,{single:!0});else this.initList()},
initList:function(){if(!this.list){this.list=new Ext.Layer({parentEl:this.getListParent(),shadow:this.shadow,cls:["x-combo-list",this.listClass].join(" "),constrain:!1});var a=this.listWidth||Math.max(this.wrap.getWidth(),this.minListWidth);this.list.setSize(a,0);this.list.swallowEvent("mousewheel");this.assetHeight=0;this.syncFont!==!1&&this.list.setStyle("font-size",this.wrap.getStyle("font-size"));if(this.title)this.header=this.list.createChild({cls:"x-combo-list-hd",html:this.title}),this.assetHeight+=
this.header.getHeight();this.innerList=this.list.createChild({cls:"x-combo-list-inner"});this.mon(this.innerList,"mouseover",this.onViewOver,this);this.mon(this.innerList,"mousemove",this.onViewMove,this);this.innerList.setWidth(a-this.list.getFrameWidth("lr"));if(!this.tpl)this.tpl='<tpl for="."><div class="x-combo-list-item">{'+this.displayField+"}</div></tpl>";this.view=new Ext.DataView({applyTo:this.innerList,tpl:this.tpl,singleSelect:!0,selectedClass:this.selectedClass,itemSelector:this.itemSelector||
".x-combo-list-item",emptyText:this.listEmptyText});this.mon(this.view,"click",this.onViewClick,this);this.bindStore(this.store,!0)}},getStore:function(){return this.store},getListParent:function(){return document.body},onKeyUp:function(a){var b=a.getKey();if(this.editable!==!1&&(b==a.BACKSPACE||!a.isSpecialKey()))this.lastKey=b,this.dqTask.delay(this.queryDelay);Atwa.editor.LenovoText.superclass.onKeyUp.call(this,a)},bindStore:function(a,b){if(this.store&&!b&&(this.store.un("beforeload",this.onBeforeLoad,
this),this.store.un("load",this.onLoad,this),this.store.un("exception",this.collapse,this),this.store!==a&&this.store.autoDestroy&&this.store.destroy(),!a))this.store=null,this.view&&this.view.bindStore(null);if(a)this.store=Ext.StoreMgr.lookup(a),this.store.on({scope:this,beforeload:this.onBeforeLoad,load:this.onLoad,exception:this.collapse}),this.view&&this.view.bindStore(a)},onBeforeLoad:function(){if(this.hasFocus)this.innerList.update(this.loadingText?'<div class="loading-indicator">'+this.loadingText+
"</div>":""),this.restrictHeight(),this.selectedIndex=-1},onLoad:function(){if(this.hasFocus)if(this.store.getCount()>0)this.expand(),this.restrictHeight(),this.select(0,!0);else this.onEmptyResults()},onEmptyResults:function(){this.collapse()},validateBlur:function(){return!this.list||!this.list.isVisible()},initQuery:function(){var a=this.getItemText();a==""||Ext.isEmpty(a)?this.collapse():this.doQuery(this.getItemText())},doQuery:function(a){a=Ext.isEmpty(a)?"":a;a={query:a,field:this,cancel:!1};
if(this.fireEvent("beforequery",a)===!1||a.cancel)return!1;var a=a.query,b=this.params,c={};if(Ext.isDefined(b.panel)&&Ext.isDefined(b.cs)){for(var c=[],c=b.cs.split(","),d="{",e=0,i=0;i<c.length;i++){var f=[],f=c[i].split(":");if(f.length==2){var j=b.panel.getFieldValue(f[0]);Ext.isDefined(j)?e==0?(d=d+f[0]+":'"+j+"'",e=1):d=d+","+f[0]+":'"+j+"'":e==0?(d=d+f[0]+":'"+f[1]+"'",e=1):d=d+","+f[0]+":'"+f[1]+"'"}else j=b.panel.getFieldValue(f[0]),Ext.isDefined(j)&&(e==0?(d=d+f[0]+":'"+j+"'",e=1):d=d+","+
f[0]+":'"+j+"'")}d+="}";c=eval("("+d+")")}a.length>=this.minChars&&(Ext.apply(this.store.baseParams,{query:a,params:c}),this.store.load(),this.expand())},unsetDelayCheck:function(){delete this.delayedCheck},isExpanded:function(){return this.list&&this.list.isVisible()},select:function(a,b){this.selectedIndex=a;this.view.select(a);if(b!==!1){var c=this.view.getNode(a);c&&this.innerList.scrollChildIntoView(c,!1)}},selectPrev:function(){this.store.getCount()>0&&(this.selectedIndex==-1?this.select(0):
this.selectedIndex!==0&&this.select(this.selectedIndex-1))},selectNext:function(){var a=this.store.getCount();a>0&&(this.selectedIndex==-1?this.select(0):this.selectedIndex<a-1&&this.select(this.selectedIndex+1))},onViewMove:function(){this.inKeyMode=!1},onViewOver:function(a,b){if(!this.inKeyMode){var c=this.view.findItemFromChild(b);c&&this.select(this.view.indexOf(c),!1)}},onViewClick:function(a){var b=this.view.getSelectedIndexes()[0],c=this.store.getAt(b);if(c)this.onSelect(c,b);a!==!1&&this.el.focus()},
onSelect:function(a,b){this.fireEvent("beforeselect",this,a,b)!==!1&&(this.replaceItemText(a.data[this.displayField]),this.collapse(),this.fireEvent("select",this,a,b))},getItemText:function(){var a=this.getRawValue(),b=this.el.dom.selectionStart,c=a.substr(0,b).lastIndexOf(this.itemSeparator)+1,d=a.substr(b).indexOf(this.itemSeparator),d=d<0?a.length:b+d;return a.substr(c,d-c)},replaceItemText:function(a){var b=this.getRawValue(),c=this.el.dom.selectionStart,d=b.substr(0,c).lastIndexOf(this.itemSeparator)+
1,e=b.substr(c).indexOf(this.itemSeparator),e=e<0?b.length:e+c+1,b=b.substr(0,d)+a+this.itemSeparator+b.substr(e);this.el.dom.selectionStart=d+a.length+1;this.setValue(b)},collapse:function(){this.isExpanded()&&(this.list.hide(),Ext.getDoc().un("mousewheel",this.collapseIf,this),Ext.getDoc().un("mousedown",this.collapseIf,this),this.fireEvent("collapse",this))},collapseIf:function(a){a.within(this.list)||this.collapse()},expand:function(){!this.isExpanded()&&this.hasFocus&&(this.list.alignTo(this.wrap,
this.listAlign),this.list.show(),Ext.isGecko2&&this.innerList.setOverflow("auto"),Ext.getDoc().on({scope:this,mousewheel:this.collapseIf,mousedown:this.collapseIf}),this.fireEvent("expand",this))},restrictHeight:function(){this.innerList.dom.style.height="";var a=this.innerList.dom,b=this.list.getFrameWidth("tb")+this.assetHeight,a=Math.max(a.clientHeight,a.offsetHeight,a.scrollHeight),c=this.getPosition()[1]-Ext.getBody().getScroll().top,d=Ext.lib.Dom.getViewHeight()-c-this.getSize().height,a=Math.min(a,
Math.max(c,d,this.minHeight||0)-this.list.shadowOffset-b-5,this.maxHeight);this.innerList.setHeight(a);this.list.beginUpdate();this.list.setHeight(a+b);this.list.alignTo(this.wrap,this.listAlign);this.list.endUpdate()},onResize:function(a,b){Atwa.editor.LenovoText.superclass.onResize.apply(this,arguments);if(this.list&&!Ext.isDefined(this.listWidth)){var c=Math.max(a,this.minListWidth);this.list.setWidth(c);this.innerList.setWidth(c-this.list.getFrameWidth("lr"))}}});Ext.reg("lenovotextfield",Atwa.editor.LenovoText);
Atwa.editor.LenovoText1=Ext.extend(Ext.form.TextField,{queryDelay:500,queryParam:"query",minChars:1,minListWidth:200,lazyInit:!0,listClass:"",displayField:"display",selectedClass:"x-combo-selected",shadow:"sides",listAlign:"tl-bl?",maxHeight:200,minHeight:90,listWidth:300,itemSeparator:" ",url:"",directFn:void 0,pageSize:0,paramarry:{},initComponent:function(){Atwa.editor.LenovoText.superclass.initComponent.call(this);this.addEvents("expand","collapse","beforeselect","select","beforequery");var a=
new Ext.data.JsonReader({root:"results",totalProperty:"rows",fields:[this.displayField]});this.store=Ext.isDefined(this.directFn)?new Ext.data.Store({proxy:new Ext.data.DirectProxy({directFn:this.directFn,paramsAsHash:!0}),baseParams:{query:this.queryParam,params:this.params},reader:a}):new Ext.data.Store({proxy:new Ext.data.HttpProxy({url:this.url}),reader:a});if(!Ext.isDefined(this.initialConfig.minChars))this.minChars=0;this.selectedIndex=-1},initEvents:function(){Atwa.editor.LenovoText.superclass.initEvents.call(this);
this.keyNav=new Ext.KeyNav(this.el,{up:function(){this.inKeyMode=!0;this.selectPrev()},down:function(){this.inKeyMode=!0;this.selectNext()},enter:function(){this.onViewClick();this.delayedCheck=!0;this.unsetDelayCheck.defer(10,this)},esc:function(){this.collapse()},tab:function(){this.onViewClick(!1);return!0},scope:this,doRelay:function(a,b,c){return c=="down"||this.scope.isExpanded()?Ext.KeyNav.prototype.doRelay.apply(this,arguments):!0},forceKeyDown:!0});this.queryDelay=Math.max(this.queryDelay||
250);this.dqTask=new Ext.util.DelayedTask(this.initQuery,this);this.editable!==!1&&!this.enableKeyEvents&&this.mon(this.el,"keyup",this.onKeyUp,this)},onRender:function(a,b){Atwa.editor.LenovoText.superclass.onRender.call(this,a,b);this.wrap=this.el.wrap({cls:"x-form-field-wrap x-form-field-trigger-wrap"});this.width||this.wrap.setWidth(this.el.getWidth());Ext.isGecko&&this.el.dom.setAttribute("autocomplete","off");if(this.lazyInit)this.on("focus",this.initList,this,{single:!0});else this.initList()},
initList:function(){if(!this.list){this.list=new Ext.Layer({parentEl:this.getListParent(),shadow:this.shadow,cls:["x-combo-list",this.listClass].join(" "),constrain:!1});var a=this.listWidth||Math.max(this.wrap.getWidth(),this.minListWidth);this.list.setSize(a,0);this.list.swallowEvent("mousewheel");this.assetHeight=0;this.syncFont!==!1&&this.list.setStyle("font-size",this.wrap.getStyle("font-size"));if(this.title)this.header=this.list.createChild({cls:"x-combo-list-hd",html:this.title}),this.assetHeight+=
this.header.getHeight();this.innerList=this.list.createChild({cls:"x-combo-list-inner"});this.mon(this.innerList,"mouseover",this.onViewOver,this);this.mon(this.innerList,"mousemove",this.onViewMove,this);this.innerList.setWidth(a-this.list.getFrameWidth("lr"));if(this.pageSize)this.footer=this.list.createChild({cls:"x-combo-list-ft"}),this.pageTb=new Ext.PagingToolbar({store:this.store,pageSize:this.pageSize,renderTo:this.footer}),this.assetHeight+=this.footer.getHeight();if(!this.tpl)this.tpl='<tpl for="."><div class="x-combo-list-item">{'+
this.displayField+"}</div></tpl>";this.view=new Ext.DataView({applyTo:this.innerList,tpl:this.tpl,singleSelect:!0,selectedClass:this.selectedClass,itemSelector:this.itemSelector||".x-combo-list-item",emptyText:this.listEmptyText});this.mon(this.view,"click",this.onViewClick,this);this.bindStore(this.store,!0)}},getStore:function(){return this.store},getListParent:function(){return document.body},onKeyUp:function(a){var b=a.getKey();if(this.editable!==!1&&(b==a.BACKSPACE||!a.isSpecialKey()))this.lastKey=
b,this.dqTask.delay(this.queryDelay);Atwa.editor.LenovoText.superclass.onKeyUp.call(this,a)},bindStore:function(a,b){if(this.store&&!b&&(this.store.un("beforeload",this.onBeforeLoad,this),this.store.un("load",this.onLoad,this),this.store.un("exception",this.collapse,this),this.store!==a&&this.store.autoDestroy&&this.store.destroy(),!a))this.store=null,this.view&&this.view.bindStore(null);if(a)this.store=Ext.StoreMgr.lookup(a),this.store.on({scope:this,beforeload:this.onBeforeLoad,load:this.onLoad,
exception:this.collapse}),this.view&&this.view.bindStore(a)},onBeforeLoad:function(){if(this.hasFocus)this.innerList.update(this.loadingText?'<div class="loading-indicator">'+this.loadingText+"</div>":""),this.restrictHeight(),this.selectedIndex=-1},onLoad:function(){if(this.hasFocus)if(this.store.getCount()>0)this.expand(),this.restrictHeight(),this.select(0,!0);else this.onEmptyResults()},onEmptyResults:function(){this.collapse()},validateBlur:function(){return!this.list||!this.list.isVisible()},
initQuery:function(){var a=this.getItemText();a==""||Ext.isEmpty(a)?this.collapse():this.doQuery(this.getItemText())},doQuery:function(a){a=Ext.isEmpty(a)?"":a;a={query:a,field:this,cancel:!1};if(this.fireEvent("beforequery",a)===!1||a.cancel)return!1;var a=a.query,b=this.paramarry,c={};if(Ext.isDefined(b.panel)&&Ext.isDefined(b.cs))for(var d=[],d=b.cs.split(","),e=0;e<d.length;e++){var i=[],i=d[e].split(":");c[i[0]]=b.panel.getFieldValue(i[0])}a.length>=this.minChars&&(this.store.baseParams[this.queryParam]=
a,Ext.apply(this.store.baseParams,c),this.store.load({params:this.getParams(a)}),this.expand())},getParams:function(){var a={};if(this.pageSize)a.start=0,a.limit=this.pageSize;return a},unsetDelayCheck:function(){delete this.delayedCheck},isExpanded:function(){return this.list&&this.list.isVisible()},select:function(a,b){this.selectedIndex=a;this.view.select(a);if(b!==!1){var c=this.view.getNode(a);c&&this.innerList.scrollChildIntoView(c,!1)}},selectPrev:function(){this.store.getCount()>0&&(this.selectedIndex==
-1?this.select(0):this.selectedIndex!==0&&this.select(this.selectedIndex-1))},selectNext:function(){var a=this.store.getCount();a>0&&(this.selectedIndex==-1?this.select(0):this.selectedIndex<a-1&&this.select(this.selectedIndex+1))},onViewMove:function(){this.inKeyMode=!1},onViewOver:function(a,b){if(!this.inKeyMode){var c=this.view.findItemFromChild(b);c&&this.select(this.view.indexOf(c),!1)}},onViewClick:function(a){var b=this.view.getSelectedIndexes()[0],c=this.store.getAt(b);if(c)this.onSelect(c,
b);a!==!1&&this.el.focus()},onSelect:function(a,b){this.fireEvent("beforeselect",this,a,b)!==!1&&(this.replaceItemText(a.data[this.displayField]),this.collapse(),this.fireEvent("select",this,a,b))},getItemText:function(){var a=this.getRawValue(),b=this.el.dom.selectionStart,c=a.substr(0,b).lastIndexOf(this.itemSeparator)+1,d=a.substr(b).indexOf(this.itemSeparator),d=d<0?a.length:b+d;return a.substr(c,d-c)},replaceItemText:function(a){var b=this.getRawValue(),c=this.el.dom.selectionStart,d=b.substr(0,
c).lastIndexOf(this.itemSeparator)+1,e=b.substr(c).indexOf(this.itemSeparator),e=e<0?b.length:e+c+1,b=b.substr(0,d)+a+this.itemSeparator+b.substr(e);this.el.dom.selectionStart=d+a.length+1;this.setValue(b)},collapse:function(){this.isExpanded()&&(this.list.hide(),Ext.getDoc().un("mousewheel",this.collapseIf,this),Ext.getDoc().un("mousedown",this.collapseIf,this),this.fireEvent("collapse",this))},collapseIf:function(a){a.within(this.list)||this.collapse()},expand:function(){!this.isExpanded()&&this.hasFocus&&
(this.list.alignTo(this.wrap,this.listAlign),this.list.show(),Ext.isGecko2&&this.innerList.setOverflow("auto"),Ext.getDoc().on({scope:this,mousewheel:this.collapseIf,mousedown:this.collapseIf}),this.fireEvent("expand",this))},restrictHeight:function(){this.innerList.dom.style.height="";var a=this.innerList.dom,b=this.list.getFrameWidth("tb")+this.assetHeight,a=Math.max(a.clientHeight,a.offsetHeight,a.scrollHeight),c=this.getPosition()[1]-Ext.getBody().getScroll().top,d=Ext.lib.Dom.getViewHeight()-
c-this.getSize().height,a=Math.min(a,Math.max(c,d,this.minHeight||0)-this.list.shadowOffset-b-5,this.maxHeight);this.innerList.setHeight(a);this.list.beginUpdate();this.list.setHeight(a+b);this.list.alignTo(this.wrap,this.listAlign);this.list.endUpdate()},onResize:function(a,b){Atwa.editor.LenovoText.superclass.onResize.apply(this,arguments);if(this.list&&!Ext.isDefined(this.listWidth)){var c=Math.max(a,this.minListWidth);this.list.setWidth(c);this.innerList.setWidth(c-this.list.getFrameWidth("lr"))}}});
Ext.reg("lenovotextfield1",Atwa.editor.LenovoText1);Ext.namespace("Atwa.editor");
Atwa.editor.NumberTrigger=Ext.extend(Ext.form.TriggerField,{allowDecimals:!1,decimalSeparator:".",decimalPrecision:2,allowNegative:!1,minValue:Number.NEGATIVE_INFINITY,maxValue:Number.MAX_VALUE,minText:"The minimum value for this field is {0}",maxText:"The maximum value for this field is {0}",nanText:"{0} is not a valid number",baseChars:"0123456789",style:"ime-mode:disabled",initEvents:function(){var a=this.baseChars+"";this.allowDecimals&&(a+=this.decimalSeparator);this.allowNegative&&(a+="-");
this.maskRe=RegExp("["+Ext.escapeRe(a)+"]");Ext.form.NumberField.superclass.initEvents.call(this)},getErrors:function(a){var b=Ext.form.NumberField.superclass.getErrors.apply(this,arguments),a=a||this.processValue(this.getRawValue());if(a.length<1)return b;a=String(a).replace(this.decimalSeparator,".");isNaN(a)&&b.push(String.format(this.nanText,a));var c=this.parseValue(a);c<this.minValue&&b.push(String.format(this.minText,this.minValue));c>this.maxValue&&b.push(String.format(this.maxText,this.maxValue));
return b},setMinValue:function(a){this.minValue=Ext.num(a,Number.NEGATIVE_INFINITY)},setMaxValue:function(a){this.maxValue=Ext.num(a,Number.MAX_VALUE)},parseValue:function(a){a=parseFloat(String(a).replace(this.decimalSeparator,"."));return isNaN(a)?"":a}});Ext.reg("numbertriggerfield",Atwa.editor.NumberTrigger);Ext.namespace("Atwa.editor");
Atwa.editor.NumberTrigger=Ext.extend(Ext.form.TextField,{allowDecimals:!1,decimalSeparator:".",decimalPrecision:2,allowNegative:!1,minValue:Number.NEGATIVE_INFINITY,maxValue:Number.MAX_VALUE,minText:"The minimum value for this field is {0}",maxText:"The maximum value for this field is {0}",nanText:"{0} is not a valid number",baseChars:"0123456789",style:"ime-mode:disabled",initEvents:function(){var a=this.baseChars+"";this.allowDecimals&&(a+=this.decimalSeparator);this.allowNegative&&(a+="-");this.maskRe=
RegExp("["+Ext.escapeRe(a)+"]");Ext.form.NumberField.superclass.initEvents.call(this)},getErrors:function(a){var b=Ext.form.NumberField.superclass.getErrors.apply(this,arguments),a=a||this.processValue(this.getRawValue());if(a.length<1)return b;a=String(a).replace(this.decimalSeparator,".");isNaN(a)&&b.push(String.format(this.nanText,a));var c=this.parseValue(a);c<this.minValue&&b.push(String.format(this.minText,this.minValue));c>this.maxValue&&b.push(String.format(this.maxText,this.maxValue));return b},
setMinValue:function(a){this.minValue=Ext.num(a,Number.NEGATIVE_INFINITY)},setMaxValue:function(a){this.maxValue=Ext.num(a,Number.MAX_VALUE)},parseValue:function(a){a=parseFloat(String(a).replace(this.decimalSeparator,"."));return isNaN(a)?"":a}});Ext.reg("numberText",Atwa.editor.NumberTrigger);
