Ext.ns("Ext.ux.calendar");
Ext.ux.calendar.RepeatType={getEvent:function(b,a){var c=b.repeatType,d=c.rtype,e=c.exceptions;if(c.beginDay<=a&&("no"==c.endDay||a<=c.endDay)&&(!e||!e[a])){var f;"day"==d?f=Ext.ux.calendar.RepeatType.getRepeatDayEvent(a,b):"week"==d?f=Ext.ux.calendar.RepeatType.getRepeatWeekEvent(a,b):"month"==d?f=Ext.ux.calendar.RepeatType.getRepeatMonthEvent(a,b):"year"==d&&(f=Ext.ux.calendar.RepeatType.getRepeatYearEvent(a,b));return f}},getRepeatDayEvent:function(b,a){var c=a.repeatType,d=c.intervalSlot,e=c.dspan,
f=c.rtime,c=Ext.ux.calendar.Mask.getDayOffset(c.beginDay,b),h=Math.floor(c/d);if(0==c%d&&(!f||h<f))return d=Ext.apply({},a),d.day=b,f=Date.parseDate(b,"Y-m-d"),d.eday=f.add(Date.DAY,e).format("Y-m-d"),delete d.lflag,delete d.rflag,d},getRepeatWeekEvent:function(b,a){var c=a.repeatType,d=c.beginDay,e=Date.parseDate(d,"Y-m-d").format("N"),f=Date.parseDate(b,"Y-m-d"),h=f.format("N"),g=c.rday;"{}"==Ext.encode(g)&&(g[e]=!0);if(g[h]&&(f=c.intervalSlot,g=c.dspan,c=c.rtime,d=Math.floor((Ext.ux.calendar.Mask.getDayOffset(d,
b)-h-e)/7)+1,e=Math.floor(d/f),0==d%f&&(!c||e<c)))return d=Ext.apply({},a),d.day=b,f=Date.parseDate(b,"Y-m-d"),d.eday=f.add(Date.DAY,g).format("Y-m-d"),delete d.lflag,delete d.rflag,d},getRepeatMonthEvent:function(b,a){var c=a.repeatType,d=c.beginDay,e=d.split("-",3),f=parseInt(e[0]),h=parseInt(e[1]),g=parseInt(e[2]),e=b.split("-",3),j=parseInt(e[0]),l=parseInt(e[1]),e=parseInt(e[2]),k=c.rby,d=Date.parseDate(d,"Y-m-d").format("N"),m=Math.floor((g-d)/7)+1,i=Date.parseDate(b,"Y-m-d"),i=i.format("N"),
n=Math.floor((e-i)/7)+1;if("date"==k&&g==e||"day"==k&&n==m&&i==d)if(e=c.intervalSlot,g=c.dspan,c=c.rtime,f=12*j+l-12*f-h,h=Math.floor(f/e),0==f%e&&(!c||h<c))return f=Ext.apply({},a),f.day=b,i=Date.parseDate(b,"Y-m-d"),f.eday=i.add(Date.DAY,g).format("Y-m-d"),delete f.lflag,delete f.rflag,f},getRepeatYearEvent:function(b,a){var c=a.repeatType,d=c.beginDay.split("-",3),e=parseInt(d[0]),f=d[1],h=d[2],d=b.split("-",3),g=parseInt(d[0]),j=d[2];if(f==d[1]&&h==j&&(f=c.intervalSlot,d=c.dspan,c=c.rtime,e=g-
e,g=Math.floor(e/f),0==e%f&&(!c||g<c)))return e=Ext.apply({},a),e.day=b,g=Date.parseDate(b,"Y-m-d"),e.eday=g.add(Date.DAY,d).format("Y-m-d"),delete e.lflag,delete e.rflag,e}};Ext.ns("Ext.ux.calendar");
Ext.ux.calendar.Mask={repeatType:[["no","\u4e0d\u91cd\u590d"],["day","\u6bcf\u5929"],["week","\u6bcf\u5468"],["month","\u6bcf\u6708"],["year","\u6bcf\u5e74"]],colors:["668CD9","D96666","59BFB3","F2A442","4CB052","B373B3"],colorIndex:["blue","red","cyan","orange","green","purple"],getColorByIndex:function(b){for(var a=Ext.ux.calendar.Mask,c=0,d=a.colorIndex.length;c<d;c++)if(b==a.colorIndex[c])return a.colors[c];return null},getIndexByColor:function(b){for(var a=Ext.ux.calendar.Mask,c=0,d=a.colors.length;c<
d;c++)if(b==a.colors[c])return a.colorIndex[c];return null},getRepeatTypeStore:function(){return new Ext.data.SimpleStore({fields:["value","display"],data:Ext.ux.calendar.Mask.repeatType})},getCalendarStore:function(){return new Ext.data.SimpleStore({fields:["id","title","description","color"],data:[]})},getHourFormatStore:function(){var b=Ext.ux.calendar.Mask.Mask;return new Ext.data.SimpleStore({fields:["id","text"],data:[["12",b["12Hours"]],["24",b["24Hours"]]]})},parseHM:function(b){var a;a=b.split(":");
b=a[0];"0"==b.charAt(0)&&(b=b.charAt(1));b=parseInt(b);a=a[1];"0"==a.charAt(0)&&(a=a.charAt(1));a=parseInt(a);return{h:b,m:a}},calculateActiveRow:function(b){var a={},c=this.parseHM(b.activeStartTime),d=c.h*60+c.m,c=this.parseHM(b.activeEndTime),c=c.h*60+c.m;a.intervalSlot=parseInt(b.intervalSlot);a.rowCount=1440/a.intervalSlot;a.activeStartRow=Math.floor(d/a.intervalSlot);a.activeEndRow=Math.floor(c/a.intervalSlot);a.numInHour=Math.floor(60/a.intervalSlot);delete b.id;delete b["class"];a=Ext.apply(a,
b);a.startDay=parseInt(a.startDay);a.startRow=0;a.endRow=a.rowCount;if(a.hideInactiveRow)a.startRow=a.activeStartRow,a.endRow=a.activeEndRow;return a},getTimeStore:function(){return new Ext.data.SimpleStore({fields:["row","hour"],data:[]})},getHMFromRow:function(b,a,c){b*=a;a=Math.floor(b/60);b%=60;10>b&&(b="0"+b);10>a&&(a="0"+a);var d=a+":"+b;"12"==c&&(d=Date.parseDate(a+":"+b,"H:i").format("h:i A"));return d},generateIntervalData:function(b,a,c,d){for(var e=Math.floor(1440/b),c=c||e,e=[],a=a||0;a<=
c;a++){var f=[];f.push(a);var h=this.getHMFromRow(b,a,d);f.push(h);e.push(f)}return e},getIntervalFromRow:function(b,a,c){b*=a;a=Math.floor(b/60);b%=60;10>b&&(b="0"+b);10>a&&(a="0"+a);var d=a+":"+b;"12"==c&&(d=Date.parseDate(a+":"+b,"H:i").format("h:i A"));return d},getRowFromHM:function(b,a){"23:59"==b&&(b="24:00");b=Ext.ux.calendar.Mask.parseHM(b);return Math.round(b.h*60/a+b.m/a)},getEDStore:function(){var b=Ext.ux.calendar.Mask.Mask;return new Ext.data.SimpleStore({fields:["value","display"],
data:[[!0,b.enable],[!1,b.disable]]})},getStartDayStore:function(){var b=Ext.ux.calendar.Mask.Mask;return new Ext.data.SimpleStore({fields:["value","display"],data:[[0,b.sunday],[1,b.monday]]})},getIntervalStore:function(){var b=Ext.ux.calendar.Mask.Mask;return new Ext.data.SimpleStore({fields:["value","display"],data:[[10,"10 "+b.minute],[15,"15 "+b.minute],[20,"20 "+b.minute],[30,"30 "+b.minute],[60,"60 "+b.minute]]})},getDayOffset:function(b,a){b instanceof Date||(b=Date.parseDate(b,"Y-m-d"));
a instanceof Date||(a=Date.parseDate(a,"Y-m-d"));var c=b.getElapsed(a);return c=Math.round(c/864E5)},getWeekDayInMonth:function(b){var a=b.format("N"),c=b.format("d"),a=Math.floor((c-a)/7)+1,b=b.format("l");return"\u7b2c"+a+"\u5468 "+b},getIntervalText:function(b,a){var c="";"day"==b?c=1==a?"\u6bcf\u5929":"\u6bcf\u9694 "+a+" \u5929":"week"==b?c=1==a?"\u6bcf\u5468\u7684":"\u6bcf\u9694 "+a+" \u5468 \u7684 ":"month"==b?c=1==a?"\u6bcf\u6708\u7684 ":"\u6bcf\u9694 "+a+" \u6708\u7684 ":"year"==b&&(c=1==
a?"\u6bcf\u5e74\u7684 ":"\u6bcf\u9694 "+a+" \u5e74\u7684 ");return c}};
