Science.message = {
    'new.text': '新建',
    'new.icon': 'x-add-icon',
    'add.text': '添加',
    'edit.text': '编辑',
    'edit.icon': 'x-edit-icon',
    'read.text': '查看',
    'read.icon': 'x-read-icon',
    'delete.text': '删除',
    'delete.icon': 'x-delete-icon',
    'delete.confirm': '确认删除?',
    'confirm.ok': '确定',
    'confirm.cancel': '取消',
    'confirm.alert': '警告',
    'confirm.attention': '提示',
    'action.success': '操作成功',
    'action.failure': '操作失败',
    'action.unknown': '未知原因',
    'session.timeout': '登录超时，请重新登录',
    'session.timeoutconfirm': '登陆超时或服务器响应错误，继续浏览？',
    'request.failure': '请求提交失败',
    'refresh.text': '刷新',
    'refresh.icon': 'x-refresh-icon',
    'wait.title': '请稍候',
    'load.wait': '正在加载信息，请稍候……',
    'save.text': '保存',
    'save.icon': 'x-save-icon',
    'save.wait': '正在保存数据，请稍候……',
    'data.empty': '暂无记录',
    'form.blank': '表单没有填写完整',
    'form.reset': '重置',
    'action.start': 'x-start-icon',
    'action.stop': 'x-stop-icon',
    'close.icon': 'x-close-icon',
    'action.reset': 'x-back-icon',
    'close.text': '关闭',
    'connection.failure': '无法连接远程服务器，请稍候再试',
    'actGetTask.text' : '领取',
    'history.icon': 'x-history-icon',
    'reset.icon': 'x-reset-icon',
    'upload.icon': 'x-upload-icon',
    'node.icon': 'x-node-icon',
    'take.icon': 'x-take-icon',
    'action.pre' : '&lt; 上一步',
    'action.next' : '下一步 &gt;',
    'action.finish' : '完成',
    'action.kaopin': 'x-kaopin-icon',
    'wpzt.ky':'2',
    'wpzt.fm':'3',
    'wpzt.xh':'1',
    "wpzt.sayj":"8",
    'wpzt.fh':'7',
    'wpzt.qtcl':'9',
    'icon.xwbl':'x-xwbl-icon',
    'icon.zccs':'x-zccs-icon',
    'icon.rywpcl':'x-rywpcl-icon',
    'icon.ajclwh':'x-ajclwh-icon',
    'icon.wszz':'x-wszz-icon',
    'icon.flzs':'x-user-select-icon',
    'icon.print':'x-ws-print-icon',//打印的图片
    'icon.ajcl':'x-department-icon',
    'icon.setup':'x-setup-icon'
    	
    	
    	
    	
    	
};
