shineyue.fieldConfigs.cell = [  {
	name : "width",
	caption : "宽度",
	orderNum : "1",
	dataType : "string"
}, {
	name : "height",
	caption : "高度",
	orderNum : "2",
	dataType : "string"
} , {
	name : "height",
	caption : "高度",
	orderNum : "2",
	dataType : "string"
} , {
	name : "height",
	caption : "高度",
	orderNum : "2",
	dataType : "string"
} , {
	name : "height",
	caption : "高度",
	orderNum : "2",
	dataType : "string"
} , {
	name : "height",
	caption : "高度",
	orderNum : "2",
	dataType : "string"
} , {
	name : "height",
	caption : "高度",
	orderNum : "2",
	dataType : "string"
} , {
	name : "height",
	caption : "高度",
	orderNum : "2",
	dataType : "string"
} , {
	name : "height",
	caption : "高度",
	orderNum : "2",
	dataType : "string"
} , {
	name : "height",
	caption : "高度",
	orderNum : "2",
	dataType : "string"
} , {
	name : "height",
	caption : "高度",
	orderNum : "2",
	dataType : "string"
} , {
	name : "height",
	caption : "高度",
	orderNum : "2",
	dataType : "string"
} , {
	name : "height",
	caption : "高度",
	orderNum : "2",
	dataType : "string"
} , {
	name : "height",
	caption : "高度",
	orderNum : "2",
	dataType : "string"
} , {
	name : "height",
	caption : "高度",
	orderNum : "2",
	dataType : "string"
}  ];
