Ext.lib.Ajax=function(){function a(a){function b(a,f){for(d in f)f.hasOwnProperty(d)&&a.setRequestHeader(d,f[d])}var a=a.conn,d;k.defaultHeaders&&b(a,k.defaultHeaders);k.headers&&(b(a,k.headers),delete k.headers)}function b(a,b){(k.headers=k.headers||{})[a]=b}function e(a,b){var d={},f,e=a.conn,k,g;try{f=a.conn.getAllResponseHeaders(),Ext.each(f.replace(/\r\n/g,"\n").split("\n"),function(a){k=a.indexOf(":");k>=0&&(g=a.substr(0,k).toLowerCase(),a.charAt(k+1)==" "&&++k,d[g]=a.substr(k+1))})}catch(p){}return{tId:a.tId,
status:e.status,statusText:e.statusText,getResponseHeader:function(a){return d[a.toLowerCase()]},getAllResponseHeaders:function(){return f},responseText:e.responseText,responseXML:e.responseXML,argument:b}}function d(a,b,d,f){if(b){var k;try{k=a.conn.status!==void 0&&a.conn.status!=0?a.conn.status:13030}catch(g){k=13030}if(k>=200&&k<300||Ext.isIE&&k==1223)d=e(a,b.argument),b.success&&(b.scope?b.success.apply(b.scope,[d]):b.success(d));else switch(k){case 12002:case 12029:case 12030:case 12031:case 12152:case 13030:d=
{tId:a.tId,status:d&&d?-1:0,statusText:d&&d?"transaction aborted":"communication failure",isAbort:d?d:!1,isTimeout:f,argument:b.argument};b.failure&&(b.scope?b.failure.apply(b.scope,[d]):b.failure(d));break;default:d=e(a,b.argument),b.failure&&(b.scope?b.failure.apply(b.scope,[d]):b.failure(d))}}a.conn=null}function h(a,b){var b=b||{},f=a.conn,e=a.tId,g=k.poll,h=b.timeout||null;h&&(k.timeout[e]=setTimeout(function(){k.abort(a,b,!0)},h));g[e]=setInterval(function(){f&&f.readyState==4&&(clearInterval(g[e]),
g[e]=null,h&&(clearTimeout(k.timeout[e]),k.timeout[e]=null),d(a,b))},k.pollInterval)}function g(){var a;try{var b;var d=k.transactionId,e;try{e=new XMLHttpRequest,e.withCredentials="true"}catch(g){for(var h=0;h<f.length;++h)try{e=new ActiveXObject(f[h]);break}catch(o){}}finally{b={conn:e,tId:d}}(a=b)&&k.transactionId++}catch(p){alert("getConnectionObject"+p)}finally{return a}}var f=["Microsoft.XMLHTTP","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP"],k={request:function(f,e,u,s,l){if(l){var q=l.xmlData,o=l.jsonData;
Ext.applyIf(this,l);if(q||o){s=this.headers;if(!s||!s["Content-Type"])b("Content-Type",q?"text/xml":"application/json");s=q||(!Ext.isPrimitive(o)?Ext.encode(o):o)}}if(l.async==!1){if(f=f||l.method||"POST",l=g()||null)l.conn.open(f,e,!1),k.useDefaultXhrHeader&&b("X-Requested-With",k.defaultXhrHeader),s&&k.useDefaultHeader&&(!k.headers||!k.headers["Content-Type"])&&b("Content-Type",k.defaultPostHeader),(k.defaultHeaders||k.headers)&&a(l),l.conn.send(s||null),d(l,u)}else if(f=f||l.method||"POST",l=g()||
null)l.conn.open(f,e,!0),k.useDefaultXhrHeader&&b("X-Requested-With",k.defaultXhrHeader),s&&k.useDefaultHeader&&(!k.headers||!k.headers["Content-Type"])&&b("Content-Type",k.defaultPostHeader),(k.defaultHeaders||k.headers)&&a(l),h(l,u),l.conn.send(s||null);return e=l},serializeForm:function(a){var a=a.elements||(document.forms[a]||Ext.getDom(a)).elements,b=!1,d=encodeURIComponent,f,e="",k;Ext.each(a,function(a){f=a.name;k=a.type;if(!a.disabled&&f)if(/select-(one|multiple)/i.test(k))Ext.each(a.options,
function(a){a.selected&&(e+=String.format("{0}={1}&",d(f),d((a.hasAttribute?a.hasAttribute("value"):a.getAttribute("value")!==null)?a.value:a.text)))});else if(!/file|undefined|reset|button/i.test(k)&&(!/radio|checkbox/i.test(k)||a.checked)&&!(k=="submit"&&b))e+=d(f)+"="+d(a.value)+"&",b=/submit/i.test(k)});return e.substr(0,e.length-1)},useDefaultHeader:!0,defaultPostHeader:"application/x-www-form-urlencoded; charset=UTF-8",useDefaultXhrHeader:!0,defaultXhrHeader:"XMLHttpRequest",poll:{},timeout:{},
pollInterval:50,transactionId:0,abort:function(a,b,f){var e=a.tId,g=!1;this.isCallInProgress(a)&&(a.conn.abort(),clearInterval(this.poll[e]),this.poll[e]=null,clearTimeout(k.timeout[e]),this.timeout[e]=null,d(a,b,g=!0,f));return g},isCallInProgress:function(a){return a.conn&&!{0:!0,4:!0}[a.conn.readyState]}};return k}();Ext.namespace("Mixky.lib");Mixky.lib.NotificationMgr={positions:[]};
Mixky.lib.Notification=Ext.extend(Ext.Window,{initComponent:function(){Ext.apply(this,{iconCls:this.iconCls||"x-icon-information",width:200,autoHeight:!0,closable:!0,plain:!1,draggable:!1,bodyStyle:"text-align:left;padding:10px;",resizable:!1});this.autoDestroy?this.task=new Ext.util.DelayedTask(this.close,this):this.closable=!0;Mixky.lib.Notification.superclass.initComponent.call(this)},setMessage:function(a){this.body.update(a)},setTitle:function(a,b){Mixky.lib.Notification.superclass.setTitle.call(this,
a,b||this.iconCls)},onRender:function(a,b){Mixky.lib.Notification.superclass.onRender.call(this,a,b)},onDestroy:function(){Mixky.lib.NotificationMgr.positions.remove(this.pos);Mixky.lib.Notification.superclass.onDestroy.call(this)},afterShow:function(){Mixky.lib.Notification.superclass.afterShow.call(this);this.on("move",function(){Mixky.lib.NotificationMgr.positions.remove(this.pos);this.autoDestroy&&this.task.cancel()},this);this.autoDestroy&&this.task.delay(this.hideDelay||5E3)},animShow:function(){for(this.pos=
0;Mixky.lib.NotificationMgr.positions.indexOf(this.pos)>-1;)this.pos++;Mixky.lib.NotificationMgr.positions.push(this.pos);this.setSize(200,100);this.el.alignTo(this.animateTarget||document,"br-br",[-1,-1-(this.getSize().height+10)*this.pos]);this.el.slideIn("b",{duration:0.7,callback:this.afterShow,scope:this})},animHide:function(){Mixky.lib.NotificationMgr.positions.remove(this.pos);this.el.ghost("b",{duration:1,remove:!0})}});Ext.MessageBox=function(){var a,b,e,d,h,g,f,k,m,n,u,s,l="",q=function(d){a.isVisible()&&(a.hide(),o(),Ext.callback(b.fn,b.scope||window,[d,u.dom.value,b],1))},o=function(){b&&b.cls&&a.el.removeClass(b.cls);k.reset()};return{getDialog:function(p){if(!a)a=new Ext.Window({manager:MixkyApp.desktop.getManager(),autoCreate:!0,title:p,resizable:!1,constrain:!0,constrainHeader:!0,minimizable:!1,maximizable:!1,stateful:!1,modal:!0,shim:!0,buttonAlign:"center",width:400,height:100,minHeight:80,plain:!0,footer:!0,
closable:!0,close:function(){b&&b.buttons&&b.buttons.no&&!b.buttons.cancel?q("no"):q("cancel")}}),n={},p=this.buttonText,n.ok=a.addButton(p.ok,q.createCallback("ok")),n.yes=a.addButton(p.yes,q.createCallback("yes")),n.no=a.addButton(p.no,q.createCallback("no")),n.cancel=a.addButton(p.cancel,q.createCallback("cancel")),n.ok.hideMode=n.yes.hideMode=n.no.hideMode=n.cancel.hideMode="offsets",a.render(document.body),a.getEl().addClass("x-window-dlg"),e=a.mask,d=a.body.createChild({html:'<div class="ext-mb-icon"></div><div class="ext-mb-content"><span class="ext-mb-text"></span><br /><div class="ext-mb-fix-cursor"><input type="text" class="ext-mb-input" /><textarea class="ext-mb-textarea"></textarea></div></div>'}),
m=Ext.get(d.dom.firstChild),p=d.dom.childNodes[1],h=Ext.get(p.firstChild),g=Ext.get(p.childNodes[2].firstChild),g.enableDisplayMode(),g.addKeyListener([10,13],function(){a.isVisible()&&b&&b.buttons&&(b.buttons.ok?q("ok"):b.buttons.yes&&q("yes"))}),f=Ext.get(p.childNodes[2].childNodes[1]),f.enableDisplayMode(),k=new Ext.ProgressBar({renderTo:d}),d.createChild({cls:"x-clear"});return a},updateText:function(d){!a.isVisible()&&!b.width&&a.setSize(this.maxWidth,100);h.update(d||"&#160;");var d=l!=""?m.getWidth()+
m.getMargins("lr"):0,f=h.getWidth()+h.getMargins("lr"),e=a.getFrameWidth("lr"),g=a.body.getFrameWidth("lr");Ext.isIE&&d>0&&(d+=3);f=Math.max(Math.min(b.width||d+f+e+g,this.maxWidth),Math.max(b.minWidth||this.minWidth,s||0));b.prompt===!0&&u.setWidth(f-d-e-g);(b.progress===!0||b.wait===!0)&&k.setSize(f-d-e-g);Ext.isIE&&f==s&&(f+=4);a.setSize(f,"auto").center();return this},updateProgress:function(a,b,d){k.updateProgress(a,b);d&&this.updateText(d);return this},isVisible:function(){return a&&a.isVisible()},
hide:function(){var b=a?a.activeGhost:null;if(this.isVisible()||b)a.hide(),o(),b&&a.unghost(!1,!1);return this},show:function(d){this.isVisible()&&this.hide();b=d;var h=this.getDialog(b.title||"&#160;");h.setTitle(b.title||"&#160;");var m=b.closable!==!1&&b.progress!==!0&&b.wait!==!0;h.tools.close.setDisplayed(m);u=g;b.prompt=b.prompt||(b.multiline?!0:!1);b.prompt?b.multiline?(g.hide(),f.show(),f.setHeight(typeof b.multiline=="number"?b.multiline:this.defaultTextHeight),u=f):(g.show(),f.hide()):(g.hide(),
f.hide());u.dom.value=b.value||"";if(b.prompt)h.focusEl=u;else{var d=b.buttons,l=null;d&&d.ok?l=n.ok:d&&d.yes&&(l=n.yes);if(l)h.focusEl=l}b.iconCls&&h.setIconClass(b.iconCls);this.setIcon(b.icon);b.cls&&h.el.addClass(b.cls);h.proxyDrag=b.proxyDrag===!0;h.modal=b.modal!==!1;h.mask=b.modal!==!1?e:!1;h.on("show",function(){h.keyMap.setDisabled(m!==!0);h.doLayout();this.setIcon(b.icon);var d=b.buttons,f=0;if(d){a.footer.dom.style.display="";for(var e in n)typeof n[e]!="function"&&(d[e]?(n[e].show(),n[e].setText(typeof d[e]==
"string"?d[e]:Ext.MessageBox.buttonText[e]),f+=n[e].el.getWidth()+15):n[e].hide())}else n.ok.hide(),n.cancel.hide(),n.yes.hide(),n.no.hide();s=f;k.setVisible(b.progress===!0||b.wait===!0);this.updateProgress(0,b.progressText);this.updateText(b.msg);b.wait===!0&&k.wait(b.waitConfig)},this,{single:!0});h.isVisible()||(document.body.appendChild(a.el.dom),h.setAnimateTarget(b.animEl),h.show(b.animEl));return this},setIcon:function(a){a&&a!=""?(m.removeClass("x-hidden"),m.replaceClass(l,a),d.addClass("x-dlg-icon"),
l=a):(m.replaceClass(l,"x-hidden"),d.removeClass("x-dlg-icon"),l="");return this},progress:function(a,b,d){this.show({title:a,msg:b,buttons:!1,progress:!0,closable:!1,minWidth:this.minProgressWidth,progressText:d});return this},wait:function(a,b,d){this.show({title:b,msg:a,buttons:!1,closable:!1,wait:!0,modal:!0,minWidth:this.minProgressWidth,waitConfig:d});return this},alert:function(a,b,d,f){this.show({title:a,msg:b,buttons:this.OK,fn:d,scope:f});return this},confirm:function(a,b,d,f){this.show({title:a,
msg:b,buttons:this.YESNO,fn:d,scope:f,icon:this.QUESTION});return this},prompt:function(a,b,d,f,e,k){this.show({title:a,msg:b,buttons:this.OKCANCEL,fn:d,minWidth:250,scope:f,prompt:!0,multiline:e,value:k});return this},OK:{ok:!0},CANCEL:{cancel:!0},OKCANCEL:{ok:!0,cancel:!0},YESNO:{yes:!0,no:!0},YESNOCANCEL:{yes:!0,no:!0,cancel:!0},INFO:"ext-mb-info",WARNING:"ext-mb-warning",QUESTION:"ext-mb-question",ERROR:"ext-mb-error",defaultTextHeight:75,maxWidth:600,minWidth:110,minProgressWidth:250,buttonText:{ok:"\u786e\u5b9a",
cancel:"\u53d6\u6d88",yes:"\u662f",no:"\u5426"}}}();Ext.Msg=Ext.MessageBox;Ext.namespace("atwasoft.common.lib");
atwasoft.common.lib.getCxdialog=function(a,b,e,d,h){var g=MixkyApp.desktop.openWindowWithJspUrl(a,e,b,{title:d.title,width:d.width,height:d.height,closable:!1,minimizable:!1,modal:!0,manager:MixkyApp.desktop.getManager(),bbar:[{text:"\u5173\u95ed",handler:function(){g.close()}},"->",{text:"\u786e\u5b9a",handler:function(){var a=g.items.get(0).getRecord();g.winRecordHandler(a)}}]},{},d);g.winRecordHandler=function(a){a&&a!=null?(h(a),g.close()):Ext.MessageBox.show({titel:"\u63d0\u793a",msg:"\u8bf7\u9009\u62e9\u8bb0\u5f55\uff01",
modal:!0,buttons:Ext.Msg.OK,icon:Ext.Msg.INFO,width:300,closable:!1})}};
atwasoft.common.lib.getChkdialog=function(a,b,e,d,h){var g=MixkyApp.desktop.openWindowWithJspUrl(a,e,b,{title:d.title,width:d.width,height:d.height,closable:!1,minimizable:!1,modal:!0,manager:MixkyApp.desktop.getManager(),bbar:[{text:"\u5173\u95ed",handler:function(){g.close()}},"->",{text:"\u786e\u5b9a",handler:function(){var a=g.items.get(0).getRecord();g.winRecordHandler(a)}}]},{},d);g.winRecordHandler=function(a){a&&a!=null&&(h(a),g.close())}};
atwasoft.common.lib.getOkdialog=function(a,b,e,d,h){var g=MixkyApp.desktop.openWindowWithJspUrl(a,e,b,{title:d.title,width:d.width,height:d.height,closable:!1,minimizable:!1,modal:!0,manager:MixkyApp.desktop.getManager(),bbar:[{text:"\u5173\u95ed",handler:function(){g.winRecordHandler(!1)}},"->",{text:"\u786e\u5b9a",handler:function(){var a=g.items.get(0).getRecord();g.winRecordHandler(a)}}]},{},d);g.winRecordHandler=function(a){h(a);g.close()}};
atwasoft.common.lib.getChkdialog_gj=function(a,b,e,d,h){var g=d.gjdbm,f=MixkyApp.desktop.openWindowWithJspUrl(a,e,b,{title:d.title,width:d.width,height:d.height,closable:!1,minimizable:!1,modal:!0,manager:MixkyApp.desktop.getManager(),bbar:[{text:"\u5173\u95ed",handler:function(){f.close()}},"->",{text:"\u786e\u5b9a",handler:function(){var a=f.items.get(0).getRecord();f.winRecordHandler(a)}}]},{},d);f.winRecordHandler=function(a){a&&a!=null&&ConsoleGzAppDirect.Gz_Dw_Zwdate_Chk(a.rzrq,g,function(b){b.success?
(h(a),f.close()):Ext.MessageBox.alert("\u63d0\u793a",b.msg)})}};
atwasoft.common.lib.getChkdialog_cw=function(a,b,e,d,h){var g=MixkyApp.desktop.openWindowWithJspUrl(a,e,b,{title:d.title,width:d.width,height:d.height,closable:!1,minimizable:!1,modal:!0,manager:MixkyApp.desktop.getManager(),bbar:[{text:"\u5173\u95ed",handler:function(){g.close()}},"->",{text:"\u786e\u5b9a",handler:function(){var a=g.items.get(0).getRecord();g.winRecordHandler(a)}}]},{},d);g.winRecordHandler=function(a){if(a&&a!=null){var b={};b.qx=a.qx;b.uid=a.uid;b.userpas=a.userpas;b.chkrq=a.chkrq;
Cw_pzglDirect.userchk(b,function(b){b&&b.success?(h(a),g.close()):Ext.MessageBox.show({title:"\u63d0\u793a",msg:b.msg,modal:!0,buttons:Ext.Msg.OK,icon:Ext.Msg.ERROR,width:300,closable:!1})})}}};
atwasoft.common.lib.getZtdialog=function(a,b,e){e&&e.hideMenu();WacwAppDirect.getZtChk(b,function(b){if(b&&!b.success){MixkyApp.desktop.closeModule("wacw","wacwpzgl");MixkyApp.desktop.closeModule("wacw","wacwqmcl");MixkyApp.desktop.closeModule("wacw","wacwzbgl");MixkyApp.desktop.closeModule("wacw","wacwpjgl");MixkyApp.desktop.closeModule("wacw","wacwreport");MixkyApp.desktop.closeModule("wacw","wacwpzcx");var b={title:"\u8d26\u5957\u9009\u62e9",width:300,height:280},h=function(a){WacwAppDirect.getZtxx(a.ztbh,
a.nd+a.yf,function(){})},g=MixkyApp.desktop.openWindowWithJspUrl(a,"ztdialog","app/common/ztml",{title:b.title,width:b.width,height:b.height,closable:!1,minimizable:!1,modal:!0,manager:MixkyApp.desktop.getManager(),bbar:[{text:"\u5173\u95ed",handler:function(){g.close()}},"->",{text:"\u786e\u5b9a",handler:function(){var a=g.items.get(0).getRecord();g.winRecordHandler(a)}}]},{},b);g.winRecordHandler=function(a){a&&a!=null&&(h(a),g.close())}}else e&&(b.ztxz!="06"?e.menu.items.get(4).hide():e.menu.items.get(4).show(),
e.showMenu()),MixkyApp.desktop.settitlebar(b.cznd,b.cwzt)})};atwasoft.common.lib.cxdialog=function(a,b,e,d){MixkyApp.desktop.openWindowWithJspUrl(a,e,b,{title:d.title,width:d.width,height:d.height,closable:!0,minimizable:!1,modal:!0,result:d.result,param:d,manager:MixkyApp.desktop.getManager()},{},d)};
atwasoft.common.lib.getCx1dialog=function(a,b,e,d,h){var g=MixkyApp.desktop.openWindowWithJspUrl(a,e,b,{title:d.title,width:d.width,height:d.height,closable:!1,minimizable:!1,modal:!0,manager:MixkyApp.desktop.getManager(),buttons:[{text:"\u53e6\u5b58\u4e3a",handler:function(){g.close()}},{text:"\u6253\u5370",handler:function(){g.close()}},{text:"\u5173\u95ed",handler:function(){g.winRecordHandler()}}]},{},d);g.winRecordHandler=function(){h();g.close()}};
atwasoft.common.lib.DirectPrintPanel=function(a,b,e){b=encodeURI(encodeURI(b));a=Mixky.wasoft.cache.Applications.report.url+"/jsppage.do?url=app/report/printPanel&reportFile="+a+"&param="+b+"&set="+e;if(!atwasoft.common.lib.DirectPrintPanel.el)b=document.createElement("iframe"),b.setAttribute("vspace","-300px"),b.setAttribute("hspace","-800px"),b.setAttribute("width","200px"),b.setAttribute("height","700px"),atwasoft.common.lib.DirectPrintPanel.el=Ext.getBody().appendChild(b);atwasoft.common.lib.DirectPrintPanel.el.dom.src=
a};atwasoft.common.lib.DirectShowReport=function(a,b,e,d,h){b=encodeURI(b);MixkyApp.desktop.openWindowWithJspUrl("report","reportpanel","app/report/showReport",{title:e,width:d,height:h,modal:!1},{},{reportFile:a,param:b})};
atwasoft.common.lib.DirectShowPreview=function(a,b,e){var b=encodeURI(b),d=screen.width,h=screen.height;window.showModalDialog(Mixky.wasoft.cache.Applications.report.url+"/jsppage.do?url=app/report/showPreview&width="+d+"&height="+h+"&reportFile="+a+"&param="+b+"&set="+e,window,"dialogWidth:"+d+"px;dialogHeight:"+h+"px;dialogLeft:"+(screen.width-NaN)/2+"px;dialogTop:"+(screen.height-NaN)/2+"px;center:yes;help:no;resizable:no;status:no;scrollbars:no;location=no;")};
atwasoft.common.lib.DirectPrintPanel_cw=function(a,b,e,d){d=encodeURI(encodeURI(d));a=Mixky.wasoft.cache.Applications.report.url+"/jsppage.do?url=app/report/prtinPanel_cw&bbid="+a+"&date="+b+"&dateType="+e+"&param="+d;if(!atwasoft.common.lib.DirectPrintPanel_cw.el)b=document.createElement("iframe"),b.setAttribute("vspace","-300px"),b.setAttribute("hspace","-800px"),b.setAttribute("width","200px"),b.setAttribute("height","700px"),atwasoft.common.lib.DirectPrintPanel_cw.el=Ext.getBody().appendChild(b);
atwasoft.common.lib.DirectPrintPanel_cw.el.dom.src=a};
atwasoft.common.lib.exportexcel=function(a){try{var b=new ActiveXObject("Excel.Application")}catch(e){Ext.MessageBox.show({title:"\u63d0\u793a",msg:"\u8981\u6253\u5370\u8be5\u8868\uff0c\u60a8\u5fc5\u987b\u5b89\u88c5Excel\u7535\u5b50\u8868\u683c\u8f6f\u4ef6,\u540c\u65f6\u6d4f\u89c8\u5668\u987b\u4f7f\u7528ActiveX\u63a7\u4ef6,\u60a8\u7684\u6d4f\u89c8\u5668\u987b\u5141\u8bb8\u6267\u884c\u63a7\u4ef6\u3002\u8bf7\u70b9\u51fb\u3010\u5e2e\u52a9\u3011\u4e86\u89e3\u6d4f\u89c8\u5668\u8bbe\u7f6e\u65b9\u6cd5\uff01",modal:!0,
buttons:Ext.Msg.OK,icon:Ext.Msg.INFO,width:450,closable:!1})}b.visible=!0;var d=b.Workbooks.Add.Worksheets(1),h=a.getColumnModel(),g=h.getColumnCount(),f=[];for(i=1;i<g;i++)h.isHidden(i)!=!0&&f.push(i);for(i=1;i<=f.length-2;i++)d.Cells(1,i).Value=h.getColumnHeader(f[i-1]);h=a.getStore().getCount();a=a.getView();for(i=1;i<=h;i++)for(j=1;j<=f.length;j++)d.Cells(i+1,j).Value=a.getCell(i-1,f[j-1]).innerText;b.ActiveWindow.Zoom=75;b.UserControl=!0};Ext.namespace("atwa.util");
atwa.util.Format={Money:function(a){return/([0-9]+)([.]?)([0-9]?)/.test(a)?(a=Math.round((a-0)*100)/100,a=a==Math.floor(a)?a+".00":a*10==Math.floor(a*10)?a+"0":a,a=String(a).split("."),a=a[0]+(a[1]?"."+a[1]:".00"),a.charAt(0)=="-"?"-"+a.substr(1):a):""},toMoney:function(a,b){var a=parseFloat((a+"").replace(/[^\d\.-]/g,"")).toFixed(b>0&&b<=20?b:2)+"",e=a.split(".")[0].split("").reverse(),d=a.split(".")[1];t="";for(i=0;i<e.length;i++)t+=e[i]+((i+1)%3==0&&i+1!=e.length?",":"");return t.split("").reverse().join("")+
"."+d},rMoney:function(a){return a=a!=""?a.replace(/[^\d\.-]/g,""):"0.00"},round:function(a,b){return a=Math.round(a*Math.pow(10,b))/Math.pow(10,b)},pzlbview:function(a,b){var e="";a==0?b==0&&(e="\u8bb0"):a==1?b==1?e="\u6536":b==2?e="\u4ed8":b==0&&(e="\u8f6c"):a==2?b==1?e="\u73b0":b==2?e="\u94f6":b==0&&(e="\u8f6c"):a==3&&(b==1?e="\u73b0\u6536":b==2?e="\u73b0\u4ed8":b==3?e="\u94f6\u6536":b==4?e="\u94f6\u4ed8":b==0&&(e="\u8f6c\u8d26"));return e}};Ext.PagingToolbar.prototype.initComponent=function(){var a=[this.first=new Ext.Toolbar.Button({tooltip:this.firstText,overflowText:this.firstText,iconCls:"x-tbar-page-first",disabled:!0,handler:this.moveFirst,scope:this}),this.prev=new Ext.Toolbar.Button({tooltip:this.prevText,overflowText:this.prevText,iconCls:"x-tbar-page-prev",disabled:!0,handler:this.movePrevious,scope:this}),"-",this.beforePageText,this.inputItem=new Ext.form.NumberField({cls:"x-tbar-page-number",allowDecimals:!1,allowNegative:!1,
enableKeyEvents:!0,selectOnFocus:!0,submitValue:!1,listeners:{scope:this,keydown:this.onPagingKeyDown,blur:this.onPagingBlur}}),this.afterTextItem=new Ext.Toolbar.TextItem({text:String.format(this.afterPageText,1)}),"-",this.next=new Ext.Toolbar.Button({tooltip:this.nextText,overflowText:this.nextText,iconCls:"x-tbar-page-next",disabled:!0,handler:this.moveNext,scope:this}),this.last=new Ext.Toolbar.Button({tooltip:this.lastText,overflowText:this.lastText,iconCls:"x-tbar-page-last",disabled:!0,handler:this.moveLast,
scope:this}),this.refresh=new Ext.Toolbar.Button({tooltip:this.refreshText,overflowText:this.refreshText,iconCls:"x-tbar-loading",handler:this.doRefresh,hidden:!0,scope:this})],b=this.items||this.buttons||[];this.items=this.prependButtons?b.concat(a):a.concat(b);delete this.buttons;if(this.displayInfo)this.items.push("->"),this.items.push(this.displayItem=new Ext.Toolbar.TextItem({}));Ext.PagingToolbar.superclass.initComponent.call(this);this.addEvents("change","beforechange");this.on("afterlayout",
this.onFirstLayout,this,{single:!0});this.cursor=0;this.bindStore(this.store,!0)};
Ext.ux.ProgressBarPager.prototype.init=function(a){if(a.displayInfo)this.parent=a,a.items.indexOf(a.displayItem),a.remove(a.displayItem,!0),this.progressBar=new Ext.ProgressBar({text:this.defaultText,width:this.progBarWidth,animate:this.defaultAnimCfg}),a.displayItem=this.progressBar,a.add(a.displayItem),a.doLayout(),Ext.apply(a,this.parentOverrides),this.progressBar.on("render",function(a){a.mon(a.getEl().applyStyles("cursor:pointer"),"",this.handleProgressBarClick,this)},this,{single:!0})};
Ext.grid.GroupingView.prototype.doRender=function(a,b,e,d,h,g){if(b.length<1)return"";if(!this.canGroup()||this.isUpdating)return Ext.grid.GroupingView.superclass.doRender.apply(this,arguments);var f=this.getGroupField(),k=this.cm.findColumnIndex(f),m,n="width:"+this.getTotalWidth()+";";m=this.cm.config[k];var u=m.groupRenderer||m.renderer,s=this.showGroupName?(m.groupName||m.header)+": ":"",l=[],q,o,p,v;o=0;for(p=b.length;o<p;o++){var y=d+o,w=b[o],x=w.data[f];o<p-1?m=this.getGroup(x,w,u,y,k,e):s=
m="";!q||q.group!=m?(v=this.constructId(x,f,k),this.state[v]=!(Ext.isDefined(this.state[v])?!this.state[v]:this.startCollapsed),q={group:m,gvalue:x,text:s+m,groupId:v,startRow:y,rs:[w],cls:this.state[v]?"":"x-grid-group-collapsed",style:n},l.push(q)):q.rs.push(w);w._groupId=v}f=[];o=0;for(p=l.length;o<p;o++)m=l[o],this.doGroupStart(f,m,a,e,h),f[f.length]=Ext.grid.GroupingView.superclass.doRender.call(this,a,m.rs,e,m.startRow,h,g),this.doGroupEnd(f,m,a,e,h);return f.join("")};
Ext.grid.GridView.prototype.handleHdDown=function(a,b){if(Ext.fly(b).hasClass("x-grid3-hd-btn")){a.stopEvent();var e=this.findHeaderCell(b);Ext.fly(e).addClass("x-grid3-hd-menu-open");var d=this.getCellIndex(e);this.hdCtxIndex=d;var h=this.hmenu.items,g=this.cm;h.get("asc").setDisabled(!g.isSortable(d));h.get("desc").setDisabled(!g.isSortable(d));g.isSortable(d)||(h.get("asc").hide(),h.get("desc").hide());this.hmenu.on("hide",function(){Ext.fly(e).removeClass("x-grid3-hd-menu-open")},this,{single:!0});
this.hmenu.show(b,"tl-bl?")}};
Ext.override(Ext.grid.RowSelectionModel,{onEditorKey:function(a,b){var e=b.getKey(),d,h=this.grid,g=h.lastEdit,f=h.activeEditor,k=b.shiftKey;f||(f=g);e==b.ENTER?(b.stopEvent(),d=k?h.walkCells(f.row,f.col-1,-1,this.acceptsNav,this):h.walkCells(f.row,f.col+1,1,this.acceptsNav,this)):e==b.TAB&&(b.stopEvent(),f.completeEdit(),this.moveEditorOnEnter!==!1&&(d=k?h.walkCells(f.row-1,f.col,-1,this.acceptsNav,this):h.walkCells(f.row,f.col+1,1,this.acceptsNav,this)));d&&(r=d[0],c=d[1],g.row!=r&&this.selectRow(r),
h.startEditing(r,c))}});Ext.namespace("atwa.zjhm");
atwa.zjhm={Check:function(a){if(a=="")return"";var b=["\u9a8c\u8bc1\u901a\u8fc7!","\u8eab\u4efd\u8bc1\u53f7\u7801\u4f4d\u6570\u4e0d\u5bf9!","\u8eab\u4efd\u8bc1\u53f7\u7801\u51fa\u751f\u65e5\u671f\u8d85\u51fa\u8303\u56f4\u6216\u542b\u6709\u975e\u6cd5\u5b57\u7b26!","\u8eab\u4efd\u8bc1\u53f7\u7801\u6821\u9a8c\u9519\u8bef!","\u8eab\u4efd\u8bc1\u5730\u533a\u975e\u6cd5!"],e,d=[],d=a.split("");if({11:"\u5317\u4eac",12:"\u5929\u6d25",13:"\u6cb3\u5317",14:"\u5c71\u897f",15:"\u5185\u8499\u53e4",21:"\u8fbd\u5b81",
22:"\u5409\u6797",23:"\u9ed1\u9f99\u6c5f",31:"\u4e0a\u6d77",32:"\u6c5f\u82cf",33:"\u6d59\u6c5f",34:"\u5b89\u5fbd",35:"\u798f\u5efa",36:"\u6c5f\u897f",37:"\u5c71\u4e1c",41:"\u6cb3\u5357",42:"\u6e56\u5317",43:"\u6e56\u5357",44:"\u5e7f\u4e1c",45:"\u5e7f\u897f",46:"\u6d77\u5357",50:"\u91cd\u5e86",51:"\u56db\u5ddd",52:"\u8d35\u5dde",53:"\u4e91\u5357",54:"\u897f\u85cf",61:"\u9655\u897f",62:"\u7518\u8083",63:"\u9752\u6d77",64:"\u5b81\u590f",65:"\u65b0\u7586",71:"\u53f0\u6e7e",81:"\u9999\u6e2f",82:"\u6fb3\u95e8",
91:"\u56fd\u5916"}[parseInt(a.substr(0,2))]==null)return b[4];switch(a.length){case 15:return ereg=(parseInt(a.substr(6,2))+1900)%4==0||(parseInt(a.substr(6,2))+1900)%100==0&&(parseInt(a.substr(6,2))+1900)%4==0?/^[1-9][0-9]{5}[0-9]{2}((01|03|05|07|08|10|12)(0[1-9]|[1-2][0-9]|3[0-1])|(04|06|09|11)(0[1-9]|[1-2][0-9]|30)|02(0[1-9]|[1-2][0-9]))[0-9]{3}$/:/^[1-9][0-9]{5}[0-9]{2}((01|03|05|07|08|10|12)(0[1-9]|[1-2][0-9]|3[0-1])|(04|06|09|11)(0[1-9]|[1-2][0-9]|30)|02(0[1-9]|1[0-9]|2[0-8]))[0-9]{3}$/,ereg.test(a)?
"":b[2];case 18:return ereg=parseInt(a.substr(6,4))%4==0||parseInt(a.substr(6,4))%100==0&&parseInt(a.substr(6,4))%4==0?/^[1-9][0-9]{5}19[0-9]{2}((01|03|05|07|08|10|12)(0[1-9]|[1-2][0-9]|3[0-1])|(04|06|09|11)(0[1-9]|[1-2][0-9]|30)|02(0[1-9]|[1-2][0-9]))[0-9]{3}[0-9Xx]$/:/^[1-9][0-9]{5}19[0-9]{2}((01|03|05|07|08|10|12)(0[1-9]|[1-2][0-9]|3[0-1])|(04|06|09|11)(0[1-9]|[1-2][0-9]|30)|02(0[1-9]|1[0-9]|2[0-8]))[0-9]{3}[0-9Xx]$/,ereg.test(a)?(a=(parseInt(d[0])+parseInt(d[10]))*7+(parseInt(d[1])+parseInt(d[11]))*
9+(parseInt(d[2])+parseInt(d[12]))*10+(parseInt(d[3])+parseInt(d[13]))*5+(parseInt(d[4])+parseInt(d[14]))*8+(parseInt(d[5])+parseInt(d[15]))*4+(parseInt(d[6])+parseInt(d[16]))*2+parseInt(d[7])*1+parseInt(d[8])*6+parseInt(d[9])*3,a%=11,e="10X98765432".substr(a,1),M1="F",JYM1="10x98765432",M1=JYM1.substr(a,1),e==d[17]||M1==d[17]?"":b[3]):b[2];default:return b[1]}}};Ext.namespace("atwa.date");
atwa.date={isDate:function(a){try{return date_array=(new String(a)).split("-"),parseInt(date_array[0],10),parseInt(date_array[1],10),parseInt(date_array[2],10),!0}catch(b){return!1}},IsyyyyMM:function(a){return(new String(a)).length!=6?!1:(a=(new String(a)).substring(0,4)+"-"+(new String(a)).substring(4,6)+"-01",atwa.date.CheckDate(new String(a))?!0:!1)},Isyyyy_MM:function(a){var b="";(new String(a)).length==6?b=(new String(a)).substring(0,4)+"-"+(new String(a)).substring(4,6)+"-01":(new String(a)).length==
7&&(b=new String(a)+"-01");return atwa.date.CheckDate(new String(b))?!0:!1},Cfgyyyy_MM:function(a){if((new String(a)).length==6)return(new String(a)).substring(0,4)+"-"+(new String(a)).substring(4,6);else if((new String(a)).length==7)return a},CheckDate:function(a){if(a=="")return!1;subYY=a.substr(0,4);if(isNaN(subYY)||subYY<=0)return!1;if(a.indexOf("-",0)!=-1)separate="-";else if(a.indexOf("/",0)!=-1)separate="/";else return!1;area=a.indexOf(separate,0);subMM=a.substr(area+1,a.indexOf(separate,area+
1)-(area+1));if(isNaN(subMM)||subMM<=0)return!1;subMM.length<2&&(subMM="0"+subMM);area=a.lastIndexOf(separate);subDD=a.substr(area+1,a.length-area-1);if(isNaN(subDD)||subDD<=0)return!1;eval(subDD)<10&&(subDD="0"+eval(subDD));NewDate=subYY+"-"+subMM+"-"+subDD;if(NewDate.length!=10)return!1;if(NewDate.substr(4,1)!="-")return!1;if(NewDate.substr(7,1)!="-")return!1;var a=NewDate.substr(5,2),b=NewDate.substr(8,2);if(subYY%4==0&&subYY%100!=0||subYY%400==0){if(parseInt(a)==2&&b>29)return!1}else if(parseInt(a)==
2&&b>28)return!1;var e=[1,3,5,7,8,10,12];for(i=0;i<e.length;i++)if(parseInt(a)==e[i]){if(parseInt(b)>31)return!1}else if(parseInt(b)>30)return!1;return parseInt(a)>12?!1:!0},formatDateInput:function(a){a.length==8&&(ctl=a.substr(0,4)+"-"+a.substr(4,2)+"-"+a.substr(6,2));a.length==6&&(ctl=(new Date).getYear().toString().substr(0,2)+a.substr(0,2)+"-"+a.substr(2,2)+"-"+a.substr(4,2));return ctl}};
