Mixky.wasoft.App=function(a){Ext.apply(this,a);this.addEvents({ready:!0,beforeunload:!0});Ext.Direct.on("exception",function(a){this.showErrorMessage(a.message,"\u670d\u52a1\u5668\u4ea4\u4e92\u9519\u8bef")},this);Ext.QuickTips.init();Ext.onReady(this.initApp,this)};
Ext.extend(Mixky.wasoft.App,Ext.util.Observable,{isReady:!1,userConfig:void 0,userMenus:void 0,initApp:function(){this.desktop=new Mixky.wasoft.Desktop(this);this.userConfig?this.setUserConfig():this.getUserConfig();new Ext.KeyMap(document,[{key:Ext.EventObject.BACKSPACE,fn:function(a,b){var d=b.target.tagName;d!="INPUT"&&d!="TEXTAREA"&&b.stopEvent()}}]);Ext.getBody().on("contextmenu",function(a){a.preventDefault()});this.doAutoOpen.defer(500,this);this.fireEvent("ready",this);Ext.EventManager.on(window,
"beforeunload",this.onUnload,this);Ext.EventManager.on(window,"beforeunload",this.onUnload,this);this.isReady=!0},getUserConfig:function(){var a=this;DesktopDirect.getUserConfig("",function(b){b&&b.success?(a.userConfig=b.userconfig,a.setUserConfig()):a.showError("\u88c5\u8f7d\u7528\u6237\u8bbe\u7f6e\u4fe1\u606f\u5931\u8d25\uff01")})},setUserConfig:function(){this.desktop.setWallpaper(this.userConfig.wallpaper);this.desktop.setWallpaperPosition(this.userConfig.wallpaperposition);this.desktop.setTransparency(this.userConfig.transparency);
this.desktop.setBackgroundColor(this.userConfig.backgroundcolor);this.desktop.setFrontColor(this.userConfig.frontcolor);this.desktop.setTheme(this.userConfig.theme);for(var a=0;a<this.userConfig.shortcuts.length;a++){var b=Ext.apply({},this.userConfig.shortcuts[a]);this.desktop.addShortcut(b)}this.userConfig.subjects.sort(function(a,b){var e=Ext.isDefined(a.row)?a.row:0,h=Ext.isDefined(b.row)?b.row:0,f=Ext.isDefined(a.col)?a.col:0,g=Ext.isDefined(b.col)?b.col:0;return f==g?e>h:f>g});for(a=0;a<this.userConfig.subjects.length;a++)b=
Ext.apply({},this.userConfig.subjects[a]),this.desktop.addSubject(b);for(a=0;a<this.userConfig.quickstarts.length;a++)b=Ext.apply({},this.userConfig.quickstarts[a]),this.desktop.addQuickStart(b)},setTheme:function(a){if(a)this.userConfig.theme=a,this.desktop.setTheme(this.userConfig.theme)},setBackgroundColor:function(a){if(a)this.userConfig.backgroundcolor=a,this.desktop.setBackgroundColor(this.userConfig.backgroundcolor)},setFrontColor:function(a){if(a)this.userConfig.frontcolor=a,this.desktop.setFrontColor(this.userConfig.frontcolor)},
setTransparency:function(a){if(a>=0&&a<=100)this.userConfig.transparency=a,this.desktop.setTransparency(this.userConfig.transparency)},setWallpaper:function(a){if(a)this.userConfig.wallpaper=a,this.desktop.setWallpaper(this.userConfig.wallpaper)},setWallpaperPosition:function(a){if(a)this.userConfig.wallpaperposition=a,this.desktop.setWallpaper(this.userConfig.wallpaperposition)},showDesktop:function(){this.desktop.showDesktop()},hasShortcut:function(a,b,d){for(var c=0;c<this.userConfig.shortcuts.length;c++){var e=
this.userConfig.shortcuts[c];if(e.btntype==a&&e.applicationkey==b&&e.key==d)return!0}},addShortcut:function(a){this.userConfig.shortcuts.push(a);var b={},b=Ext.apply(b,a);this.desktop.addShortcut(b)},removeShortcut:function(a,b,d){this.desktop.removeShortcut(a,b,d);for(var c=0;c<this.userConfig.shortcuts.length;c++){var e=this.userConfig.shortcuts[c];if(e.btntype==a&&e.applicationkey==b&&e.key==d){this.userConfig.shortcuts.splice(c,1);break}}},hasQuickStart:function(a,b,d){for(var c=0;c<this.userConfig.quickstarts.length;c++){var e=
this.userConfig.quickstarts[c];if(e.btntype==a&&e.applicationkey==b&&e.key==d)return!0}},addQuickStart:function(a){this.userConfig.quickstarts.push(a);var b={},b=Ext.apply(b,a);this.desktop.addQuickStart(b)},removeQuickStart:function(a,b,d){this.desktop.removeQuickStart(a,b,d);for(var c=0;c<this.userConfig.quickstarts.length;c++){var e=this.userConfig.quickstarts[c];if(e.btntype==a&&e.applicationkey==b&&e.key==d){this.userConfig.quickstarts.splice(c,1);break}}},hasSubject:function(a,b){for(var d=
0;d<this.userConfig.subjects.length;d++){var c=this.userConfig.subjects[d];if(c.applicationkey==a&&c.key==b)return!0}},getSubject:function(a,b){for(var d=0;d<this.userConfig.subjects.length;d++){var c=this.userConfig.subjects[d];if(c.applicationkey==a&&c.key==b)return c}},addSubject:function(a){this.userConfig.subjects.push(a);var b={},b=Ext.apply(b,a);this.desktop.addSubject(b)},removeSubject:function(a,b){this.desktop.removeSubject(a,b);for(var d=0;d<this.userConfig.subjects.length;d++){var c=this.userConfig.subjects[d];
if(c.applicationkey==a&&c.key==b){this.userConfig.subjects.splice(d,1);break}}},showWaitMessage:function(a){return this.showNotification({title:"\u8bf7\u7a0d\u5019...",html:a,iconCls:"x-icon-wait"})},showInfoMessage:function(a){this.hideNotification(this.showNotification({title:"\u4fe1\u606f\u63d0\u793a",html:a,iconCls:"x-icon-information"}),5E3)},showAlertMessage:function(a){this.hideNotification(this.showNotification({title:"\u8b66\u544a\u4fe1\u606f",html:a,iconCls:"x-icon-alert"}),5E3)},showErrorMessage:function(a){this.hideNotification(this.showNotification({title:"\u9519\u8bef\u63d0\u793a",
html:a,iconCls:"x-icon-error"}),5E3)},showDirectActionFail:function(a){MixkyApp.showErrorMessage("\u3010"+a+"\u3011\u64cd\u4f5c\u5931\u8d25\uff01")},showFormActionFail:function(a,b){switch(b.failureType){case Ext.form.Action.CLIENT_INVALID:MixkyApp.showErrorMessage("\u63d0\u4ea4\u6570\u636e\u975e\u6cd5\uff01");break;case Ext.form.Action.CONNECT_FAILURE:MixkyApp.showErrorMessage("\u670d\u52a1\u5668\u8fde\u63a5\u9519\u8bef\uff01");break;case Ext.form.Action.SERVER_INVALID:b.result.errors&&b.result.errors.msg?
MixkyApp.showErrorMessage("\u670d\u52a1\u5668\u6570\u636e\u5904\u7406\u9519\u8bef\uff01<br/>"+b.result.errors.msg):MixkyApp.showErrorMessage("\u670d\u52a1\u5668\u6570\u636e\u5904\u7406\u9519\u8bef\uff01");break;case Ext.form.Action.LOAD_FAILURE:MixkyApp.showErrorMessage("\u8868\u5355\u6570\u636e\u88c5\u8f7d\u5931\u8d25\uff01")}},showNotification:function(a){a=new Mixky.lib.Notification(Ext.apply({animateTarget:this.desktop.getAnimateTarget(),autoDestroy:!0,hideDelay:2E3,html:"",iconCls:"x-icon-waiting",
title:""},a));a.show();return a},hideNotification:function(a,b){a&&function(){a.el.dom&&a.animHide()}.defer(b||2E3)},onReady:function(a,b){if(this.isReady)a.call(b,this);else this.on("ready",a,b)},onUnload:function(a){this.fireEvent("beforeunload",this)===!1&&a.stopEvent()},doAutoOpen:function(){Ext.get("mixky-loading").remove();Ext.get("mixky-loading-mask").fadeOut({remove:!0});if(Ext.isDefined(this.openParams)){if(Ext.isDefined(this.openParams.modulekey)){var a=this.desktop.openModule(this.openParams.appkey,
this.openParams.modulekey);this.openParams.viewkey&&Ext.isDefined(a)&&a.openView(this.openParams.viewkey)}Ext.isDefined(this.openParams.documentkey)&&Ext.isDefined(this.openParams.documentid)&&Mixky.wasoft.lib.openFavorite(this.openParams.appkey,this.openParams.documentkey,this.openParams.documentid)}},kqqdadd:function(){Ext.MessageBox.show({title:"\u8003\u52e4\u63d0\u793a",msg:"\u4eca\u5929\u662f\u60a8\u7b2c\u4e00\u6b21\u767b\u5f55\u7cfb\u7edf\uff0c\u662f\u5426\u7b7e\u5230\uff1f",modal:!0,buttons:Ext.Msg.YESNO,
icon:Ext.Msg.QUESTION,width:300,closable:!1,fn:function(a){a=="yes"&&KqglDirect.kqgl_qd(function(a){a&&a.success?Ext.MessageBox.show({title:"\u63d0\u793a",msg:a.msg,modal:!0,buttons:Ext.Msg.OK,icon:Ext.Msg.INFO,width:300,closable:!1}):Ext.MessageBox.show({title:"\u63d0\u793a",msg:a.msg,modal:!0,buttons:Ext.Msg.OK,icon:Ext.Msg.ERROR,width:300,closable:!1})})}})},rqwarn:function(){var a=ApplicationInfo.ywrq.split("\uff1a")[1],b=(new Date).format("Y\u5e74m\u6708d\u65e5");a!=b&&Ext.MessageBox.show({title:"\u8b66\u544a",
msg:"\u5f53\u524d\u7cfb\u7edf\u65e5\u671f\u4e0e\u4e1a\u52a1\u65e5\u671f\u4e0d\u4e00\u81f4\uff01",modal:!0,buttons:Ext.Msg.OK,icon:Ext.Msg.WARNING,width:280,closable:!1})}});
