shineyue.fieldConfigs.checkbox = [ {
	name : "name",
	caption : "name",
	orderNum : "1",
	dataType : "string"
}, {
	name : "caption",
	caption : "显示名",
	orderNum : "2",
	dataType : "string"
} , {
	name : "size",
	caption : "size",
	orderNum : "2",
	dataType : "string"
} ,{
	name : "width",
	caption : "宽度",
	orderNum : "2",
	dataType : "string"
} ,{
	name : "height",
	caption : "高度",
	orderNum : "2",
	dataType : "string"
} , {
	name : "maxlength",
	caption : "输入最大长度",
	orderNum : "2",
	dataType : "boolean"
} , {
	name : "minlength",
	caption : "输入最小长度",
	orderNum : "2",
	dataType : "boolean"
} , {
	name : "value",
	caption : "默认值",
	orderNum : "2",
	dataType : "string"
} , {
	name : "readonly",
	caption : "只读",
	orderNum : "2",
	dataType : "string"
} , {
	name : "allowblank",
	caption : "允许为空",
	orderNum : "2",
	dataType : "string"
} , {
	name : "regex",
	caption : "正则表达式",
	orderNum : "2",
	dataType : "string"
} , {
	name : "validateType",
	caption : "验证类型",
	orderNum : "2",
	dataType : "string"
}  ];
