Ext.namespace("Mixky.lib");
Mixky.lib.getEditorConfig=function(c,a){var b={};switch(c){case "boolean":b={xtype:"combo",triggerAction:"all",forceSelection:!1,editable:!1,store:[!1,!0]};break;case "number":b={xtype:"numberfield",style:"text-align:left;",selectOnFocus:!0};break;case "textarea":b={xtype:"textarea",selectOnFocus:!0};break;case "date":b={xtype:"datefield",format:"Y-m-d"};break;case "datetime":b={xtype:"datefield",format:"Y-m-d"};break;case "select":b={xtype:"combo",triggerAction:"all",mode:"local",forceSelection:!1,
store:a.datas};break;case "selectkeymap":b={xtype:"combo",triggerAction:"all",mode:"local",forceSelection:!1,store:new Ext.data.SimpleStore({fields:["value","name"],data:a.datas}),valueField:"value",displayField:"name"};break;case "check":b={xtype:"checkboxgroup",items:a.datas};break;case "radio":b={xtype:"radiogroup",items:a.datas};break;case "jsonobject":b={xtype:"mixkyjsonobjectfield"};break;case "textbox":b={xtype:"mixkytextboxfield"};break;case "organization":b={xtype:"mixkyorganizationfield"};
break;case "designobject":b={xtype:"mixkydesignobjectfield"};break;case "userselector":b={xtype:"trigger",editable:!1,onTriggerClick:function(){var b=this;Mixky.lib.editor.getUserSelector(this.value,function(a){for(var c="",g=0;g<a.length;g++)c=c+a[g].get("expression")+";";b.setValue(c)},a).show()}};break;case "readonly":b={xtype:"textfield",selectOnFocus:!0,readOnly:!0};break;default:b={xtype:"textfield",selectOnFocus:!0}}a&&a.config&&Ext.apply(b,a.config);return b};
Mixky.lib.getEditorComponent=function(c,a){return Ext.ComponentMgr.create(Mixky.lib.getEditorConfig(c,a))};
Mixky.lib.setFieldInitConfig=function(c,a,b){if(Ext.isDefined(a)&&Ext.isDefined(b))switch(c){case "select":case "selectkeymap":a.getStore().removeAll();a.getStore().loadData(b.datas);a.el?a.setEditable(b.readOnly===!1):a.editable=b.readOnly===!1;break;case "textarea":Ext.isDefined(b.height)?a.setHeight(b.height):a.setHeight(60);case "organization":a.selectMulti=Ext.isDefined(b.selectMulti)?b.selectMulti:!0;a.selectType=Ext.isDefined(b.selectType)?b.selectType:"mix";a.valueField=Ext.isDefined(b.valueField)?
b.valueField:"expression";a.displayField=b.displayField?b.displayField:"f_caption";a.valueSeparator=Ext.isDefined(b.valueSeparator)?b.valueSeparator:"";break;case "designobject":a.selectInParent=Ext.isDefined(b.selectInParent)?b.selectInParent:!1,a.mclass=Ext.isDefined(b.mclass)?b.mclass:"",a.parentKey=Ext.isDefined(b.parentKey)?b.parentKey:""}};
Mixky.lib.remoteRenderValue=function(c,a,b,d){(!a||a=="")&&b("",d);switch(c){case "renderUserExpression":Ext.isDefined(d)&&d.valueSeparator&&d.valueSeparator!=""&&(a=a.split(d.valueSeparator));OrganizationDirect.getExpressionDisplay(a,function(a){b(a.display,d)});break;case "renderDesignObject":DesignObjectDirect.loadObject(a.data,function(a){b(a.object.f_caption+" ["+a.object.key+"]",d)})}};
Mixky.lib.remoteRenderStore=function(c){c.fields.each(function(a){if(Ext.isDefined(a.remoteRenderType))for(var b=0;b<c.getCount();b++){var d=c.getAt(b),e=d.get(a.name);if(Ext.isDefined(e)&&e!=""){d={record:d};if(a.remoteRenderType=="renderUserExpression")d.valueSeparator=a.valueSeparator;Mixky.lib.remoteRenderValue(a.remoteRenderType,e,function(b,c){c.record.set(a.name+"_display",b);c.record.commit()},d)}}})};
Mixky.lib.getFieldSelectorWindow=function(c,a){Ext.applyIf(a,{getInitValue:Ext.emptyFn,setValue:Ext.emptyFn,getValue:Ext.emptyFn,onSelectedFn:Ext.emptyFn});Ext.applyIf(c,{modal:!0,width:500,height:300,minWidth:300,minHeight:200,layout:"fit",plain:!0,buttonAlign:"center",buttons:[{text:"\u786e\u5b9a",handler:function(){var b=this.findParentByType("window");a.onSelectedFn(a.getValue())!==!1&&(b.closeAction=="hide"?b.hide():b.close())}},{text:"\u53d6\u6d88",handler:function(){var a=this.findParentByType("window");
a.closeAction=="hide"?a.hide():a.close()}}],listeners:{beforeshow:function(){a.setValue(a.getInitValue())}}});return new Ext.Window(c)};
Mixky.lib.getObjectFormatString=function(c,a,b){var d="",e=typeof a;a instanceof Array&&(e="array");for(var f="",d=0;d<b;d++)f+="\t";d=f;c&&(d=d+c+" : ");switch(e){case "boolean":case "number":d=d+a+",\n";break;case "string":d=d+Ext.encode(a)+",\n";break;case "object":d+="{\n";c=!1;for(n in a)a.hasOwnProperty(n)&&(c=!0,d+=Mixky.lib.getObjectFormatString(n,a[n],b+1));b>0&&c&&(d=d.substring(0,d.length-2)+"\n");d=d+f+"},\n";break;case "array":d+="[\n";c=!1;for(n in a)a.hasOwnProperty(n)&&(c=!0,d+=Mixky.lib.getObjectFormatString(!1,
a[n],b+1));b>0&&c&&(d=d.substring(0,d.length-2)+"\n");d=d+f+"],\n";break;case "function":d=d+"("+a.toString().replace(RegExp("\n","gm"),f+"\n")+"),\n";break;case "undefined":d=d+a+",\n"}return b==0?d.substring(0,d.length-2):d};Mixky.lib.getNewTableRecordId=function(c,a){CommonLibDirect.getNewTableRecordId(c,function(b){b&&b.success&&a(b.id)})};Mixky.lib.showOrganizationWindow=function(){};String.prototype.replaceAll=function(c,a){return this.replace(RegExp(c,"gm"),a)};
Mixky.lib.alertObject=function(c){var a="item is \n",b;for(b in c)a=a+"\t"+b+":"+c[b]+"\n";alert(a)};Mixky.lib.IframeManager={loadUrl:function(c){if(!Mixky.lib.IframeManager.el){var a=document.createElement("iframe");a.setAttribute("width","0px");a.setAttribute("height","0px");Mixky.lib.IframeManager.el=Ext.getBody().appendChild(a)}Mixky.lib.IframeManager.el.dom.src=c}};String.prototype.replaceAll=function(c,a){return this.replace(RegExp(c,"gm"),a)};
Array.prototype.removeAt=function(c){if(isNaN(c)||c>=this.length)return!1;for(;c<this.length-1;c++)this[c]=this[c+1];this.length-=1};
