package physics.app.model;

import com.lyt.pallas.jdbc.model.Entity;

public class BasicUnit extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column BASIC_UNIT.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column BASIC_UNIT.UNIT_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	private String unitName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column BASIC_UNIT.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	private String chineseName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column BASIC_UNIT.SYMBOL
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	private String symbol;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column BASIC_UNIT.COMMENTS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	private String comments;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column BASIC_UNIT.ENGLISH_COMMENT
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	private String englishComment;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column BASIC_UNIT.ID
	 * 
	 * @return the value of BASIC_UNIT.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column BASIC_UNIT.ID
	 * 
	 * @param id
	 *            the value for BASIC_UNIT.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column BASIC_UNIT.UNIT_NAME
	 * 
	 * @return the value of BASIC_UNIT.UNIT_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	public String getUnitName() {
		return unitName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column BASIC_UNIT.UNIT_NAME
	 * 
	 * @param unitName
	 *            the value for BASIC_UNIT.UNIT_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column BASIC_UNIT.CHINESE_NAME
	 * 
	 * @return the value of BASIC_UNIT.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	public String getChineseName() {
		return chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column BASIC_UNIT.CHINESE_NAME
	 * 
	 * @param chineseName
	 *            the value for BASIC_UNIT.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column BASIC_UNIT.SYMBOL
	 * 
	 * @return the value of BASIC_UNIT.SYMBOL
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	public String getSymbol() {
		return symbol;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column BASIC_UNIT.SYMBOL
	 * 
	 * @param symbol
	 *            the value for BASIC_UNIT.SYMBOL
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column BASIC_UNIT.COMMENTS
	 * 
	 * @return the value of BASIC_UNIT.COMMENTS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	public String getComments() {
		return comments;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column BASIC_UNIT.COMMENTS
	 * 
	 * @param comments
	 *            the value for BASIC_UNIT.COMMENTS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column BASIC_UNIT.ENGLISH_COMMENT
	 * 
	 * @return the value of BASIC_UNIT.ENGLISH_COMMENT
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	public String getEnglishComment() {
		return englishComment;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column BASIC_UNIT.ENGLISH_COMMENT
	 * 
	 * @param englishComment
	 *            the value for BASIC_UNIT.ENGLISH_COMMENT
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	public void setEnglishComment(String englishComment) {
		this.englishComment = englishComment;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table BASIC_UNIT
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof BasicUnit)) {
			return false;
		}
		BasicUnit other = (BasicUnit) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getUnitName() == null ? other.getUnitName() == null
						: this.getUnitName().equals(other.getUnitName()))
				&& (this.getChineseName() == null ? other.getChineseName() == null
						: this.getChineseName().equals(other.getChineseName()))
				&& (this.getSymbol() == null ? other.getSymbol() == null : this
						.getSymbol().equals(other.getSymbol()))
				&& (this.getComments() == null ? other.getComments() == null
						: this.getComments().equals(other.getComments()))
				&& (this.getEnglishComment() == null ? other
						.getEnglishComment() == null : this.getEnglishComment()
						.equals(other.getEnglishComment()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table BASIC_UNIT
	 * 
	 * @ibatorgenerated Wed Jul 21 13:45:01 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getUnitName() != null) {
			hash *= getUnitName().hashCode();
		}
		if (getChineseName() != null) {
			hash *= getChineseName().hashCode();
		}
		if (getSymbol() != null) {
			hash *= getSymbol().hashCode();
		}
		if (getComments() != null) {
			hash *= getComments().hashCode();
		}
		if (getEnglishComment() != null) {
			hash *= getEnglishComment().hashCode();
		}
		return hash;
	}
}