package physics.app.model;

import java.math.BigDecimal;

import com.lyt.pallas.jdbc.model.Entity;

public class ElectroMagnetSpectrum extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column ELECTRO_MAGNET_SPECTRUM.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column ELECTRO_MAGNET_SPECTRUM.MIN_WAVE_LENGTH
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	private BigDecimal minWaveLength;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column ELECTRO_MAGNET_SPECTRUM.MAX_WAVE_LENGTH
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	private BigDecimal maxWaveLength;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column ELECTRO_MAGNET_SPECTRUM.WAVE_LENGTH_UNIT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	private Long waveLengthUnitId;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column ELECTRO_MAGNET_SPECTRUM.ENGLISH_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	private String englishName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column ELECTRO_MAGNET_SPECTRUM.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	private String chineseName;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column ELECTRO_MAGNET_SPECTRUM.ID
	 * 
	 * @return the value of ELECTRO_MAGNET_SPECTRUM.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column ELECTRO_MAGNET_SPECTRUM.ID
	 * 
	 * @param id
	 *            the value for ELECTRO_MAGNET_SPECTRUM.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column ELECTRO_MAGNET_SPECTRUM.MIN_WAVE_LENGTH
	 * 
	 * @return the value of ELECTRO_MAGNET_SPECTRUM.MIN_WAVE_LENGTH
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	public BigDecimal getMinWaveLength() {
		return minWaveLength;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column ELECTRO_MAGNET_SPECTRUM.MIN_WAVE_LENGTH
	 * 
	 * @param minWaveLength
	 *            the value for ELECTRO_MAGNET_SPECTRUM.MIN_WAVE_LENGTH
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	public void setMinWaveLength(BigDecimal minWaveLength) {
		this.minWaveLength = minWaveLength;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column ELECTRO_MAGNET_SPECTRUM.MAX_WAVE_LENGTH
	 * 
	 * @return the value of ELECTRO_MAGNET_SPECTRUM.MAX_WAVE_LENGTH
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	public BigDecimal getMaxWaveLength() {
		return maxWaveLength;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column ELECTRO_MAGNET_SPECTRUM.MAX_WAVE_LENGTH
	 * 
	 * @param maxWaveLength
	 *            the value for ELECTRO_MAGNET_SPECTRUM.MAX_WAVE_LENGTH
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	public void setMaxWaveLength(BigDecimal maxWaveLength) {
		this.maxWaveLength = maxWaveLength;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column
	 * ELECTRO_MAGNET_SPECTRUM.WAVE_LENGTH_UNIT_ID
	 * 
	 * @return the value of ELECTRO_MAGNET_SPECTRUM.WAVE_LENGTH_UNIT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	public Long getWaveLengthUnitId() {
		return waveLengthUnitId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column ELECTRO_MAGNET_SPECTRUM.WAVE_LENGTH_UNIT_ID
	 * 
	 * @param waveLengthUnitId
	 *            the value for ELECTRO_MAGNET_SPECTRUM.WAVE_LENGTH_UNIT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	public void setWaveLengthUnitId(Long waveLengthUnitId) {
		this.waveLengthUnitId = waveLengthUnitId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column ELECTRO_MAGNET_SPECTRUM.ENGLISH_NAME
	 * 
	 * @return the value of ELECTRO_MAGNET_SPECTRUM.ENGLISH_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	public String getEnglishName() {
		return englishName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column ELECTRO_MAGNET_SPECTRUM.ENGLISH_NAME
	 * 
	 * @param englishName
	 *            the value for ELECTRO_MAGNET_SPECTRUM.ENGLISH_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column ELECTRO_MAGNET_SPECTRUM.CHINESE_NAME
	 * 
	 * @return the value of ELECTRO_MAGNET_SPECTRUM.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	public String getChineseName() {
		return chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column ELECTRO_MAGNET_SPECTRUM.CHINESE_NAME
	 * 
	 * @param chineseName
	 *            the value for ELECTRO_MAGNET_SPECTRUM.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table ELECTRO_MAGNET_SPECTRUM
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof ElectroMagnetSpectrum)) {
			return false;
		}
		ElectroMagnetSpectrum other = (ElectroMagnetSpectrum) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getMinWaveLength() == null ? other.getMinWaveLength() == null
						: this.getMinWaveLength().equals(
								other.getMinWaveLength()))
				&& (this.getMaxWaveLength() == null ? other.getMaxWaveLength() == null
						: this.getMaxWaveLength().equals(
								other.getMaxWaveLength()))
				&& (this.getWaveLengthUnitId() == null ? other
						.getWaveLengthUnitId() == null : this
						.getWaveLengthUnitId().equals(
								other.getWaveLengthUnitId()))
				&& (this.getEnglishName() == null ? other.getEnglishName() == null
						: this.getEnglishName().equals(other.getEnglishName()))
				&& (this.getChineseName() == null ? other.getChineseName() == null
						: this.getChineseName().equals(other.getChineseName()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table ELECTRO_MAGNET_SPECTRUM
	 * 
	 * @ibatorgenerated Wed Jul 21 13:42:06 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getMinWaveLength() != null) {
			hash *= getMinWaveLength().hashCode();
		}
		if (getMaxWaveLength() != null) {
			hash *= getMaxWaveLength().hashCode();
		}
		if (getWaveLengthUnitId() != null) {
			hash *= getWaveLengthUnitId().hashCode();
		}
		if (getEnglishName() != null) {
			hash *= getEnglishName().hashCode();
		}
		if (getChineseName() != null) {
			hash *= getChineseName().hashCode();
		}
		return hash;
	}
}