package physics.app.model;

import java.math.BigDecimal;

import com.lyt.pallas.jdbc.model.Entity;

public class FundamentalConstants extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column FUNDAMENTAL_CONSTANTS.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column FUNDAMENTAL_CONSTANTS.ENGLISH_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	private String englishName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column FUNDAMENTAL_CONSTANTS.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	private String chineseName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column FUNDAMENTAL_CONSTANTS.SYMBOL
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	private String symbol;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column FUNDAMENTAL_CONSTANTS.EXPRESSION
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	private String expression;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column FUNDAMENTAL_CONSTANTS.VALUE_IN_S_I_UNITS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	private BigDecimal valueInSIUnits;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column FUNDAMENTAL_CONSTANTS.ERROR
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	private BigDecimal error;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column FUNDAMENTAL_CONSTANTS.UNIT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	private Long unitId;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column FUNDAMENTAL_CONSTANTS.ID
	 * 
	 * @return the value of FUNDAMENTAL_CONSTANTS.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column FUNDAMENTAL_CONSTANTS.ID
	 * 
	 * @param id
	 *            the value for FUNDAMENTAL_CONSTANTS.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column FUNDAMENTAL_CONSTANTS.ENGLISH_NAME
	 * 
	 * @return the value of FUNDAMENTAL_CONSTANTS.ENGLISH_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public String getEnglishName() {
		return englishName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column FUNDAMENTAL_CONSTANTS.ENGLISH_NAME
	 * 
	 * @param englishName
	 *            the value for FUNDAMENTAL_CONSTANTS.ENGLISH_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column FUNDAMENTAL_CONSTANTS.CHINESE_NAME
	 * 
	 * @return the value of FUNDAMENTAL_CONSTANTS.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public String getChineseName() {
		return chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column FUNDAMENTAL_CONSTANTS.CHINESE_NAME
	 * 
	 * @param chineseName
	 *            the value for FUNDAMENTAL_CONSTANTS.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column FUNDAMENTAL_CONSTANTS.SYMBOL
	 * 
	 * @return the value of FUNDAMENTAL_CONSTANTS.SYMBOL
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public String getSymbol() {
		return symbol;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column FUNDAMENTAL_CONSTANTS.SYMBOL
	 * 
	 * @param symbol
	 *            the value for FUNDAMENTAL_CONSTANTS.SYMBOL
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column FUNDAMENTAL_CONSTANTS.EXPRESSION
	 * 
	 * @return the value of FUNDAMENTAL_CONSTANTS.EXPRESSION
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public String getExpression() {
		return expression;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column FUNDAMENTAL_CONSTANTS.EXPRESSION
	 * 
	 * @param expression
	 *            the value for FUNDAMENTAL_CONSTANTS.EXPRESSION
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public void setExpression(String expression) {
		this.expression = expression;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column FUNDAMENTAL_CONSTANTS.VALUE_IN_S_I_UNITS
	 * 
	 * @return the value of FUNDAMENTAL_CONSTANTS.VALUE_IN_S_I_UNITS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public BigDecimal getValueInSIUnits() {
		return valueInSIUnits;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column FUNDAMENTAL_CONSTANTS.VALUE_IN_S_I_UNITS
	 * 
	 * @param valueInSIUnits
	 *            the value for FUNDAMENTAL_CONSTANTS.VALUE_IN_S_I_UNITS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public void setValueInSIUnits(BigDecimal valueInSIUnits) {
		this.valueInSIUnits = valueInSIUnits;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column FUNDAMENTAL_CONSTANTS.ERROR
	 * 
	 * @return the value of FUNDAMENTAL_CONSTANTS.ERROR
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public BigDecimal getError() {
		return error;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column FUNDAMENTAL_CONSTANTS.ERROR
	 * 
	 * @param error
	 *            the value for FUNDAMENTAL_CONSTANTS.ERROR
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public void setError(BigDecimal error) {
		this.error = error;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column FUNDAMENTAL_CONSTANTS.UNIT_ID
	 * 
	 * @return the value of FUNDAMENTAL_CONSTANTS.UNIT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public Long getUnitId() {
		return unitId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column FUNDAMENTAL_CONSTANTS.UNIT_ID
	 * 
	 * @param unitId
	 *            the value for FUNDAMENTAL_CONSTANTS.UNIT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	public void setUnitId(Long unitId) {
		this.unitId = unitId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table FUNDAMENTAL_CONSTANTS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof FundamentalConstants)) {
			return false;
		}
		FundamentalConstants other = (FundamentalConstants) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getEnglishName() == null ? other.getEnglishName() == null
						: this.getEnglishName().equals(other.getEnglishName()))
				&& (this.getChineseName() == null ? other.getChineseName() == null
						: this.getChineseName().equals(other.getChineseName()))
				&& (this.getSymbol() == null ? other.getSymbol() == null : this
						.getSymbol().equals(other.getSymbol()))
				&& (this.getExpression() == null ? other.getExpression() == null
						: this.getExpression().equals(other.getExpression()))
				&& (this.getValueInSIUnits() == null ? other
						.getValueInSIUnits() == null : this.getValueInSIUnits()
						.equals(other.getValueInSIUnits()))
				&& (this.getError() == null ? other.getError() == null : this
						.getError().equals(other.getError()))
				&& (this.getUnitId() == null ? other.getUnitId() == null : this
						.getUnitId().equals(other.getUnitId()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table FUNDAMENTAL_CONSTANTS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:24:43 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getEnglishName() != null) {
			hash *= getEnglishName().hashCode();
		}
		if (getChineseName() != null) {
			hash *= getChineseName().hashCode();
		}
		if (getSymbol() != null) {
			hash *= getSymbol().hashCode();
		}
		if (getExpression() != null) {
			hash *= getExpression().hashCode();
		}
		if (getValueInSIUnits() != null) {
			hash *= getValueInSIUnits().hashCode();
		}
		if (getError() != null) {
			hash *= getError().hashCode();
		}
		if (getUnitId() != null) {
			hash *= getUnitId().hashCode();
		}
		return hash;
	}
}