package physics.app.model;

import com.lyt.pallas.jdbc.model.Entity;

public class GreekAlphabet extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column GREEK_ALPHABET.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:26:55 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column GREEK_ALPHABET.LETTER
	 * 
	 * @ibatorgenerated Wed Jul 21 13:26:55 CST 2010
	 */
	private String letter;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column GREEK_ALPHABET.NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:26:55 CST 2010
	 */
	private String name;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column GREEK_ALPHABET.ISBIG
	 * 
	 * @ibatorgenerated Wed Jul 21 13:26:55 CST 2010
	 */
	private Long isbig;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column GREEK_ALPHABET.ID
	 * 
	 * @return the value of GREEK_ALPHABET.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:26:55 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column GREEK_ALPHABET.ID
	 * 
	 * @param id
	 *            the value for GREEK_ALPHABET.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:26:55 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column GREEK_ALPHABET.LETTER
	 * 
	 * @return the value of GREEK_ALPHABET.LETTER
	 * 
	 * @ibatorgenerated Wed Jul 21 13:26:55 CST 2010
	 */
	public String getLetter() {
		return letter;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column GREEK_ALPHABET.LETTER
	 * 
	 * @param letter
	 *            the value for GREEK_ALPHABET.LETTER
	 * 
	 * @ibatorgenerated Wed Jul 21 13:26:55 CST 2010
	 */
	public void setLetter(String letter) {
		this.letter = letter;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column GREEK_ALPHABET.NAME
	 * 
	 * @return the value of GREEK_ALPHABET.NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:26:55 CST 2010
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column GREEK_ALPHABET.NAME
	 * 
	 * @param name
	 *            the value for GREEK_ALPHABET.NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:26:55 CST 2010
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column GREEK_ALPHABET.ISBIG
	 * 
	 * @return the value of GREEK_ALPHABET.ISBIG
	 * 
	 * @ibatorgenerated Wed Jul 21 13:26:55 CST 2010
	 */
	public Long getIsbig() {
		return isbig;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column GREEK_ALPHABET.ISBIG
	 * 
	 * @param isbig
	 *            the value for GREEK_ALPHABET.ISBIG
	 * 
	 * @ibatorgenerated Wed Jul 21 13:26:55 CST 2010
	 */
	public void setIsbig(Long isbig) {
		this.isbig = isbig;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table GREEK_ALPHABET
	 * 
	 * @ibatorgenerated Wed Jul 21 13:26:55 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof GreekAlphabet)) {
			return false;
		}
		GreekAlphabet other = (GreekAlphabet) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getLetter() == null ? other.getLetter() == null : this
						.getLetter().equals(other.getLetter()))
				&& (this.getName() == null ? other.getName() == null : this
						.getName().equals(other.getName()))
				&& (this.getIsbig() == null ? other.getIsbig() == null : this
						.getIsbig().equals(other.getIsbig()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table GREEK_ALPHABET
	 * 
	 * @ibatorgenerated Wed Jul 21 13:26:55 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getLetter() != null) {
			hash *= getLetter().hashCode();
		}
		if (getName() != null) {
			hash *= getName().hashCode();
		}
		if (getIsbig() != null) {
			hash *= getIsbig().hashCode();
		}
		return hash;
	}
}