package physics.app.model;

import com.lyt.pallas.jdbc.model.Entity;

public class ManageUsers extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_USERS.ID
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_USERS.USERNAME
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	private String username;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_USERS.PASSWORD
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	private String password;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_USERS.CHINESE_NAME
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	private String chineseName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_USERS.USED
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	private String used;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_USERS.ID
	 * 
	 * @return the value of MANAGE_USERS.ID
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_USERS.ID
	 * 
	 * @param id
	 *            the value for MANAGE_USERS.ID
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_USERS.USERNAME
	 * 
	 * @return the value of MANAGE_USERS.USERNAME
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_USERS.USERNAME
	 * 
	 * @param username
	 *            the value for MANAGE_USERS.USERNAME
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_USERS.PASSWORD
	 * 
	 * @return the value of MANAGE_USERS.PASSWORD
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_USERS.PASSWORD
	 * 
	 * @param password
	 *            the value for MANAGE_USERS.PASSWORD
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_USERS.CHINESE_NAME
	 * 
	 * @return the value of MANAGE_USERS.CHINESE_NAME
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	public String getChineseName() {
		return chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_USERS.CHINESE_NAME
	 * 
	 * @param chineseName
	 *            the value for MANAGE_USERS.CHINESE_NAME
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_USERS.USED
	 * 
	 * @return the value of MANAGE_USERS.USED
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	public String getUsed() {
		return used;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_USERS.USED
	 * 
	 * @param used
	 *            the value for MANAGE_USERS.USED
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	public void setUsed(String used) {
		this.used = used;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table MANAGE_USERS
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof ManageUsers)) {
			return false;
		}
		ManageUsers other = (ManageUsers) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getUsername() == null ? other.getUsername() == null
						: this.getUsername().equals(other.getUsername()))
				&& (this.getPassword() == null ? other.getPassword() == null
						: this.getPassword().equals(other.getPassword()))
				&& (this.getChineseName() == null ? other.getChineseName() == null
						: this.getChineseName().equals(other.getChineseName()))
				&& (this.getUsed() == null ? other.getUsed() == null : this
						.getUsed().equals(other.getUsed()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table MANAGE_USERS
	 * 
	 * @ibatorgenerated Tue Jul 27 21:47:33 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getUsername() != null) {
			hash *= getUsername().hashCode();
		}
		if (getPassword() != null) {
			hash *= getPassword().hashCode();
		}
		if (getChineseName() != null) {
			hash *= getChineseName().hashCode();
		}
		if (getUsed() != null) {
			hash *= getUsed().hashCode();
		}
		return hash;
	}
}