package physics.app.model;

import com.lyt.pallas.jdbc.model.Entity;

public class ManageRefUsersRoles extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_REF_USERS_ROLES.ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:03:29 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_REF_USERS_ROLES.ROLES_ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:03:29 CST 2010
	 */
	private Long rolesId;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_REF_USERS_ROLES.USERS_ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:03:29 CST 2010
	 */
	private Long usersId;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_REF_USERS_ROLES.ID
	 * 
	 * @return the value of MANAGE_REF_USERS_ROLES.ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:03:29 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_REF_USERS_ROLES.ID
	 * 
	 * @param id
	 *            the value for MANAGE_REF_USERS_ROLES.ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:03:29 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_REF_USERS_ROLES.ROLES_ID
	 * 
	 * @return the value of MANAGE_REF_USERS_ROLES.ROLES_ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:03:29 CST 2010
	 */
	public Long getRolesId() {
		return rolesId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_REF_USERS_ROLES.ROLES_ID
	 * 
	 * @param rolesId
	 *            the value for MANAGE_REF_USERS_ROLES.ROLES_ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:03:29 CST 2010
	 */
	public void setRolesId(Long rolesId) {
		this.rolesId = rolesId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_REF_USERS_ROLES.USERS_ID
	 * 
	 * @return the value of MANAGE_REF_USERS_ROLES.USERS_ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:03:29 CST 2010
	 */
	public Long getUsersId() {
		return usersId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_REF_USERS_ROLES.USERS_ID
	 * 
	 * @param usersId
	 *            the value for MANAGE_REF_USERS_ROLES.USERS_ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:03:29 CST 2010
	 */
	public void setUsersId(Long usersId) {
		this.usersId = usersId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table MANAGE_REF_USERS_ROLES
	 * 
	 * @ibatorgenerated Thu Jul 22 17:03:29 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof ManageRefUsersRoles)) {
			return false;
		}
		ManageRefUsersRoles other = (ManageRefUsersRoles) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getRolesId() == null ? other.getRolesId() == null
						: this.getRolesId().equals(other.getRolesId()))
				&& (this.getUsersId() == null ? other.getUsersId() == null
						: this.getUsersId().equals(other.getUsersId()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table MANAGE_REF_USERS_ROLES
	 * 
	 * @ibatorgenerated Thu Jul 22 17:03:29 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getRolesId() != null) {
			hash *= getRolesId().hashCode();
		}
		if (getUsersId() != null) {
			hash *= getUsersId().hashCode();
		}
		return hash;
	}
}