package physics.app.model;

import com.lyt.pallas.jdbc.model.Entity;

public class ManageResourcesType extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_RESOURCES_TYPE.ID
	 * 
	 * @ibatorgenerated Thu Jul 22 22:08:04 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_RESOURCES_TYPE.NAME
	 * 
	 * @ibatorgenerated Thu Jul 22 22:08:04 CST 2010
	 */
	private String name;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_RESOURCES_TYPE.CHINESE_NAME
	 * 
	 * @ibatorgenerated Thu Jul 22 22:08:04 CST 2010
	 */
	private String chineseName;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_RESOURCES_TYPE.ID
	 * 
	 * @return the value of MANAGE_RESOURCES_TYPE.ID
	 * 
	 * @ibatorgenerated Thu Jul 22 22:08:04 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_RESOURCES_TYPE.ID
	 * 
	 * @param id
	 *            the value for MANAGE_RESOURCES_TYPE.ID
	 * 
	 * @ibatorgenerated Thu Jul 22 22:08:04 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_RESOURCES_TYPE.NAME
	 * 
	 * @return the value of MANAGE_RESOURCES_TYPE.NAME
	 * 
	 * @ibatorgenerated Thu Jul 22 22:08:04 CST 2010
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_RESOURCES_TYPE.NAME
	 * 
	 * @param name
	 *            the value for MANAGE_RESOURCES_TYPE.NAME
	 * 
	 * @ibatorgenerated Thu Jul 22 22:08:04 CST 2010
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_RESOURCES_TYPE.CHINESE_NAME
	 * 
	 * @return the value of MANAGE_RESOURCES_TYPE.CHINESE_NAME
	 * 
	 * @ibatorgenerated Thu Jul 22 22:08:04 CST 2010
	 */
	public String getChineseName() {
		return chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_RESOURCES_TYPE.CHINESE_NAME
	 * 
	 * @param chineseName
	 *            the value for MANAGE_RESOURCES_TYPE.CHINESE_NAME
	 * 
	 * @ibatorgenerated Thu Jul 22 22:08:04 CST 2010
	 */
	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table MANAGE_RESOURCES_TYPE
	 * 
	 * @ibatorgenerated Thu Jul 22 22:08:04 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof ManageResourcesType)) {
			return false;
		}
		ManageResourcesType other = (ManageResourcesType) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getName() == null ? other.getName() == null : this
						.getName().equals(other.getName()))
				&& (this.getChineseName() == null ? other.getChineseName() == null
						: this.getChineseName().equals(other.getChineseName()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table MANAGE_RESOURCES_TYPE
	 * 
	 * @ibatorgenerated Thu Jul 22 22:08:04 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getName() != null) {
			hash *= getName().hashCode();
		}
		if (getChineseName() != null) {
			hash *= getChineseName().hashCode();
		}
		return hash;
	}
}