package physics.app.model;

import com.lyt.pallas.jdbc.model.Entity;

public class ManageGrant extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_GRANT.ID
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_GRANT.GRANT_NAME
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	private String grantName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_GRANT.CHINESE_NAME
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	private String chineseName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_GRANT.DESCRIPTION
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	private String description;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_GRANT.USED
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	private String used;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_GRANT.ID
	 * 
	 * @return the value of MANAGE_GRANT.ID
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_GRANT.ID
	 * 
	 * @param id
	 *            the value for MANAGE_GRANT.ID
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_GRANT.GRANT_NAME
	 * 
	 * @return the value of MANAGE_GRANT.GRANT_NAME
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	public String getGrantName() {
		return grantName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_GRANT.GRANT_NAME
	 * 
	 * @param grantName
	 *            the value for MANAGE_GRANT.GRANT_NAME
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	public void setGrantName(String grantName) {
		this.grantName = grantName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_GRANT.CHINESE_NAME
	 * 
	 * @return the value of MANAGE_GRANT.CHINESE_NAME
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	public String getChineseName() {
		return chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_GRANT.CHINESE_NAME
	 * 
	 * @param chineseName
	 *            the value for MANAGE_GRANT.CHINESE_NAME
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_GRANT.DESCRIPTION
	 * 
	 * @return the value of MANAGE_GRANT.DESCRIPTION
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_GRANT.DESCRIPTION
	 * 
	 * @param description
	 *            the value for MANAGE_GRANT.DESCRIPTION
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_GRANT.USED
	 * 
	 * @return the value of MANAGE_GRANT.USED
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	public String getUsed() {
		return used;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_GRANT.USED
	 * 
	 * @param used
	 *            the value for MANAGE_GRANT.USED
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	public void setUsed(String used) {
		this.used = used;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table MANAGE_GRANT
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof ManageGrant)) {
			return false;
		}
		ManageGrant other = (ManageGrant) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getGrantName() == null ? other.getGrantName() == null
						: this.getGrantName().equals(other.getGrantName()))
				&& (this.getChineseName() == null ? other.getChineseName() == null
						: this.getChineseName().equals(other.getChineseName()))
				&& (this.getDescription() == null ? other.getDescription() == null
						: this.getDescription().equals(other.getDescription()))
				&& (this.getUsed() == null ? other.getUsed() == null : this
						.getUsed().equals(other.getUsed()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table MANAGE_GRANT
	 * 
	 * @ibatorgenerated Tue Jul 27 21:16:31 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getGrantName() != null) {
			hash *= getGrantName().hashCode();
		}
		if (getChineseName() != null) {
			hash *= getChineseName().hashCode();
		}
		if (getDescription() != null) {
			hash *= getDescription().hashCode();
		}
		if (getUsed() != null) {
			hash *= getUsed().hashCode();
		}
		return hash;
	}
}