package physics.app.model;

import com.lyt.pallas.jdbc.model.Entity;

public class ManageRefResourcesGrant extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_REF_RESOURCES_GRANT.ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:02:02 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_REF_RESOURCES_GRANT.GRANT_ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:02:02 CST 2010
	 */
	private Long grantId;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MANAGE_REF_RESOURCES_GRANT.RESOURCES_ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:02:02 CST 2010
	 */
	private Long resourcesId;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_REF_RESOURCES_GRANT.ID
	 * 
	 * @return the value of MANAGE_REF_RESOURCES_GRANT.ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:02:02 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_REF_RESOURCES_GRANT.ID
	 * 
	 * @param id
	 *            the value for MANAGE_REF_RESOURCES_GRANT.ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:02:02 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_REF_RESOURCES_GRANT.GRANT_ID
	 * 
	 * @return the value of MANAGE_REF_RESOURCES_GRANT.GRANT_ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:02:02 CST 2010
	 */
	public Long getGrantId() {
		return grantId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_REF_RESOURCES_GRANT.GRANT_ID
	 * 
	 * @param grantId
	 *            the value for MANAGE_REF_RESOURCES_GRANT.GRANT_ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:02:02 CST 2010
	 */
	public void setGrantId(Long grantId) {
		this.grantId = grantId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MANAGE_REF_RESOURCES_GRANT.RESOURCES_ID
	 * 
	 * @return the value of MANAGE_REF_RESOURCES_GRANT.RESOURCES_ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:02:02 CST 2010
	 */
	public Long getResourcesId() {
		return resourcesId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MANAGE_REF_RESOURCES_GRANT.RESOURCES_ID
	 * 
	 * @param resourcesId
	 *            the value for MANAGE_REF_RESOURCES_GRANT.RESOURCES_ID
	 * 
	 * @ibatorgenerated Thu Jul 22 17:02:02 CST 2010
	 */
	public void setResourcesId(Long resourcesId) {
		this.resourcesId = resourcesId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table MANAGE_REF_RESOURCES_GRANT
	 * 
	 * @ibatorgenerated Thu Jul 22 17:02:02 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof ManageRefResourcesGrant)) {
			return false;
		}
		ManageRefResourcesGrant other = (ManageRefResourcesGrant) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getGrantId() == null ? other.getGrantId() == null
						: this.getGrantId().equals(other.getGrantId()))
				&& (this.getResourcesId() == null ? other.getResourcesId() == null
						: this.getResourcesId().equals(other.getResourcesId()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table MANAGE_REF_RESOURCES_GRANT
	 * 
	 * @ibatorgenerated Thu Jul 22 17:02:02 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getGrantId() != null) {
			hash *= getGrantId().hashCode();
		}
		if (getResourcesId() != null) {
			hash *= getResourcesId().hashCode();
		}
		return hash;
	}
}