package physics.app.model;

import com.lyt.pallas.jdbc.model.Entity;

public class MenuItem extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.PARENT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private Long parentId;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.FULL_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private String fullName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private String name;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.URL
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private String url;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.IS_ENABLE
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private Long isEnable;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.DESCRIPTION
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private String description;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.VERION
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private Long verion;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.IS_HIDDEN
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private Long isHidden;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.PROCESS_DEF_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private String processDefName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.ICON_CSS_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private String iconCssName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.TAB_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private String tabName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.CASE_TYPE
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private String caseType;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.IN_CASE_STATE
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private String inCaseState;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.DISPLAY_ORDER
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private Long displayOrder;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.CONDITION_STR
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private String conditionStr;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column MENU_ITEM.IS_LEAF
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	private Long isLeaf;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.ID
	 * 
	 * @return the value of MENU_ITEM.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.ID
	 * 
	 * @param id
	 *            the value for MENU_ITEM.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.PARENT_ID
	 * 
	 * @return the value of MENU_ITEM.PARENT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public Long getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.PARENT_ID
	 * 
	 * @param parentId
	 *            the value for MENU_ITEM.PARENT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.FULL_NAME
	 * 
	 * @return the value of MENU_ITEM.FULL_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public String getFullName() {
		return fullName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.FULL_NAME
	 * 
	 * @param fullName
	 *            the value for MENU_ITEM.FULL_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.NAME
	 * 
	 * @return the value of MENU_ITEM.NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.NAME
	 * 
	 * @param name
	 *            the value for MENU_ITEM.NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.URL
	 * 
	 * @return the value of MENU_ITEM.URL
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.URL
	 * 
	 * @param url
	 *            the value for MENU_ITEM.URL
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.IS_ENABLE
	 * 
	 * @return the value of MENU_ITEM.IS_ENABLE
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public Long getIsEnable() {
		return isEnable;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.IS_ENABLE
	 * 
	 * @param isEnable
	 *            the value for MENU_ITEM.IS_ENABLE
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setIsEnable(Long isEnable) {
		this.isEnable = isEnable;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.DESCRIPTION
	 * 
	 * @return the value of MENU_ITEM.DESCRIPTION
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.DESCRIPTION
	 * 
	 * @param description
	 *            the value for MENU_ITEM.DESCRIPTION
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.VERION
	 * 
	 * @return the value of MENU_ITEM.VERION
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public Long getVerion() {
		return verion;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.VERION
	 * 
	 * @param verion
	 *            the value for MENU_ITEM.VERION
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setVerion(Long verion) {
		this.verion = verion;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.IS_HIDDEN
	 * 
	 * @return the value of MENU_ITEM.IS_HIDDEN
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public Long getIsHidden() {
		return isHidden;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.IS_HIDDEN
	 * 
	 * @param isHidden
	 *            the value for MENU_ITEM.IS_HIDDEN
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setIsHidden(Long isHidden) {
		this.isHidden = isHidden;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.PROCESS_DEF_NAME
	 * 
	 * @return the value of MENU_ITEM.PROCESS_DEF_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public String getProcessDefName() {
		return processDefName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.PROCESS_DEF_NAME
	 * 
	 * @param processDefName
	 *            the value for MENU_ITEM.PROCESS_DEF_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setProcessDefName(String processDefName) {
		this.processDefName = processDefName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.ICON_CSS_NAME
	 * 
	 * @return the value of MENU_ITEM.ICON_CSS_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public String getIconCssName() {
		return iconCssName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.ICON_CSS_NAME
	 * 
	 * @param iconCssName
	 *            the value for MENU_ITEM.ICON_CSS_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setIconCssName(String iconCssName) {
		this.iconCssName = iconCssName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.TAB_NAME
	 * 
	 * @return the value of MENU_ITEM.TAB_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public String getTabName() {
		return tabName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.TAB_NAME
	 * 
	 * @param tabName
	 *            the value for MENU_ITEM.TAB_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setTabName(String tabName) {
		this.tabName = tabName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.CASE_TYPE
	 * 
	 * @return the value of MENU_ITEM.CASE_TYPE
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public String getCaseType() {
		return caseType;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.CASE_TYPE
	 * 
	 * @param caseType
	 *            the value for MENU_ITEM.CASE_TYPE
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setCaseType(String caseType) {
		this.caseType = caseType;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.IN_CASE_STATE
	 * 
	 * @return the value of MENU_ITEM.IN_CASE_STATE
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public String getInCaseState() {
		return inCaseState;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.IN_CASE_STATE
	 * 
	 * @param inCaseState
	 *            the value for MENU_ITEM.IN_CASE_STATE
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setInCaseState(String inCaseState) {
		this.inCaseState = inCaseState;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.DISPLAY_ORDER
	 * 
	 * @return the value of MENU_ITEM.DISPLAY_ORDER
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public Long getDisplayOrder() {
		return displayOrder;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.DISPLAY_ORDER
	 * 
	 * @param displayOrder
	 *            the value for MENU_ITEM.DISPLAY_ORDER
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setDisplayOrder(Long displayOrder) {
		this.displayOrder = displayOrder;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.CONDITION_STR
	 * 
	 * @return the value of MENU_ITEM.CONDITION_STR
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public String getConditionStr() {
		return conditionStr;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.CONDITION_STR
	 * 
	 * @param conditionStr
	 *            the value for MENU_ITEM.CONDITION_STR
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setConditionStr(String conditionStr) {
		this.conditionStr = conditionStr;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column MENU_ITEM.IS_LEAF
	 * 
	 * @return the value of MENU_ITEM.IS_LEAF
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public Long getIsLeaf() {
		return isLeaf;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column MENU_ITEM.IS_LEAF
	 * 
	 * @param isLeaf
	 *            the value for MENU_ITEM.IS_LEAF
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	public void setIsLeaf(Long isLeaf) {
		this.isLeaf = isLeaf;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table MENU_ITEM
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof MenuItem)) {
			return false;
		}
		MenuItem other = (MenuItem) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getParentId() == null ? other.getParentId() == null
						: this.getParentId().equals(other.getParentId()))
				&& (this.getFullName() == null ? other.getFullName() == null
						: this.getFullName().equals(other.getFullName()))
				&& (this.getName() == null ? other.getName() == null : this
						.getName().equals(other.getName()))
				&& (this.getUrl() == null ? other.getUrl() == null : this
						.getUrl().equals(other.getUrl()))
				&& (this.getIsEnable() == null ? other.getIsEnable() == null
						: this.getIsEnable().equals(other.getIsEnable()))
				&& (this.getDescription() == null ? other.getDescription() == null
						: this.getDescription().equals(other.getDescription()))
				&& (this.getVerion() == null ? other.getVerion() == null : this
						.getVerion().equals(other.getVerion()))
				&& (this.getIsHidden() == null ? other.getIsHidden() == null
						: this.getIsHidden().equals(other.getIsHidden()))
				&& (this.getProcessDefName() == null ? other
						.getProcessDefName() == null : this.getProcessDefName()
						.equals(other.getProcessDefName()))
				&& (this.getIconCssName() == null ? other.getIconCssName() == null
						: this.getIconCssName().equals(other.getIconCssName()))
				&& (this.getTabName() == null ? other.getTabName() == null
						: this.getTabName().equals(other.getTabName()))
				&& (this.getCaseType() == null ? other.getCaseType() == null
						: this.getCaseType().equals(other.getCaseType()))
				&& (this.getInCaseState() == null ? other.getInCaseState() == null
						: this.getInCaseState().equals(other.getInCaseState()))
				&& (this.getDisplayOrder() == null ? other.getDisplayOrder() == null
						: this.getDisplayOrder()
								.equals(other.getDisplayOrder()))
				&& (this.getConditionStr() == null ? other.getConditionStr() == null
						: this.getConditionStr()
								.equals(other.getConditionStr()))
				&& (this.getIsLeaf() == null ? other.getIsLeaf() == null : this
						.getIsLeaf().equals(other.getIsLeaf()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table MENU_ITEM
	 * 
	 * @ibatorgenerated Wed Jul 21 13:35:03 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getParentId() != null) {
			hash *= getParentId().hashCode();
		}
		if (getFullName() != null) {
			hash *= getFullName().hashCode();
		}
		if (getName() != null) {
			hash *= getName().hashCode();
		}
		if (getUrl() != null) {
			hash *= getUrl().hashCode();
		}
		if (getIsEnable() != null) {
			hash *= getIsEnable().hashCode();
		}
		if (getDescription() != null) {
			hash *= getDescription().hashCode();
		}
		if (getVerion() != null) {
			hash *= getVerion().hashCode();
		}
		if (getIsHidden() != null) {
			hash *= getIsHidden().hashCode();
		}
		if (getProcessDefName() != null) {
			hash *= getProcessDefName().hashCode();
		}
		if (getIconCssName() != null) {
			hash *= getIconCssName().hashCode();
		}
		if (getTabName() != null) {
			hash *= getTabName().hashCode();
		}
		if (getCaseType() != null) {
			hash *= getCaseType().hashCode();
		}
		if (getInCaseState() != null) {
			hash *= getInCaseState().hashCode();
		}
		if (getDisplayOrder() != null) {
			hash *= getDisplayOrder().hashCode();
		}
		if (getConditionStr() != null) {
			hash *= getConditionStr().hashCode();
		}
		if (getIsLeaf() != null) {
			hash *= getIsLeaf().hashCode();
		}
		return hash;
	}
}