package physics.app.model;

import com.lyt.pallas.jdbc.model.Entity;

public class PhysicalVariable extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column PHYSICAL_VARIABLE.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column PHYSICAL_VARIABLE.ENGLISH_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	private String englishName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column PHYSICAL_VARIABLE.SIMPLE_EN_SPELL
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	private String simpleEnSpell;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column PHYSICAL_VARIABLE.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	private String chineseName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column PHYSICAL_VARIABLE.ENGLISH_META
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	private String englishMeta;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column PHYSICAL_VARIABLE.CHINESE_META
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	private String chineseMeta;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column PHYSICAL_VARIABLE.STANDARD_UNIT
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	private String standardUnit;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column PHYSICAL_VARIABLE.FIELD_IDS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	private String fieldIds;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column PHYSICAL_VARIABLE.ID
	 * 
	 * @return the value of PHYSICAL_VARIABLE.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column PHYSICAL_VARIABLE.ID
	 * 
	 * @param id
	 *            the value for PHYSICAL_VARIABLE.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column PHYSICAL_VARIABLE.ENGLISH_NAME
	 * 
	 * @return the value of PHYSICAL_VARIABLE.ENGLISH_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public String getEnglishName() {
		return englishName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column PHYSICAL_VARIABLE.ENGLISH_NAME
	 * 
	 * @param englishName
	 *            the value for PHYSICAL_VARIABLE.ENGLISH_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column PHYSICAL_VARIABLE.SIMPLE_EN_SPELL
	 * 
	 * @return the value of PHYSICAL_VARIABLE.SIMPLE_EN_SPELL
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public String getSimpleEnSpell() {
		return simpleEnSpell;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column PHYSICAL_VARIABLE.SIMPLE_EN_SPELL
	 * 
	 * @param simpleEnSpell
	 *            the value for PHYSICAL_VARIABLE.SIMPLE_EN_SPELL
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public void setSimpleEnSpell(String simpleEnSpell) {
		this.simpleEnSpell = simpleEnSpell;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column PHYSICAL_VARIABLE.CHINESE_NAME
	 * 
	 * @return the value of PHYSICAL_VARIABLE.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public String getChineseName() {
		return chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column PHYSICAL_VARIABLE.CHINESE_NAME
	 * 
	 * @param chineseName
	 *            the value for PHYSICAL_VARIABLE.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column PHYSICAL_VARIABLE.ENGLISH_META
	 * 
	 * @return the value of PHYSICAL_VARIABLE.ENGLISH_META
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public String getEnglishMeta() {
		return englishMeta;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column PHYSICAL_VARIABLE.ENGLISH_META
	 * 
	 * @param englishMeta
	 *            the value for PHYSICAL_VARIABLE.ENGLISH_META
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public void setEnglishMeta(String englishMeta) {
		this.englishMeta = englishMeta;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column PHYSICAL_VARIABLE.CHINESE_META
	 * 
	 * @return the value of PHYSICAL_VARIABLE.CHINESE_META
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public String getChineseMeta() {
		return chineseMeta;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column PHYSICAL_VARIABLE.CHINESE_META
	 * 
	 * @param chineseMeta
	 *            the value for PHYSICAL_VARIABLE.CHINESE_META
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public void setChineseMeta(String chineseMeta) {
		this.chineseMeta = chineseMeta;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column PHYSICAL_VARIABLE.STANDARD_UNIT
	 * 
	 * @return the value of PHYSICAL_VARIABLE.STANDARD_UNIT
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public String getStandardUnit() {
		return standardUnit;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column PHYSICAL_VARIABLE.STANDARD_UNIT
	 * 
	 * @param standardUnit
	 *            the value for PHYSICAL_VARIABLE.STANDARD_UNIT
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public void setStandardUnit(String standardUnit) {
		this.standardUnit = standardUnit;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column PHYSICAL_VARIABLE.FIELD_IDS
	 * 
	 * @return the value of PHYSICAL_VARIABLE.FIELD_IDS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public String getFieldIds() {
		return fieldIds;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column PHYSICAL_VARIABLE.FIELD_IDS
	 * 
	 * @param fieldIds
	 *            the value for PHYSICAL_VARIABLE.FIELD_IDS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	public void setFieldIds(String fieldIds) {
		this.fieldIds = fieldIds;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table PHYSICAL_VARIABLE
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof PhysicalVariable)) {
			return false;
		}
		PhysicalVariable other = (PhysicalVariable) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getEnglishName() == null ? other.getEnglishName() == null
						: this.getEnglishName().equals(other.getEnglishName()))
				&& (this.getSimpleEnSpell() == null ? other.getSimpleEnSpell() == null
						: this.getSimpleEnSpell().equals(
								other.getSimpleEnSpell()))
				&& (this.getChineseName() == null ? other.getChineseName() == null
						: this.getChineseName().equals(other.getChineseName()))
				&& (this.getEnglishMeta() == null ? other.getEnglishMeta() == null
						: this.getEnglishMeta().equals(other.getEnglishMeta()))
				&& (this.getChineseMeta() == null ? other.getChineseMeta() == null
						: this.getChineseMeta().equals(other.getChineseMeta()))
				&& (this.getStandardUnit() == null ? other.getStandardUnit() == null
						: this.getStandardUnit()
								.equals(other.getStandardUnit()))
				&& (this.getFieldIds() == null ? other.getFieldIds() == null
						: this.getFieldIds().equals(other.getFieldIds()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table PHYSICAL_VARIABLE
	 * 
	 * @ibatorgenerated Wed Jul 21 13:29:23 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getEnglishName() != null) {
			hash *= getEnglishName().hashCode();
		}
		if (getSimpleEnSpell() != null) {
			hash *= getSimpleEnSpell().hashCode();
		}
		if (getChineseName() != null) {
			hash *= getChineseName().hashCode();
		}
		if (getEnglishMeta() != null) {
			hash *= getEnglishMeta().hashCode();
		}
		if (getChineseMeta() != null) {
			hash *= getChineseMeta().hashCode();
		}
		if (getStandardUnit() != null) {
			hash *= getStandardUnit().hashCode();
		}
		if (getFieldIds() != null) {
			hash *= getFieldIds().hashCode();
		}
		return hash;
	}
}