package physics.app.model;

import java.util.Date;

import com.lyt.pallas.jdbc.model.Entity;

public class Scientist extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SCIENTIST.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SCIENTIST.FIRST_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	private String firstName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SCIENTIST.MIDDLE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	private String middleName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SCIENTIST.LAST_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	private String lastName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SCIENTIST.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	private String chineseName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SCIENTIST.BIRTHDAY
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	private Date birthday;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SCIENTIST.DEATHDAY
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	private Date deathday;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SCIENTIST.FIELD_IDS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	private String fieldIds;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SCIENTIST.ID
	 * 
	 * @return the value of SCIENTIST.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SCIENTIST.ID
	 * 
	 * @param id
	 *            the value for SCIENTIST.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SCIENTIST.FIRST_NAME
	 * 
	 * @return the value of SCIENTIST.FIRST_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SCIENTIST.FIRST_NAME
	 * 
	 * @param firstName
	 *            the value for SCIENTIST.FIRST_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SCIENTIST.MIDDLE_NAME
	 * 
	 * @return the value of SCIENTIST.MIDDLE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public String getMiddleName() {
		return middleName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SCIENTIST.MIDDLE_NAME
	 * 
	 * @param middleName
	 *            the value for SCIENTIST.MIDDLE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SCIENTIST.LAST_NAME
	 * 
	 * @return the value of SCIENTIST.LAST_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SCIENTIST.LAST_NAME
	 * 
	 * @param lastName
	 *            the value for SCIENTIST.LAST_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SCIENTIST.CHINESE_NAME
	 * 
	 * @return the value of SCIENTIST.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public String getChineseName() {
		return chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SCIENTIST.CHINESE_NAME
	 * 
	 * @param chineseName
	 *            the value for SCIENTIST.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SCIENTIST.BIRTHDAY
	 * 
	 * @return the value of SCIENTIST.BIRTHDAY
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SCIENTIST.BIRTHDAY
	 * 
	 * @param birthday
	 *            the value for SCIENTIST.BIRTHDAY
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SCIENTIST.DEATHDAY
	 * 
	 * @return the value of SCIENTIST.DEATHDAY
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public Date getDeathday() {
		return deathday;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SCIENTIST.DEATHDAY
	 * 
	 * @param deathday
	 *            the value for SCIENTIST.DEATHDAY
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public void setDeathday(Date deathday) {
		this.deathday = deathday;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SCIENTIST.FIELD_IDS
	 * 
	 * @return the value of SCIENTIST.FIELD_IDS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public String getFieldIds() {
		return fieldIds;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SCIENTIST.FIELD_IDS
	 * 
	 * @param fieldIds
	 *            the value for SCIENTIST.FIELD_IDS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	public void setFieldIds(String fieldIds) {
		this.fieldIds = fieldIds;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table SCIENTIST
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof Scientist)) {
			return false;
		}
		Scientist other = (Scientist) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getFirstName() == null ? other.getFirstName() == null
						: this.getFirstName().equals(other.getFirstName()))
				&& (this.getMiddleName() == null ? other.getMiddleName() == null
						: this.getMiddleName().equals(other.getMiddleName()))
				&& (this.getLastName() == null ? other.getLastName() == null
						: this.getLastName().equals(other.getLastName()))
				&& (this.getChineseName() == null ? other.getChineseName() == null
						: this.getChineseName().equals(other.getChineseName()))
				&& (this.getBirthday() == null ? other.getBirthday() == null
						: this.getBirthday().equals(other.getBirthday()))
				&& (this.getDeathday() == null ? other.getDeathday() == null
						: this.getDeathday().equals(other.getDeathday()))
				&& (this.getFieldIds() == null ? other.getFieldIds() == null
						: this.getFieldIds().equals(other.getFieldIds()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table SCIENTIST
	 * 
	 * @ibatorgenerated Wed Jul 21 13:30:34 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getFirstName() != null) {
			hash *= getFirstName().hashCode();
		}
		if (getMiddleName() != null) {
			hash *= getMiddleName().hashCode();
		}
		if (getLastName() != null) {
			hash *= getLastName().hashCode();
		}
		if (getChineseName() != null) {
			hash *= getChineseName().hashCode();
		}
		if (getBirthday() != null) {
			hash *= getBirthday().hashCode();
		}
		if (getDeathday() != null) {
			hash *= getDeathday().hashCode();
		}
		if (getFieldIds() != null) {
			hash *= getFieldIds().hashCode();
		}
		return hash;
	}
}