package physics.app.model;

import java.math.BigDecimal;

import com.lyt.pallas.jdbc.model.Entity;

public class SolarSystem extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SOLAR_SYSTEM.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SOLAR_SYSTEM.PLANET_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	private Long planetId;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SOLAR_SYSTEM.EQUATERIAL_DIAMETER
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	private BigDecimal equaterialDiameter;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SOLAR_SYSTEM.E_D_UNIT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	private Long eDUnitId;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SOLAR_SYSTEM.MEAN_DISTANCE_FROM_SUN
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	private BigDecimal meanDistanceFromSun;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SOLAR_SYSTEM.M_D_F_S_UNIT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	private Long mDFSUnitId;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SOLAR_SYSTEM.SIDEREAL_PERIOD
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	private BigDecimal siderealPeriod;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column SOLAR_SYSTEM.S_P_UNIT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	private Long sPUnitId;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SOLAR_SYSTEM.ID
	 * 
	 * @return the value of SOLAR_SYSTEM.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SOLAR_SYSTEM.ID
	 * 
	 * @param id
	 *            the value for SOLAR_SYSTEM.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SOLAR_SYSTEM.PLANET_ID
	 * 
	 * @return the value of SOLAR_SYSTEM.PLANET_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public Long getPlanetId() {
		return planetId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SOLAR_SYSTEM.PLANET_ID
	 * 
	 * @param planetId
	 *            the value for SOLAR_SYSTEM.PLANET_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public void setPlanetId(Long planetId) {
		this.planetId = planetId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SOLAR_SYSTEM.EQUATERIAL_DIAMETER
	 * 
	 * @return the value of SOLAR_SYSTEM.EQUATERIAL_DIAMETER
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public BigDecimal getEquaterialDiameter() {
		return equaterialDiameter;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SOLAR_SYSTEM.EQUATERIAL_DIAMETER
	 * 
	 * @param equaterialDiameter
	 *            the value for SOLAR_SYSTEM.EQUATERIAL_DIAMETER
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public void setEquaterialDiameter(BigDecimal equaterialDiameter) {
		this.equaterialDiameter = equaterialDiameter;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SOLAR_SYSTEM.E_D_UNIT_ID
	 * 
	 * @return the value of SOLAR_SYSTEM.E_D_UNIT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public Long geteDUnitId() {
		return eDUnitId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SOLAR_SYSTEM.E_D_UNIT_ID
	 * 
	 * @param eDUnitId
	 *            the value for SOLAR_SYSTEM.E_D_UNIT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public void seteDUnitId(Long eDUnitId) {
		this.eDUnitId = eDUnitId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SOLAR_SYSTEM.MEAN_DISTANCE_FROM_SUN
	 * 
	 * @return the value of SOLAR_SYSTEM.MEAN_DISTANCE_FROM_SUN
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public BigDecimal getMeanDistanceFromSun() {
		return meanDistanceFromSun;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SOLAR_SYSTEM.MEAN_DISTANCE_FROM_SUN
	 * 
	 * @param meanDistanceFromSun
	 *            the value for SOLAR_SYSTEM.MEAN_DISTANCE_FROM_SUN
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public void setMeanDistanceFromSun(BigDecimal meanDistanceFromSun) {
		this.meanDistanceFromSun = meanDistanceFromSun;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SOLAR_SYSTEM.M_D_F_S_UNIT_ID
	 * 
	 * @return the value of SOLAR_SYSTEM.M_D_F_S_UNIT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public Long getmDFSUnitId() {
		return mDFSUnitId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SOLAR_SYSTEM.M_D_F_S_UNIT_ID
	 * 
	 * @param mDFSUnitId
	 *            the value for SOLAR_SYSTEM.M_D_F_S_UNIT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public void setmDFSUnitId(Long mDFSUnitId) {
		this.mDFSUnitId = mDFSUnitId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SOLAR_SYSTEM.SIDEREAL_PERIOD
	 * 
	 * @return the value of SOLAR_SYSTEM.SIDEREAL_PERIOD
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public BigDecimal getSiderealPeriod() {
		return siderealPeriod;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SOLAR_SYSTEM.SIDEREAL_PERIOD
	 * 
	 * @param siderealPeriod
	 *            the value for SOLAR_SYSTEM.SIDEREAL_PERIOD
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public void setSiderealPeriod(BigDecimal siderealPeriod) {
		this.siderealPeriod = siderealPeriod;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column SOLAR_SYSTEM.S_P_UNIT_ID
	 * 
	 * @return the value of SOLAR_SYSTEM.S_P_UNIT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public Long getsPUnitId() {
		return sPUnitId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column SOLAR_SYSTEM.S_P_UNIT_ID
	 * 
	 * @param sPUnitId
	 *            the value for SOLAR_SYSTEM.S_P_UNIT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	public void setsPUnitId(Long sPUnitId) {
		this.sPUnitId = sPUnitId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table SOLAR_SYSTEM
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof SolarSystem)) {
			return false;
		}
		SolarSystem other = (SolarSystem) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getPlanetId() == null ? other.getPlanetId() == null
						: this.getPlanetId().equals(other.getPlanetId()))
				&& (this.getEquaterialDiameter() == null ? other
						.getEquaterialDiameter() == null : this
						.getEquaterialDiameter().equals(
								other.getEquaterialDiameter()))
				&& (this.geteDUnitId() == null ? other.geteDUnitId() == null
						: this.geteDUnitId().equals(other.geteDUnitId()))
				&& (this.getMeanDistanceFromSun() == null ? other
						.getMeanDistanceFromSun() == null : this
						.getMeanDistanceFromSun().equals(
								other.getMeanDistanceFromSun()))
				&& (this.getmDFSUnitId() == null ? other.getmDFSUnitId() == null
						: this.getmDFSUnitId().equals(other.getmDFSUnitId()))
				&& (this.getSiderealPeriod() == null ? other
						.getSiderealPeriod() == null : this.getSiderealPeriod()
						.equals(other.getSiderealPeriod()))
				&& (this.getsPUnitId() == null ? other.getsPUnitId() == null
						: this.getsPUnitId().equals(other.getsPUnitId()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table SOLAR_SYSTEM
	 * 
	 * @ibatorgenerated Wed Jul 21 13:32:31 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getPlanetId() != null) {
			hash *= getPlanetId().hashCode();
		}
		if (getEquaterialDiameter() != null) {
			hash *= getEquaterialDiameter().hashCode();
		}
		if (geteDUnitId() != null) {
			hash *= geteDUnitId().hashCode();
		}
		if (getMeanDistanceFromSun() != null) {
			hash *= getMeanDistanceFromSun().hashCode();
		}
		if (getmDFSUnitId() != null) {
			hash *= getmDFSUnitId().hashCode();
		}
		if (getSiderealPeriod() != null) {
			hash *= getSiderealPeriod().hashCode();
		}
		if (getsPUnitId() != null) {
			hash *= getsPUnitId().hashCode();
		}
		return hash;
	}
}