package physics.app.model;

import com.lyt.pallas.jdbc.model.Entity;

public class StarCluster extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column STAR_CLUSTER.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:33:42 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column STAR_CLUSTER.STAR_CLUSTER_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:33:42 CST 2010
	 */
	private String starClusterName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column STAR_CLUSTER.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:33:42 CST 2010
	 */
	private String chineseName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column STAR_CLUSTER.GALAXY_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:33:42 CST 2010
	 */
	private Long galaxyId;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column STAR_CLUSTER.ID
	 * 
	 * @return the value of STAR_CLUSTER.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:33:42 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column STAR_CLUSTER.ID
	 * 
	 * @param id
	 *            the value for STAR_CLUSTER.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:33:42 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column STAR_CLUSTER.STAR_CLUSTER_NAME
	 * 
	 * @return the value of STAR_CLUSTER.STAR_CLUSTER_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:33:42 CST 2010
	 */
	public String getStarClusterName() {
		return starClusterName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column STAR_CLUSTER.STAR_CLUSTER_NAME
	 * 
	 * @param starClusterName
	 *            the value for STAR_CLUSTER.STAR_CLUSTER_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:33:42 CST 2010
	 */
	public void setStarClusterName(String starClusterName) {
		this.starClusterName = starClusterName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column STAR_CLUSTER.CHINESE_NAME
	 * 
	 * @return the value of STAR_CLUSTER.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:33:42 CST 2010
	 */
	public String getChineseName() {
		return chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column STAR_CLUSTER.CHINESE_NAME
	 * 
	 * @param chineseName
	 *            the value for STAR_CLUSTER.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:33:42 CST 2010
	 */
	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column STAR_CLUSTER.GALAXY_ID
	 * 
	 * @return the value of STAR_CLUSTER.GALAXY_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:33:42 CST 2010
	 */
	public Long getGalaxyId() {
		return galaxyId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column STAR_CLUSTER.GALAXY_ID
	 * 
	 * @param galaxyId
	 *            the value for STAR_CLUSTER.GALAXY_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:33:42 CST 2010
	 */
	public void setGalaxyId(Long galaxyId) {
		this.galaxyId = galaxyId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table STAR_CLUSTER
	 * 
	 * @ibatorgenerated Wed Jul 21 13:33:42 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof StarCluster)) {
			return false;
		}
		StarCluster other = (StarCluster) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getStarClusterName() == null ? other
						.getStarClusterName() == null : this
						.getStarClusterName()
						.equals(other.getStarClusterName()))
				&& (this.getChineseName() == null ? other.getChineseName() == null
						: this.getChineseName().equals(other.getChineseName()))
				&& (this.getGalaxyId() == null ? other.getGalaxyId() == null
						: this.getGalaxyId().equals(other.getGalaxyId()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table STAR_CLUSTER
	 * 
	 * @ibatorgenerated Wed Jul 21 13:33:42 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getStarClusterName() != null) {
			hash *= getStarClusterName().hashCode();
		}
		if (getChineseName() != null) {
			hash *= getChineseName().hashCode();
		}
		if (getGalaxyId() != null) {
			hash *= getGalaxyId().hashCode();
		}
		return hash;
	}
}