package physics.app.model;

import com.lyt.pallas.jdbc.model.Entity;

public class TreeMenu extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column TREE_MENU.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column TREE_MENU.IS_LEAF
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	private String isLeaf;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column TREE_MENU.NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	private String name;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column TREE_MENU.URL_PATH
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	private String urlPath;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column TREE_MENU.URL_CODE
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	private String urlCode;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column TREE_MENU.PARENT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	private Long parentId;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column TREE_MENU.ORDER_NUM
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	private Long orderNum;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column TREE_MENU.ID
	 * 
	 * @return the value of TREE_MENU.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column TREE_MENU.ID
	 * 
	 * @param id
	 *            the value for TREE_MENU.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column TREE_MENU.IS_LEAF
	 * 
	 * @return the value of TREE_MENU.IS_LEAF
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	public String getIsLeaf() {
		return isLeaf;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column TREE_MENU.IS_LEAF
	 * 
	 * @param isLeaf
	 *            the value for TREE_MENU.IS_LEAF
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	public void setIsLeaf(String isLeaf) {
		this.isLeaf = isLeaf;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column TREE_MENU.NAME
	 * 
	 * @return the value of TREE_MENU.NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column TREE_MENU.NAME
	 * 
	 * @param name
	 *            the value for TREE_MENU.NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column TREE_MENU.URL_PATH
	 * 
	 * @return the value of TREE_MENU.URL_PATH
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	public String getUrlPath() {
		return urlPath;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column TREE_MENU.URL_PATH
	 * 
	 * @param urlPath
	 *            the value for TREE_MENU.URL_PATH
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	public void setUrlPath(String urlPath) {
		this.urlPath = urlPath;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column TREE_MENU.URL_CODE
	 * 
	 * @return the value of TREE_MENU.URL_CODE
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	public String getUrlCode() {
		return urlCode;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column TREE_MENU.URL_CODE
	 * 
	 * @param urlCode
	 *            the value for TREE_MENU.URL_CODE
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	public void setUrlCode(String urlCode) {
		this.urlCode = urlCode;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column TREE_MENU.PARENT_ID
	 * 
	 * @return the value of TREE_MENU.PARENT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	public Long getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column TREE_MENU.PARENT_ID
	 * 
	 * @param parentId
	 *            the value for TREE_MENU.PARENT_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column TREE_MENU.ORDER_NUM
	 * 
	 * @return the value of TREE_MENU.ORDER_NUM
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	public Long getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column TREE_MENU.ORDER_NUM
	 * 
	 * @param orderNum
	 *            the value for TREE_MENU.ORDER_NUM
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	public void setOrderNum(Long orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table TREE_MENU
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof TreeMenu)) {
			return false;
		}
		TreeMenu other = (TreeMenu) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getIsLeaf() == null ? other.getIsLeaf() == null : this
						.getIsLeaf().equals(other.getIsLeaf()))
				&& (this.getName() == null ? other.getName() == null : this
						.getName().equals(other.getName()))
				&& (this.getUrlPath() == null ? other.getUrlPath() == null
						: this.getUrlPath().equals(other.getUrlPath()))
				&& (this.getUrlCode() == null ? other.getUrlCode() == null
						: this.getUrlCode().equals(other.getUrlCode()))
				&& (this.getParentId() == null ? other.getParentId() == null
						: this.getParentId().equals(other.getParentId()))
				&& (this.getOrderNum() == null ? other.getOrderNum() == null
						: this.getOrderNum().equals(other.getOrderNum()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table TREE_MENU
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:01 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getIsLeaf() != null) {
			hash *= getIsLeaf().hashCode();
		}
		if (getName() != null) {
			hash *= getName().hashCode();
		}
		if (getUrlPath() != null) {
			hash *= getUrlPath().hashCode();
		}
		if (getUrlCode() != null) {
			hash *= getUrlCode().hashCode();
		}
		if (getParentId() != null) {
			hash *= getParentId().hashCode();
		}
		if (getOrderNum() != null) {
			hash *= getOrderNum().hashCode();
		}
		return hash;
	}
}