package physics.app.model;

import com.lyt.pallas.jdbc.model.Entity;

public class Unit extends Entity {
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column UNIT.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column UNIT.SCIENCIST_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	private Long sciencistId;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column UNIT.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	private String chineseName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column UNIT.UNIT_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	private String unitName;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column UNIT.JSON_DATA_OF_UNIT_ID_AND_POWER
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	private String jsonDataOfUnitIdAndPower;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column UNIT.SYMBOL
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	private String symbol;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column UNIT.COMMENTS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	private String comments;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column UNIT.ENGLISH_COMMENT
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	private String englishComment;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column UNIT.ISBASIC
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	private String isbasic;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column UNIT.ID
	 * 
	 * @return the value of UNIT.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column UNIT.ID
	 * 
	 * @param id
	 *            the value for UNIT.ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column UNIT.SCIENCIST_ID
	 * 
	 * @return the value of UNIT.SCIENCIST_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public Long getSciencistId() {
		return sciencistId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column UNIT.SCIENCIST_ID
	 * 
	 * @param sciencistId
	 *            the value for UNIT.SCIENCIST_ID
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public void setSciencistId(Long sciencistId) {
		this.sciencistId = sciencistId;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column UNIT.CHINESE_NAME
	 * 
	 * @return the value of UNIT.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public String getChineseName() {
		return chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column UNIT.CHINESE_NAME
	 * 
	 * @param chineseName
	 *            the value for UNIT.CHINESE_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column UNIT.UNIT_NAME
	 * 
	 * @return the value of UNIT.UNIT_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public String getUnitName() {
		return unitName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column UNIT.UNIT_NAME
	 * 
	 * @param unitName
	 *            the value for UNIT.UNIT_NAME
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column UNIT.JSON_DATA_OF_UNIT_ID_AND_POWER
	 * 
	 * @return the value of UNIT.JSON_DATA_OF_UNIT_ID_AND_POWER
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public String getJsonDataOfUnitIdAndPower() {
		return jsonDataOfUnitIdAndPower;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column UNIT.JSON_DATA_OF_UNIT_ID_AND_POWER
	 * 
	 * @param jsonDataOfUnitIdAndPower
	 *            the value for UNIT.JSON_DATA_OF_UNIT_ID_AND_POWER
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public void setJsonDataOfUnitIdAndPower(String jsonDataOfUnitIdAndPower) {
		this.jsonDataOfUnitIdAndPower = jsonDataOfUnitIdAndPower;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column UNIT.SYMBOL
	 * 
	 * @return the value of UNIT.SYMBOL
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public String getSymbol() {
		return symbol;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column UNIT.SYMBOL
	 * 
	 * @param symbol
	 *            the value for UNIT.SYMBOL
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column UNIT.COMMENTS
	 * 
	 * @return the value of UNIT.COMMENTS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public String getComments() {
		return comments;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column UNIT.COMMENTS
	 * 
	 * @param comments
	 *            the value for UNIT.COMMENTS
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column UNIT.ENGLISH_COMMENT
	 * 
	 * @return the value of UNIT.ENGLISH_COMMENT
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public String getEnglishComment() {
		return englishComment;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column UNIT.ENGLISH_COMMENT
	 * 
	 * @param englishComment
	 *            the value for UNIT.ENGLISH_COMMENT
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public void setEnglishComment(String englishComment) {
		this.englishComment = englishComment;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column UNIT.ISBASIC
	 * 
	 * @return the value of UNIT.ISBASIC
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public String getIsbasic() {
		return isbasic;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column UNIT.ISBASIC
	 * 
	 * @param isbasic
	 *            the value for UNIT.ISBASIC
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	public void setIsbasic(String isbasic) {
		this.isbasic = isbasic;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table UNIT
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof Unit)) {
			return false;
		}
		Unit other = (Unit) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getSciencistId() == null ? other.getSciencistId() == null
						: this.getSciencistId().equals(other.getSciencistId()))
				&& (this.getChineseName() == null ? other.getChineseName() == null
						: this.getChineseName().equals(other.getChineseName()))
				&& (this.getUnitName() == null ? other.getUnitName() == null
						: this.getUnitName().equals(other.getUnitName()))
				&& (this.getJsonDataOfUnitIdAndPower() == null ? other
						.getJsonDataOfUnitIdAndPower() == null : this
						.getJsonDataOfUnitIdAndPower().equals(
								other.getJsonDataOfUnitIdAndPower()))
				&& (this.getSymbol() == null ? other.getSymbol() == null : this
						.getSymbol().equals(other.getSymbol()))
				&& (this.getComments() == null ? other.getComments() == null
						: this.getComments().equals(other.getComments()))
				&& (this.getEnglishComment() == null ? other
						.getEnglishComment() == null : this.getEnglishComment()
						.equals(other.getEnglishComment()))
				&& (this.getIsbasic() == null ? other.getIsbasic() == null
						: this.getIsbasic().equals(other.getIsbasic()));
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table UNIT
	 * 
	 * @ibatorgenerated Wed Jul 21 13:36:54 CST 2010
	 */
	
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getSciencistId() != null) {
			hash *= getSciencistId().hashCode();
		}
		if (getChineseName() != null) {
			hash *= getChineseName().hashCode();
		}
		if (getUnitName() != null) {
			hash *= getUnitName().hashCode();
		}
		if (getJsonDataOfUnitIdAndPower() != null) {
			hash *= getJsonDataOfUnitIdAndPower().hashCode();
		}
		if (getSymbol() != null) {
			hash *= getSymbol().hashCode();
		}
		if (getComments() != null) {
			hash *= getComments().hashCode();
		}
		if (getEnglishComment() != null) {
			hash *= getEnglishComment().hashCode();
		}
		if (getIsbasic() != null) {
			hash *= getIsbasic().hashCode();
		}
		return hash;
	}
}